import { zodResolver } from "@hookform/resolvers/zod";
import { useMissionActivateMissionCommand, useMissionCompleteMissionCommand, useMissionRenameMissionCommand } from "@bba/sdk-react";
import { Button, ConfirmationDialog, Field, Input, Textarea } from "@bba/ui";
import { FormProvider, useForm } from "react-hook-form";
import { CommandFeedback } from "../../../shared/CommandFeedback.js"; import { CommandReceiptView } from "../../../shared/CommandReceiptView.js";
import { EvidenceFields, ReasonField, TimestampField } from "../../../shared/forms/institutional-fields.js"; import { auditDefaults } from "../common.js";
import { mapCompleteMission, mapDecisionMission, mapRenameMission } from "./mapper.js"; import { completeMissionSchema, decisionMissionSchema, renameMissionSchema, type CompleteMissionFormValues, type DecisionMissionFormValues, type RenameMissionFormValues } from "./schema.js";

function receipt(state: ReturnType<typeof useMissionRenameMissionCommand>["state"], missionId: string) { return state.status === "COMMITTED" ? <CommandReceiptView receipt={state.receipt} returnTo={`/missions/${missionId}`} /> : null; }
export function RenameMissionForm({ missionId, version }: { readonly missionId: string; readonly version: number }) { const command = useMissionRenameMissionCommand(); const audit = auditDefaults(); const form = useForm<RenameMissionFormValues>({ resolver: zodResolver(renameMissionSchema), defaultValues: { reason: "", title: "", expectedVersion: version, occurredAt: audit.occurredAt } }); const done = receipt(command.state, missionId); if (done) return done; return <FormProvider {...form}><form className="bba-form" onChange={command.edited} onSubmit={form.handleSubmit((values) => command.submit(mapRenameMission(missionId, values), values.reason))}><Field label="New title" id="newTitle"><Input id="newTitle" {...form.register("title")} /></Field><Input type="hidden" {...form.register("expectedVersion")} /><TimestampField label="Occurred at" name="occurredAt" /><ReasonField /><CommandFeedback state={command.state} onRetry={() => { void command.retry(); }} /><Button disabled={command.state.status === "SUBMITTING"} type="submit">Rename Mission</Button></form></FormProvider>; }
export function ActivateMissionForm({ missionId, version }: { readonly missionId: string; readonly version: number }) { const command = useMissionActivateMissionCommand(); const audit = auditDefaults(); const form = useForm<DecisionMissionFormValues>({ resolver: zodResolver(decisionMissionSchema), defaultValues: { reason: "", expectedVersion: version, authorityReference: "", decisionReference: "", approvalReference: "", occurredAt: audit.occurredAt, evidence: audit.evidence } }); if (command.state.status === "COMMITTED") return <CommandReceiptView receipt={command.state.receipt} returnTo={`/missions/${missionId}`} />; return <FormProvider {...form}><form className="bba-form" onChange={command.edited} onSubmit={form.handleSubmit((values) => command.submit(mapDecisionMission(missionId, values), values.reason))}><Input type="hidden" {...form.register("expectedVersion")} /><Field label="Authority reference" id="authorityReference"><Input id="authorityReference" {...form.register("authorityReference")} /></Field><Field label="Decision reference (optional)" id="decisionReference"><Input id="decisionReference" {...form.register("decisionReference")} /></Field><Field label="Approval reference (optional)" id="approvalReference"><Input id="approvalReference" {...form.register("approvalReference")} /></Field><TimestampField label="Occurred at" name="occurredAt" /><ReasonField /><EvidenceFields /><CommandFeedback state={command.state} onRetry={() => { void command.retry(); }} /><Button disabled={command.state.status === "SUBMITTING"} type="submit">Activate Mission</Button></form></FormProvider>; }
export function CompleteMissionForm({ missionId, version }: { readonly missionId: string; readonly version: number }) { const command = useMissionCompleteMissionCommand(); const audit = auditDefaults(); const form = useForm<CompleteMissionFormValues>({ resolver: zodResolver(completeMissionSchema), defaultValues: { reason: "", expectedVersion: version, authorityReference: "", decisionReference: "", approvalReference: "", occurredAt: audit.occurredAt, evidence: audit.evidence, result: "", learning: "", limitations: "", residualObligations: "" } }); if (command.state.status === "COMMITTED") return <CommandReceiptView receipt={command.state.receipt} returnTo={`/missions/${missionId}`} />; const submit = form.handleSubmit((values) => command.submit(mapCompleteMission(missionId, values), values.reason)); return <FormProvider {...form}><form className="bba-form" onChange={command.edited}><Input type="hidden" {...form.register("expectedVersion")} /><Field label="Authority reference" id="completeAuthority"><Input id="completeAuthority" {...form.register("authorityReference")} /></Field><Field label="Decision reference" id="completeDecision"><Input id="completeDecision" {...form.register("decisionReference")} /></Field><Field label="Approval reference" id="completeApproval"><Input id="completeApproval" {...form.register("approvalReference")} /></Field><Field label="Result" id="result"><Textarea id="result" {...form.register("result")} /></Field><Field label="Learning" id="learning"><Textarea id="learning" {...form.register("learning")} /></Field><Field label="Limitations" id="limitations"><Textarea id="limitations" {...form.register("limitations")} /></Field><Field label="Residual obligations" id="residualObligations"><Textarea id="residualObligations" {...form.register("residualObligations")} /></Field><TimestampField label="Occurred at" name="occurredAt" /><ReasonField /><EvidenceFields /><CommandFeedback state={command.state} onRetry={() => { void command.retry(); }} /><ConfirmationDialog confirmLabel="Complete Mission" description={<><p>This closes the Mission with the recorded outcome.</p><p>Operational reason: {form.watch("reason") || "Not provided"}</p></>} onConfirm={() => { void submit(); }} title="Complete Mission" trigger={<Button disabled={command.state.status === "SUBMITTING"} type="button">Review completion</Button>} /></form></FormProvider>; }
