import type { JsonObject } from "../../../shared/common/serialization.js";
import { InvariantViolation } from "../../../shared/errors/InvariantViolation.js";
import { DecisionReference, InstitutionalActorReference } from "../../../shared/references/index.js";
import { ValueObject } from "../../../shared/valueobject/ValueObject.js";

export interface AssetAuthorityContextProps { readonly ownerReference: InstitutionalActorReference; readonly stewardReference: InstitutionalActorReference; readonly custodianReference: InstitutionalActorReference; readonly authorReferences: readonly InstitutionalActorReference[]; readonly decisionReference?: DecisionReference; }
export class AssetAuthorityContext extends ValueObject<JsonObject> {
  public readonly ownerReference: InstitutionalActorReference; public readonly stewardReference: InstitutionalActorReference; public readonly custodianReference: InstitutionalActorReference; public readonly authorReferences: readonly InstitutionalActorReference[]; public readonly decisionReference: DecisionReference | undefined;
  public constructor(props: AssetAuthorityContextProps) { const tenant = props.ownerReference.tenantId; const refs = [props.stewardReference, props.custodianReference, ...props.authorReferences]; if (props.authorReferences.length === 0) throw new InvariantViolation("AssetAuthorityContext requires at least one Author"); if (refs.some((item) => !item.tenantId.equals(tenant)) || (props.decisionReference !== undefined && !props.decisionReference.tenantId.equals(tenant))) throw new InvariantViolation("AssetAuthorityContext cannot cross a Tenant boundary"); super({ ownerReference: props.ownerReference.toJSON(), stewardReference: props.stewardReference.toJSON(), custodianReference: props.custodianReference.toJSON(), authorReferences: props.authorReferences.map((item) => item.toJSON()), ...(props.decisionReference ? { decisionReference: props.decisionReference.toJSON() } : {}) }); this.ownerReference = props.ownerReference; this.stewardReference = props.stewardReference; this.custodianReference = props.custodianReference; this.authorReferences = Object.freeze([...props.authorReferences]); this.decisionReference = props.decisionReference; Object.freeze(this); }
  public get tenantId() { return this.ownerReference.tenantId; }
  public static fromJSON(value: JsonObject): AssetAuthorityContext { return new AssetAuthorityContext({ ownerReference: InstitutionalActorReference.fromJSON(value.ownerReference as { reference: string; tenantId: string }), stewardReference: InstitutionalActorReference.fromJSON(value.stewardReference as { reference: string; tenantId: string }), custodianReference: InstitutionalActorReference.fromJSON(value.custodianReference as { reference: string; tenantId: string }), authorReferences: Array.isArray(value.authorReferences) ? value.authorReferences.map((item) => InstitutionalActorReference.fromJSON(item as { reference: string; tenantId: string })) : [], ...(value.decisionReference ? { decisionReference: DecisionReference.fromJSON(value.decisionReference as { id: string; tenantId: string }) } : {}) }); }
}
