import { AggregateRoot } from "../../../shared/aggregate/AggregateRoot.js";
import type { CausationId, CorrelationId } from "../../../shared/common/index.js";
import type { JsonObject } from "../../../shared/common/serialization.js";
import { InvariantViolation } from "../../../shared/errors/InvariantViolation.js";
import type { EvidenceReference } from "../../../shared/evidence/EvidenceReference.js";
import { AssetId, AssetVersionId, TenantId } from "../../../shared/identity/index.js";
import type { LineageReference } from "../../../shared/lineage/LineageReference.js";
import { AssetReference, AssetVersionReference, MissionReference } from "../../../shared/references/index.js";
import { Version } from "../../../shared/version/Version.js";
import { AssetAuthorityContext } from "./AssetAuthorityContext.js";
import { AssetClassification } from "./AssetClassification.js";
import type { AddAssetRelationshipCommand, ArchiveAssetCommand, AssetAuditInput, CreateAssetCommand, CreateAssetVersionCommand, ProduceAssetCommand, SupersedeAssetCommand } from "./AssetCommands.js";
import { AssetArchived, AssetCreated, AssetProduced, AssetRelationshipCreated, AssetSuperseded, AssetVersionCreated } from "./AssetEvents.js";
import { AssetMetadata } from "./AssetMetadata.js";
import { AssetRelationship } from "./AssetRelationship.js";
import type { AssetStatus } from "./AssetStatus.js";
import { AssetVersion } from "./AssetVersion.js";
import { AssetVersionNumber } from "./AssetVersionNumber.js";

export interface AssetSnapshot { readonly schemaVersion: 1; readonly assetId: string; readonly tenantId: string; readonly missionReference: JsonObject; readonly metadata: JsonObject; readonly classification: JsonObject; readonly authorityContext: JsonObject; readonly status: AssetStatus; readonly versions: readonly JsonObject[]; readonly currentVersionId: string; readonly relationships: readonly JsonObject[]; readonly supersededBy: JsonObject | null; readonly version: number; }
const CANONICAL_STATUSES = new Set<AssetStatus>(["PROPOSED", "PRODUCED", "UNDER_REVIEW", "APPROVED", "PUBLISHED", "ARCHIVED", "SUPERSEDED", "REJECTED"]);

export class Asset extends AggregateRoot<AssetId> {
  private readonly assetTenantId: TenantId; private readonly assetMissionReference: MissionReference; private readonly assetMetadata: AssetMetadata; private readonly assetClassification: AssetClassification; private readonly assetAuthorityContext: AssetAuthorityContext;
  private assetStatus: AssetStatus; private assetVersions: AssetVersion[]; private assetCurrentVersionId: AssetVersionId; private assetRelationships: AssetRelationship[]; private assetSupersededBy: AssetReference | null;
  private constructor(id: AssetId, state: { tenantId: TenantId; missionReference: MissionReference; metadata: AssetMetadata; classification: AssetClassification; authorityContext: AssetAuthorityContext; status: AssetStatus; versions: AssetVersion[]; currentVersionId: AssetVersionId; relationships: AssetRelationship[]; supersededBy: AssetReference | null; version: Version }) { super(id, state.version); if (!CANONICAL_STATUSES.has(state.status)) throw new InvariantViolation("Asset status is not canonical"); if (!state.missionReference.tenantId.equals(state.tenantId) || !state.authorityContext.tenantId.equals(state.tenantId)) throw new InvariantViolation("Asset context cannot cross a Tenant boundary"); this.assetTenantId = state.tenantId; this.assetMissionReference = state.missionReference; this.assetMetadata = state.metadata; this.assetClassification = state.classification; this.assetAuthorityContext = state.authorityContext; this.assetStatus = state.status; this.assetVersions = [...state.versions]; this.assetCurrentVersionId = state.currentVersionId; this.assetRelationships = [...state.relationships]; this.assetSupersededBy = state.supersededBy; this.assertState(); }
  public static create(command: CreateAssetCommand): Asset { if (!command.authorityDecisionReference.tenantId.equals(command.tenantId)) throw new InvariantViolation("Asset version decision must belong to the Asset Tenant"); const version = new AssetVersion({ id: command.initialVersionId, assetId: command.assetId, tenantId: command.tenantId, number: new AssetVersionNumber(1), content: command.content, reason: command.reason, authorityDecisionReference: command.authorityDecisionReference, evidence: command.evidence, lineage: command.lineage, createdAt: command.occurredAt }); const asset = new Asset(command.assetId, { tenantId: command.tenantId, missionReference: command.missionReference, metadata: command.metadata, classification: command.classification, authorityContext: command.authorityContext, status: "PROPOSED", versions: [version], currentVersionId: version.id, relationships: [], supersededBy: null, version: Version.initial() }); asset.incrementVersion(); asset.emit(AssetCreated, command, { status: "PROPOSED", currentVersionId: version.id.toString() }); asset.emit(AssetVersionCreated, command, { versionId: version.id.toString(), number: 1 }); return asset; }
  public static rehydrate(snapshot: AssetSnapshot): Asset { if (snapshot.schemaVersion !== 1) throw new InvariantViolation("Unsupported Asset snapshot schema"); return new Asset(AssetId.from(snapshot.assetId), { tenantId: TenantId.from(snapshot.tenantId), missionReference: MissionReference.fromJSON(snapshot.missionReference as { id: string; tenantId: string }), metadata: AssetMetadata.fromJSON(snapshot.metadata), classification: AssetClassification.fromJSON(snapshot.classification), authorityContext: AssetAuthorityContext.fromJSON(snapshot.authorityContext), status: snapshot.status, versions: snapshot.versions.map((item) => AssetVersion.fromSnapshot(item)), currentVersionId: AssetVersionId.from(snapshot.currentVersionId), relationships: snapshot.relationships.map((item) => AssetRelationship.fromJSON(item)), supersededBy: snapshot.supersededBy ? AssetReference.fromJSON(snapshot.supersededBy as { id: string; tenantId: string }) : null, version: Version.from(snapshot.version) }); }
  public get tenantId(): TenantId { return this.assetTenantId; } public get missionReference(): MissionReference { return this.assetMissionReference; } public get metadata(): AssetMetadata { return this.assetMetadata; } public get classification(): AssetClassification { return this.assetClassification; } public get authorityContext(): AssetAuthorityContext { return this.assetAuthorityContext; } public get status(): AssetStatus { return this.assetStatus; } public get versions(): readonly AssetVersion[] { return [...this.assetVersions]; } public get currentVersionId(): AssetVersionId { return this.assetCurrentVersionId; } public get currentAssetVersion(): AssetVersion { const version = this.assetVersions.find((item) => item.id.equals(this.currentVersionId)); if (version === undefined) throw new InvariantViolation("Asset current version is missing"); return version; } public get relationships(): readonly AssetRelationship[] { return [...this.assetRelationships]; } public get supersededBy(): AssetReference | null { return this.assetSupersededBy; }
  public produce(command: ProduceAssetCommand): void { if (this.assetStatus !== "PROPOSED") throw new InvariantViolation(`Asset cannot be produced from ${this.assetStatus}`); this.assertGovernedTenant(command); this.assetStatus = "PRODUCED"; this.incrementVersion(); this.emit(AssetProduced, command, { currentVersionId: this.currentVersionId.toString() }); }
  public createVersion(command: CreateAssetVersionCommand): AssetVersion { if (this.assetStatus !== "PROPOSED" && this.assetStatus !== "PRODUCED") throw new InvariantViolation(`Asset cannot create a version from ${this.assetStatus}`); if (!command.authorityDecisionReference.tenantId.equals(this.tenantId)) throw new InvariantViolation("AssetVersion decision crossed a Tenant boundary"); if (this.assetVersions.some((item) => item.id.equals(command.versionId))) throw new InvariantViolation("AssetVersionId already exists"); const nextNumber = new AssetVersionNumber(Math.max(...this.assetVersions.map((item) => item.number.value)) + 1); const version = new AssetVersion({ id: command.versionId, assetId: this.id, tenantId: this.tenantId, number: nextNumber, content: command.content, predecessorReference: new AssetVersionReference(this.id, this.currentVersionId, this.tenantId), reason: command.reason, authorityDecisionReference: command.authorityDecisionReference, evidence: command.evidence, lineage: command.lineage, createdAt: command.occurredAt }); this.assetVersions = [...this.assetVersions, version]; this.assetCurrentVersionId = version.id; this.incrementVersion(); this.emit(AssetVersionCreated, command, { versionId: version.id.toString(), predecessorVersionId: version.predecessorReference?.versionId.toString() ?? null, number: version.number.value }); this.assertState(); return version; }
  public addRelationship(command: AddAssetRelationshipCommand): void { const relationship = command.relationship; if (!relationship.source.id.equals(this.id) || !relationship.source.tenantId.equals(this.tenantId)) throw new InvariantViolation("Asset may own only its outgoing relationships"); if (this.assetRelationships.some((item) => item.type === relationship.type && item.target.id.equals(relationship.target.id))) throw new InvariantViolation("AssetRelationship already exists"); this.assetRelationships = [...this.assetRelationships, relationship]; this.incrementVersion(); this.emit(AssetRelationshipCreated, command, { sourceAssetId: relationship.source.id.toString(), targetAssetId: relationship.target.id.toString(), relationshipType: relationship.type }); }
  public archive(command: ArchiveAssetCommand): void { if (this.assetStatus !== "PUBLISHED") throw new InvariantViolation(`Asset cannot be archived from ${this.assetStatus}`); this.assertGovernedTenant(command); this.assetStatus = "ARCHIVED"; this.incrementVersion(); this.emit(AssetArchived, command); }
  public supersede(command: SupersedeAssetCommand): void { if (this.assetStatus !== "PUBLISHED") throw new InvariantViolation(`Asset cannot be superseded from ${this.assetStatus}`); this.assertGovernedTenant(command); if (!command.successorReference.tenantId.equals(this.tenantId) || command.successorReference.id.equals(this.id)) throw new InvariantViolation("Asset successor must be distinct and intra-Tenant"); this.assetSupersededBy = command.successorReference; this.assetStatus = "SUPERSEDED"; this.incrementVersion(); this.emit(AssetSuperseded, command, { successorAssetId: command.successorReference.id.toString() }); }
  public toSnapshot(): AssetSnapshot { return { schemaVersion: 1, assetId: this.id.toString(), tenantId: this.tenantId.toString(), missionReference: this.missionReference.toJSON(), metadata: this.metadata.toJSON(), classification: this.classification.toJSON(), authorityContext: this.authorityContext.toJSON(), status: this.status, versions: this.versions.map((item) => item.toSnapshot()), currentVersionId: this.currentVersionId.toString(), relationships: this.relationships.map((item) => item.toJSON()), supersededBy: this.supersededBy?.toJSON() ?? null, version: this.version.value }; }
  private assertState(): void { if (this.assetVersions.length === 0) throw new InvariantViolation("Asset requires at least one version"); if (this.assetVersions.filter((item) => item.id.equals(this.assetCurrentVersionId)).length !== 1) throw new InvariantViolation("Asset must have exactly one current version"); if (this.assetVersions.some((item) => !item.assetId.equals(this.id) || !item.tenantId.equals(this.tenantId))) throw new InvariantViolation("AssetVersion cannot cross Asset or Tenant boundaries"); if (this.assetStatus === "SUPERSEDED" && this.assetSupersededBy === null) throw new InvariantViolation("Superseded Asset requires a successor"); }
  private assertGovernedTenant(command: { authorityReference: { tenantId: TenantId }; decisionReference: { tenantId: TenantId } }): void { if (!command.authorityReference.tenantId.equals(this.tenantId) || !command.decisionReference.tenantId.equals(this.tenantId)) throw new InvariantViolation("Governed Asset command crossed a Tenant boundary"); }
  private emit(eventType: new (props: import("./AssetEvents.js").AssetEventProps) => import("./AssetEvents.js").AssetDomainEvent, command: AssetAuditInput & { correlationId: CorrelationId; causationId?: CausationId; evidence: readonly EvidenceReference[]; lineage: readonly LineageReference[] }, payload: JsonObject = {}): void { this.recordEvent(new eventType({ aggregateId: this.id.toString(), tenantId: this.tenantId, occurredAt: command.occurredAt, version: this.version, correlationId: command.correlationId.toString(), ...(command.causationId ? { causationId: command.causationId.toString() } : {}), evidenceIds: command.evidence.map((item) => item.evidenceId.toString()), lineage: command.lineage.map((item) => item.toJSON()), payload })); }
}
