import type { JsonObject } from "../../../shared/common/serialization.js";
import { ValidationError } from "../../../shared/errors/ValidationError.js";
import { ValueObject } from "../../../shared/valueobject/ValueObject.js";

export const ASSET_CATEGORIES = ["KNOWLEDGE", "EDITORIAL", "BRAND", "MARKETING", "PUBLICATION", "MEDIA", "LEARNING", "GOVERNANCE", "DATA", "MODEL", "TEMPLATE", "GUIDELINE"] as const;
export type AssetCategory = typeof ASSET_CATEGORIES[number];
export type Sensitivity = "PUBLIC" | "INTERNAL" | "CONFIDENTIAL" | "RESTRICTED";
export class AssetTag extends ValueObject<string> { public constructor(value: string) { const normalized = value.trim().toLowerCase(); if (!/^[a-z0-9][a-z0-9_-]{0,63}$/u.test(normalized)) throw new ValidationError("AssetTag must be a normalized semantic label"); super(normalized); Object.freeze(this); } public get value(): string { return this.rawValue; } }
export interface AssetClassificationProps { readonly primaryCategory: AssetCategory; readonly secondaryCategories?: readonly AssetCategory[]; readonly sensitivity: Sensitivity; readonly tags?: readonly AssetTag[]; }
export class AssetClassification extends ValueObject<JsonObject> {
  public readonly primaryCategory: AssetCategory; public readonly secondaryCategories: readonly AssetCategory[]; public readonly sensitivity: Sensitivity; public readonly tags: readonly AssetTag[];
  public constructor(props: AssetClassificationProps) { if (!ASSET_CATEGORIES.includes(props.primaryCategory)) throw new ValidationError("Asset primary category is not canonical"); const secondary = [...new Set(props.secondaryCategories ?? [])].filter((item) => item !== props.primaryCategory); for (const category of secondary) if (!ASSET_CATEGORIES.includes(category)) throw new ValidationError("Asset secondary category is not canonical"); const sensitivities: readonly Sensitivity[] = ["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED"]; if (!sensitivities.includes(props.sensitivity)) throw new ValidationError("Asset Sensitivity is not canonical"); const tags = [...new Map((props.tags ?? []).map((tag) => [tag.value, tag])).values()]; super({ primaryCategory: props.primaryCategory, secondaryCategories: secondary, sensitivity: props.sensitivity, tags: tags.map((tag) => tag.toJSON()) }); this.primaryCategory = props.primaryCategory; this.secondaryCategories = Object.freeze(secondary); this.sensitivity = props.sensitivity; this.tags = Object.freeze(tags); Object.freeze(this); }
  public static fromJSON(value: JsonObject): AssetClassification { return new AssetClassification({ primaryCategory: String(value.primaryCategory) as AssetCategory, secondaryCategories: Array.isArray(value.secondaryCategories) ? value.secondaryCategories.map(String) as AssetCategory[] : [], sensitivity: String(value.sensitivity) as Sensitivity, tags: Array.isArray(value.tags) ? value.tags.map((item) => new AssetTag(String(item))) : [] }); }
}
