import { describe, expect, it } from "vitest";
import { DeterministicAgentExecutor, PublisherProjectService, editorialContextSchema, publisherAgents, publisherProduct, reviewConsistency, type EditorialContext, type EditorialCore, type PlatformContentVariant, type PublisherPlatformCompositionPort, type PublisherProject, type PublisherProjectRepository } from "../src/index.js";
const context: EditorialContext = { contextId: "context-1", version: 1, title: "Publisher launch", topic: "Governed publishing", objective: "Explain the service", audience: "Communication leaders", centralMessage: "One approved message can serve several channels", tone: "Precise", contentLanguage: "en-US", callToAction: "Review the Editorial Package", requiredFacts: ["Human approval remains mandatory"], requiredTerms: ["governance"], prohibitedClaims: ["autonomous publishing"], constraints: ["Do not claim external publication"], channels: ["blog", "linkedin", "instagram"], materials: [{ id: "source-1", kind: "TEXT", title: "Source", content: "Human approval remains mandatory." }] };
describe("Publisher Product", () => {
  it("is a declarative product with four agents and three channels", () => { expect(publisherProduct.id).toBe("bba.publisher.multiplatform-publication"); expect(publisherAgents).toHaveLength(4); expect(publisherProduct.channels).toHaveLength(3); expect(publisherProduct).not.toHaveProperty("aggregateId"); });
  it("validates English canonical context and rejects unsafe URLs", () => { expect(editorialContextSchema.parse(context).contentLanguage).toBe("en-US"); expect(() => editorialContextSchema.parse({ ...context, materials: [{ id: "x", kind: "URL", title: "bad", url: "javascript:alert(1)" }] })).toThrow(); });
  it("executes the deterministic composition", async () => { const executor = new DeterministicAgentExecutor(); const core = (await executor.execute<EditorialCore>(publisherAgents[0]!, context, { projectId: "project-1" })).output; const variants: PlatformContentVariant[] = []; for (const channelId of publisherProduct.channels) variants.push((await executor.execute<PlatformContentVariant>(publisherAgents[2]!, core, { projectId: "project-1", channelId })).output); expect(core.contentLanguage).toBe("en-US"); expect(variants).toHaveLength(3); expect(reviewConsistency({ core, variants }, "2026-07-29T12:00:00.000Z").passed).toBe(true); });
  it("blocks unsupported claims", () => { const core: EditorialCore = { version: 1, objective: "Objective", audience: "Audience", centralMessage: "Message", claims: [{ id: "claim-1", statement: "Fact", evidenceIds: ["evidence-1"], required: true }], evidence: [{ id: "evidence-1", materialId: "source", locator: "line" }], tone: "Precise", requiredTerms: [], prohibitedClaims: ["invented result"], contentLanguage: "en-US", limitations: [] }; const variant: PlatformContentVariant = { variantId: "variant", version: 1, channelId: "blog", format: "article", blocks: [{ id: "block", kind: "CONTEXT", text: "Invented result", sourceClaimIds: [] }], tags: [], metadata: {}, editorialCoreVersion: 1 }; expect(reviewConsistency({ core, variants: [variant] }, "2026-07-29T12:00:00.000Z").passed).toBe(false); });
});
describe("Publisher Project", () => {
  it("requires two human checkpoints and preserves English event contracts", async () => { const values = new Map<string, PublisherProject>(); const repository: PublisherProjectRepository = { get: async (tenantId, projectId) => values.get(`${tenantId}:${projectId}`), list: async (tenantId, subject) => [...values.values()].filter((project) => project.tenantId === tenantId && project.subject === subject), save: async (project) => { values.set(`${project.tenantId}:${project.projectId}`, project); } }; const platform: PublisherPlatformCompositionPort = { createProjectFoundation: async ({ projectId }) => ({ missionId: `mission-${projectId}`, assetIds: [], transactionIds: ["tx-create"] }), recordEditorialPackage: async ({ current }) => ({ ...current, assetIds: ["asset-package"], transactionIds: [...current.transactionIds, "tx-package"] }), recordHumanDecision: async ({ current, decision }) => ({ ...current, reviewId: "review-package", transactionIds: [...current.transactionIds, decision.decisionId] }) }; const service = new PublisherProjectService(repository, platform); const commandContext = { tenantId: "tenant-1", subject: "subject-1", actorReference: "steward-1", correlationId: "corr-1", now: "2026-07-29T12:00:00.000Z" }; let project = await service.create({ projectId: "project-1", executionMode: "DETERMINISTIC", context }, commandContext); expect(project.visibleStage).toBe("CONTEXT_RECEIVED"); project = await service.execute(project.projectId, commandContext, new DeterministicAgentExecutor()); project = await service.decide(project.projectId, { decisionId: "core-approved", target: "EDITORIAL_CORE", targetVersion: 1, outcome: "APPROVED", rationale: "Correct", actorReference: "steward-1", occurredAt: commandContext.now }, commandContext); project = await service.execute(project.projectId, commandContext, new DeterministicAgentExecutor()); project = await service.decide(project.projectId, { decisionId: "package-approved", target: "EDITORIAL_PACKAGE", targetVersion: 1, outcome: "APPROVED", rationale: "Ready", actorReference: "steward-1", occurredAt: commandContext.now }, commandContext); expect(project.status).toBe("READY_FOR_DELIVERY"); expect(project.visibleStage).toBe("READY_FOR_DELIVERY"); expect(project.packages[0]?.applicationLocale).toBe("en-US"); expect(project.events.every((event) => /^[\x20-\x7E]+$/u.test(event.message ?? ""))).toBe(true); });
  it("isolates Projects by tenant and subject", async () => { const saved: PublisherProject[] = []; const repository: PublisherProjectRepository = { get: async (tenantId, projectId) => saved.find((project) => project.tenantId === tenantId && project.projectId === projectId), list: async () => [], save: async (project) => { saved.push(project); } }; const platform: PublisherPlatformCompositionPort = { createProjectFoundation: async () => ({ assetIds: [], transactionIds: [] }), recordEditorialPackage: async ({ current }) => current, recordHumanDecision: async ({ current }) => current }; const service = new PublisherProjectService(repository, platform); const base = { tenantId: "tenant-1", subject: "subject-1", actorReference: "steward-1", correlationId: "corr-1", now: "2026-07-29T12:00:00.000Z" }; await service.create({ projectId: "private", executionMode: "DETERMINISTIC", context }, base); await expect(service.execute("private", { ...base, tenantId: "tenant-2" }, new DeterministicAgentExecutor())).rejects.toThrow("PROJECT_NOT_FOUND"); });
});
