import { Link } from "react-router-dom";
import { getAgencyProductById } from "../../content/products/index.js";
import { getAgencyProjectById } from "../../content/projects/index.js";
import type { AgencyDeliveryPackageContent, DeliveryArtifact } from "../../content/deliveries/index.js";

function Section({ eyebrow, title, children, className }: { readonly eyebrow: string; readonly title: string; readonly children: React.ReactNode; readonly className?: string }) {
  return <section className={`delivery-package-section ${className ?? ""}`.trim()}><p className="section-kicker">{eyebrow}</p><h2>{title}</h2>{children}</section>;
}

function artifactNames(ids: string[], artifacts: DeliveryArtifact[]) {
  const names = new Map(artifacts.map((artifact) => [artifact.id, artifact.name]));
  return ids.map((id) => names.get(id) ?? id).join(" · ");
}

function sectionBody(deliveryPackage: AgencyDeliveryPackageContent, title: string) {
  const section = deliveryPackage.sections[title];
  if (!section) throw new Error(`Missing generated Delivery Package section: ${title}`);
  return section.body;
}

export function DeliveryPackagePage({ deliveryPackage }: { readonly deliveryPackage: AgencyDeliveryPackageContent }) {
  const product = getAgencyProductById(deliveryPackage.productId);
  const project = getAgencyProjectById(deliveryPackage.projectId);
  const previous = deliveryPackage.navigation.previousDelivery;
  const next = deliveryPackage.navigation.nextDelivery;
  const prototypeBacked = deliveryPackage.status === "PROTOTYPE_BACKED";

  return (
    <main className="page-shell delivery-package-page">
      <Link className="back-link" to="/deliveries">← Return to Delivery Packages</Link>
      <section className="delivery-package-hero" aria-labelledby="delivery-package-heading">
        <div><p className="section-kicker">{deliveryPackage.eyebrow}</p><span className={`delivery-status ${deliveryPackage.status.toLowerCase()}`}>{deliveryPackage.availability.label}</span><h1 id="delivery-package-heading">{deliveryPackage.name}</h1><p className="delivery-package-headline">{deliveryPackage.headline}</p><p className="delivery-package-summary">{deliveryPackage.summary}</p><div className="delivery-package-meta"><span>{deliveryPackage.productName}</span><span>{deliveryPackage.projectName}</span><span>{deliveryPackage.category}</span></div><p className="delivery-package-disclosure">{prototypeBacked ? "This Package reflects the outcome demonstrated by the functional BBA Publisher prototype." : "This is an illustrative representation of a planned BBA Agency Delivery Package."}</p>{deliveryPackage.prototype.available ? <a className="delivery-package-external-link" href={deliveryPackage.prototype.url} target="_blank" rel="noopener noreferrer" aria-label="Explore the functional Publisher prototype at dev.bba.country in a new tab">Explore the functional Publisher prototype <span aria-hidden="true">↗</span></a> : null}</div>
        <aside className="delivery-package-outcome"><span>Customer outcome</span><strong>{deliveryPackage.name}</strong><p>{deliveryPackage.customerOutcome}</p><i>Informational only. No Package action is available on this static site.</i></aside>
      </section>
      <section className="delivery-package-overview" aria-label="Package overview"><article><span>Purpose</span><p>{deliveryPackage.purpose}</p></article><article><span>Artifacts</span><p>{deliveryPackage.artifacts.length} structured materials</p></article><article><span>Human review</span><p>{deliveryPackage.reviewProcess.length} explanatory checkpoints</p></article><article><span>Approval</span><p>{deliveryPackage.approval.required ? "Human approval required" : "No approval requirement"}</p></article></section>

      <Section eyebrow="Overview" title="What this Package explains"><p className="delivery-package-lead">{sectionBody(deliveryPackage, "Overview")}</p></Section>
      <Section eyebrow="Business objective" title="Why this Package exists"><div className="delivery-package-objective-grid"><article><span>Business objective</span><p>{sectionBody(deliveryPackage, "Business objective")}</p></article><article><span>Customer outcome</span><p>{deliveryPackage.customerOutcome}</p></article></div></Section>
      <Section eyebrow="Contents" title="The complete result represented by the Package"><p className="delivery-package-lead">{sectionBody(deliveryPackage, "Contents")}</p></Section>
      <Section eyebrow="Artifacts" title="Structured materials for customer review"><p className="delivery-package-lead">{sectionBody(deliveryPackage, "Artifacts")}</p><div className="delivery-artifact-grid">{deliveryPackage.artifacts.map((artifact) => <article key={artifact.id}><span>{artifact.requiresHumanApproval ? "Human approval applies" : "Reviewable material"}</span><h3>{artifact.name}</h3><p>{artifact.description}</p><small><strong>Purpose:</strong> {artifact.purpose}</small><small><strong>Illustrative format:</strong> {artifact.illustrativeFormats.join(" · ")}</small><i>{artifact.includedInPackage ? `Included in ${deliveryPackage.name}` : "Not included in the final Package"}</i></article>)}</div></Section>
      <Section eyebrow="Review process" title="Ordered explanatory review checkpoints"><p className="delivery-package-lead">{sectionBody(deliveryPackage, "Review process")}</p><ol className="delivery-review-list">{deliveryPackage.reviewProcess.map((checkpoint) => <li key={checkpoint.id}><div className="delivery-review-order">{String(checkpoint.order).padStart(2, "0")}</div><div><span>Human checkpoint</span><h3>{checkpoint.label}</h3><p>{checkpoint.purpose}</p></div><dl><div><dt>Reviewer role</dt><dd>{checkpoint.reviewerRole}</dd></div><div><dt>Artifacts reviewed</dt><dd>{artifactNames(checkpoint.artifactIds, deliveryPackage.artifacts)}</dd></div><div><dt>Possible future responses</dt><dd>{checkpoint.possibleOutcomes.map((outcome) => outcome.toLowerCase().replaceAll("_", " ")).join(" · ")}</dd></div><div><dt>Static website</dt><dd>Explanatory only; no review action occurs here.</dd></div></dl></li>)}</ol></Section>
      <Section eyebrow="Approval" title="Human approval remains required"><p className="delivery-package-lead">{sectionBody(deliveryPackage, "Approval")}</p><article className="delivery-approval-summary"><span>Responsible role</span><h3>{deliveryPackage.approval.responsibleRole}</h3><p>{deliveryPackage.approval.description}</p><dl><div><dt>What is considered</dt><dd>Final artifacts, review findings, limitations, and version history.</dd></div><div><dt>Possible future responses</dt><dd>{deliveryPackage.approval.possibleResponses.map((response) => response.toLowerCase().replaceAll("_", " ")).join(" · ")}</dd></div><div><dt>Static website</dt><dd>No approval occurs on this static site.</dd></div></dl></article></Section>
      <Section eyebrow="Revision policy" title="Revisions create new traceable versions"><p className="delivery-package-lead">{sectionBody(deliveryPackage, "Revision policy")}</p><article className="delivery-revision-policy"><p>{deliveryPackage.revisionPolicy.description}</p><dl><div><dt>Preserved</dt><dd>{deliveryPackage.revisionPolicy.preserves.join(" · ")}</dd></div><div><dt>May require renewed review</dt><dd>{deliveryPackage.revisionPolicy.mayInvalidate.join(" · ")}</dd></div><div><dt>Customer guidance</dt><dd>Clarifications about context, scope, artifacts, findings, or limitations may guide a future revision.</dd></div></dl></article></Section>
      <Section eyebrow="Illustrative version history" title="Versions preserve their review context"><p className="delivery-package-lead">{sectionBody(deliveryPackage, "Version history")}</p><div className="delivery-version-list">{deliveryPackage.versionHistory.map((version) => <article key={version.version}><span>Illustrative version history</span><h3>Version {version.version}</h3><p>{version.description}</p><dl><div><dt>Changed artifacts</dt><dd>{artifactNames(version.changedArtifactIds, deliveryPackage.artifacts)}</dd></div><div><dt>Review reference</dt><dd>{version.decisionReference?.replaceAll("-", " ") ?? "Human review reference"}</dd></div><div><dt>Status</dt><dd>Illustrative record</dd></div></dl></article>)}</div></Section>
      <Section eyebrow="Traceability" title="From Project context to the final Package"><p className="delivery-package-lead">{sectionBody(deliveryPackage, "Traceability")}</p><div className="delivery-traceability-flow" aria-label="Traceability model"><span>Project context</span><span aria-hidden="true">→</span><span>Package artifact</span><span aria-hidden="true">→</span><span>Artifact version</span><span aria-hidden="true">→</span><span>Review checkpoint</span><span aria-hidden="true">→</span><span>Human decision</span><span aria-hidden="true">→</span><span>Final Package</span></div><div className="delivery-traceability-list">{deliveryPackage.traceability.map((trace) => <article key={trace.id}><span>Illustrative trace record</span><h3>{trace.sourceReference.replaceAll("-", " ")}</h3><p>{trace.rationale}</p><dl><div><dt>Artifact and version</dt><dd>{artifactNames([trace.artifactId], deliveryPackage.artifacts)} · v{trace.artifactVersion}</dd></div><div><dt>Review checkpoint</dt><dd>{trace.reviewCheckpointId?.replaceAll("-", " ") ?? "Human review reference"}</dd></div><div><dt>Human decision</dt><dd>{trace.decisionReference?.replaceAll("-", " ") ?? "Human decision reference"}</dd></div></dl></article>)}</div></Section>
      <Section eyebrow="Quality gates" title="Visible expectations before a future delivery"><p className="delivery-package-lead">{sectionBody(deliveryPackage, "Quality gates")}</p><div className="delivery-quality-grid">{deliveryPackage.qualityGates.map((gate) => <article key={gate.id}><span>{gate.severityWhenFailed === "BLOCKING" ? "Blocking if unmet" : "Warning if unmet"}</span><h3>{gate.name}</h3><p>{gate.description}</p><small>{gate.severityWhenFailed === "BLOCKING" ? "The future workflow cannot consider delivery ready until this is resolved." : "The future workflow keeps this concern visible for human consideration."}</small></article>)}</div></Section>
      <Section eyebrow="Limitations" title="Limits remain part of the Package" className="delivery-package-limitations"><p className="delivery-package-lead">{sectionBody(deliveryPackage, "Limitations")}</p><ul>{deliveryPackage.limitations.map((limitation) => <li key={limitation}>{limitation}</li>)}</ul></Section>
      <Section eyebrow="Relationship with Projects" title="The representative Project context"><p className="delivery-package-lead">{sectionBody(deliveryPackage, "Relationship with Projects")}</p><Link className="delivery-relationship-link" to={project?.route ?? deliveryPackage.projectRoute}>View {project?.name ?? deliveryPackage.projectName} <span aria-hidden="true">→</span></Link></Section>
      <Section eyebrow="Relationship with Product" title="The related BBA Agency Product"><p className="delivery-package-lead">{sectionBody(deliveryPackage, "Relationship with Product")}</p><Link className="delivery-relationship-link" to={product?.route ?? deliveryPackage.productRoute}>View {product?.name ?? deliveryPackage.productName} <span aria-hidden="true">→</span></Link></Section>
      <Section eyebrow="Future operational workflow" title="What a future platform may support"><p className="delivery-package-lead">{sectionBody(deliveryPackage, "Future operational workflow")}</p></Section>
      <Section eyebrow="Frequently asked questions" title="Questions about this Package"><div className="delivery-faq-list">{deliveryPackage.faq.map((item) => <article key={item.question}><h3>{item.question}</h3><p>{item.answer}</p></article>)}</div></Section>
      <section className="delivery-package-navigation" aria-label="Package navigation"><article><p className="section-kicker">All Packages</p><h2>Continue the delivery journey</h2><Link to="/deliveries">Return to Delivery Packages</Link></article><nav>{previous ? <Link to={`/deliveries/${previous}`}>Previous Package</Link> : <span>Previous Package: none</span>}{next ? <Link to={`/deliveries/${next}`}>Next Package</Link> : <span>Next Package: none</span>}</nav></section>
    </main>
  );
}
