import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { describe, expect, it } from "vitest";
import { AgencyHome } from "../src/static-publisher/pages/AgencyHome.js";
import { sanitizeProviderConfiguration } from "../src/static-publisher/pages/StaticAiSettings.js";
import { validateDraftStep } from "../src/static-publisher/pages/EditorialContextWizard.js";
import { projectScenarios } from "../src/static-publisher/fixtures/projects.js";
import { publisherProjectReducer, visibleStageLabel } from "../src/static-publisher/state-machine.js";
import type { PublisherDraft } from "../src/static-publisher/models.js";

const draft: PublisherDraft = { title: "Projeto", communicationNeed: "Comunicar o lançamento", objective: "Explicar", expectedOutcome: "Pacote pronto", language: "pt-BR", audience: "Builders", centralMessage: "Mensagem", tone: "Preciso", callToAction: "", textualMaterials: "Fonte", urls: "", fileName: "", fileType: "", fileSize: "", fileDescription: "", requiredFacts: "Fato", requiredTerms: "", prohibitedClaims: "", limitations: "", notes: "", channels: ["BLOG", "LINKEDIN", "INSTAGRAM"], executionMode: "DETERMINISTIC" };

describe("static Publisher Experience", () => {
  it("presents an Agency service home with only Publisher available", () => { render(<MemoryRouter><AgencyHome /></MemoryRouter>); expect(screen.getByRole("heading", { name: "Como podemos ajudar?" })).toBeTruthy(); expect(screen.getAllByText("Planejado")).toHaveLength(4); expect(screen.getByText("Disponível")).toBeTruthy(); expect(screen.queryByRole("heading", { name: "Mission" })).toBeNull(); });
  it("validates the wizard progressively", () => { expect(validateDraftStep(1, { ...draft, title: "" })).toContain("Preencha título, necessidade, objetivo e resultado esperado."); expect(validateDraftStep(2, draft)).toEqual([]); expect(validateDraftStep(4, { ...draft, requiredFacts: "" })).toContain("Informe ao menos um fato obrigatório."); });
  it("contains every required fixture scenario and valid three-channel packages", () => { expect(Object.keys(projectScenarios)).toEqual(expect.arrayContaining(["new-project", "running-context-analysis", "awaiting-core-approval", "core-revision-requested", "running-content-generation", "awaiting-package-approval", "package-blocked", "package-revision-requested", "ready-for-delivery", "recoverable-failure"])); expect(projectScenarios["ready-for-delivery"].variants.map((item) => item.channel)).toEqual(["BLOG", "LINKEDIN", "INSTAGRAM"]); });
  it("runs the golden path through explicit events", () => { let project = projectScenarios["new-project"]; project = publisherProjectReducer(project, { type: "EXECUTION_STARTED" }); project = publisherProjectReducer(project, { type: "CONTEXT_ANALYSIS_COMPLETED" }); project = publisherProjectReducer(project, { type: "EDITORIAL_CORE_APPROVED", rationale: "Mensagem correta" }); project = publisherProjectReducer(project, { type: "EDITORIAL_PLAN_COMPLETED" }); for (const channel of ["BLOG", "LINKEDIN", "INSTAGRAM"] as const) project = publisherProjectReducer(project, { type: "CHANNEL_CONTENT_COMPLETED", channel }); project = publisherProjectReducer(project, { type: "CONSISTENCY_REVIEW_COMPLETED" }); project = publisherProjectReducer(project, { type: "PACKAGE_APPROVED", rationale: "Pronto" }); expect(project.status).toBe("READY_FOR_DELIVERY"); expect(project.variants).toHaveLength(3); expect(project.decisions).toHaveLength(2); });
  it("regenerates all variants after revision and blocks packages with findings", () => { const revised = publisherProjectReducer(projectScenarios["awaiting-package-approval"], { type: "PACKAGE_REVISION_REQUESTED", guidance: "Explicitar governança" }); expect(revised.variants.every((variant) => variant.version === 2)).toBe(true); expect(projectScenarios["package-blocked"].availableActions).not.toContain("APPROVE_PACKAGE"); expect(projectScenarios["package-blocked"].review?.findings.some((finding) => finding.severity === "BLOCKING")).toBe(true); });
  it("represents recoverable failure and retry without losing completed content", () => { const failed = projectScenarios["recoverable-failure"]; const retried = publisherProjectReducer(failed, { type: "STEP_RETRIED", stage: failed.visibleStage }); expect(retried.status).toBe("RUNNING"); expect(retried.failure).toBeUndefined(); expect(retried.variants).toHaveLength(1); });
  it("sanitizes visual BYOK configuration and never returns the key", () => { const result = sanitizeProviderConfiguration({ provider: "OpenAI", apiKey: "secret-key-value", consent: true }); expect(result).toEqual({ provider: "OpenAI", configured: true, consent: true }); expect(JSON.stringify(result)).not.toContain("secret-key-value"); });
  it("maps technical stages to customer language", () => { expect(visibleStageLabel("UNDERSTANDING_CONTEXT")).toBe("Compreendendo contexto"); expect(visibleStageLabel("PACKAGE_REVIEW")).toBe("Pacote disponível para revisão"); expect(visibleStageLabel("DELIVERY")).toBe("Pronto para entrega"); });
});
