import { workflowActivateWorkflow, workflowAdvanceStage, workflowArchiveWorkflow, workflowCancelWorkflow, workflowCompleteWorkflow, workflowCreateWorkflow, workflowFailWorkflowExecution, workflowGetWorkflow, workflowGetWorkflowExecution, workflowPauseWorkflow, workflowRecordTaskFailure, workflowRecordTaskState, workflowResumeWorkflow, workflowStartWorkflow } from "@bba/api-client";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useCallback } from "react";
import type { CommandIntent } from "../commands/command-types.js";
import { commandHeaders, executeCommand, requireReady, type GeneratedCommandResponse } from "../commands/execute-command.js";
import { useCommandIntent } from "../commands/use-command-intent.js";
import { BbaSdkError, normalizeSdkError } from "../errors/BbaSdkError.js";
import type { EvidenceInput, LineageInput } from "../missions/mission-commands.js";
import { useBbaSdkRuntime, type ReadySdkRuntime } from "../provider/BbaSdkProvider.js";
import { workflowKeys } from "../query-keys/product-keys.js";

export interface WorkflowAuditInput { readonly occurredAt: string; readonly evidence: readonly EvidenceInput[]; readonly lineage: readonly LineageInput[]; }
export interface CreateWorkflowInput extends WorkflowAuditInput { readonly workflowId: string; readonly missionId: string; readonly name: string; readonly summary: string; readonly stage: { readonly id: string; readonly name: string }; readonly task: { readonly id: string; readonly name: string; readonly kind: "COORDINATION" | "GOVERNANCE_CHECKPOINT" | "WORK_ASSIGNMENT" | "ASSET_CHECK" | "KNOWLEDGE_CHECK"; readonly dueDate?: string }; }
export interface WorkflowLifecycleInput extends WorkflowAuditInput { readonly workflowId: string; }
export interface StartWorkflowInput extends WorkflowAuditInput { readonly workflowId: string; readonly executionId: string; readonly missionId: string; readonly initialStageId: string; }
export interface WorkflowExecutionInput extends WorkflowAuditInput { readonly executionId: string; readonly nextStageId?: string; readonly disposition?: string; readonly taskId?: string; readonly observedState?: string; readonly failure?: string; readonly workAssignmentId?: string; }
export interface WorkflowView { readonly id: string; readonly tenantId: string; readonly status: string; readonly version: number; }
export interface WorkflowExecutionView { readonly id: string; readonly tenantId: string; readonly status: string; readonly version: number; }
type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };
const audit = (value: WorkflowAuditInput): { [key: string]: JsonValue } => ({ occurredAt: value.occurredAt, evidence: value.evidence.map((item) => ({ ...item })), lineage: value.lineage.map((item) => ({ ...item })) });
function useWorkflowCommand<T>(operationId: string, ids: (value: T) => { primaryId: string; relatedId?: string; workflowId?: string }, invoke: (runtime: ReadySdkRuntime, intent: CommandIntent<T>) => Promise<GeneratedCommandResponse>) { const runtime = useBbaSdkRuntime(); const queryClient = useQueryClient(); const execute = useCallback((intent: CommandIntent<T>) => { const ready = requireReady(runtime.ready); return executeCommand(ready, queryClient, operationId, intent, () => invoke(ready, intent), ids(intent.payload)); }, [ids, invoke, operationId, queryClient, runtime.ready]); return useCommandIntent(execute); }
const lifecycle = (operationId: string, call: typeof workflowActivateWorkflow) => function useLifecycle() { return useWorkflowCommand<WorkflowLifecycleInput>(operationId, (v) => ({ primaryId: v.workflowId }), (r, i) => call({ client: r.client, path: { workflowId: i.payload.workflowId }, headers: commandHeaders(r, i), body: { data: { workflowId: i.payload.workflowId, ...audit(i.payload) }, meta: { reason: i.reason } } })); };
const execution = (operationId: string, call: typeof workflowPauseWorkflow) => function useExecution() { return useWorkflowCommand<WorkflowExecutionInput>(operationId, (v) => ({ primaryId: v.executionId, relatedId: v.executionId }), (r, i) => call({ client: r.client, path: { executionId: i.payload.executionId }, headers: commandHeaders(r, i), body: { data: { ...i.payload, evidence: i.payload.evidence.map((v) => ({ ...v })), lineage: i.payload.lineage.map((v) => ({ ...v })) }, meta: { reason: i.reason } } })); };
export function useWorkflowCreateWorkflowCommand() { return useWorkflowCommand<CreateWorkflowInput>("workflowCreateWorkflow", (v) => ({ primaryId: v.workflowId }), (r, i) => workflowCreateWorkflow({ client: r.client, headers: commandHeaders(r, i), body: { data: { workflowId: i.payload.workflowId, missionReference: { id: i.payload.missionId, tenantId: r.tenantId }, metadata: { name: i.payload.name, summary: i.payload.summary, createdAt: i.payload.occurredAt, updatedAt: i.payload.occurredAt }, taskDefinitions: [{ taskId: i.payload.task.id, name: i.payload.task.name, kind: i.payload.task.kind, references: [{ kind: "mission", reference: { id: i.payload.missionId, tenantId: r.tenantId } }], dueDate: i.payload.task.dueDate ?? null, metadata: {} }], stageDefinitions: [{ stageId: i.payload.stage.id, name: i.payload.stage.name, dependencies: [], taskIds: [i.payload.task.id], metadata: {} }], ...audit(i.payload) }, meta: { reason: i.reason } } })); }
export const useWorkflowActivateWorkflowCommand = lifecycle("workflowActivateWorkflow", workflowActivateWorkflow); export const useWorkflowArchiveWorkflowCommand = lifecycle("workflowArchiveWorkflow", workflowArchiveWorkflow);
export function useWorkflowStartWorkflowCommand() { return useWorkflowCommand<StartWorkflowInput>("workflowStartWorkflow", (v) => ({ primaryId: v.workflowId, relatedId: v.executionId, workflowId: v.workflowId }), (r, i) => workflowStartWorkflow({ client: r.client, path: { workflowId: i.payload.workflowId }, headers: commandHeaders(r, i), body: { data: { workflowId: i.payload.workflowId, executionId: i.payload.executionId, workflowReference: { id: i.payload.workflowId, tenantId: r.tenantId }, missionReference: { id: i.payload.missionId, tenantId: r.tenantId }, initialStageId: i.payload.initialStageId, ...audit(i.payload) }, meta: { reason: i.reason } } })); }
export const useWorkflowPauseWorkflowCommand = execution("workflowPauseWorkflow", workflowPauseWorkflow); export const useWorkflowResumeWorkflowCommand = execution("workflowResumeWorkflow", workflowResumeWorkflow); export const useWorkflowCompleteWorkflowCommand = execution("workflowCompleteWorkflow", workflowCompleteWorkflow); export const useWorkflowCancelWorkflowCommand = execution("workflowCancelWorkflow", workflowCancelWorkflow); export const useWorkflowFailWorkflowExecutionCommand = execution("workflowFailWorkflowExecution", workflowFailWorkflowExecution);
export function useWorkflowAdvanceStageCommand() { return useWorkflowCommand<WorkflowExecutionInput>("workflowAdvanceStage", (v) => ({ primaryId: v.executionId, relatedId: v.executionId }), (r, i) => workflowAdvanceStage({ client: r.client, path: { executionId: i.payload.executionId }, headers: commandHeaders(r, i), body: { data: { ...i.payload, evidence: i.payload.evidence.map((v) => ({ ...v })), lineage: i.payload.lineage.map((v) => ({ ...v })) }, meta: { reason: i.reason } } })); }
export function useWorkflowRecordTaskStateCommand() { return useWorkflowCommand<WorkflowExecutionInput>("workflowRecordTaskState", (v) => ({ primaryId: v.executionId, relatedId: v.executionId }), (r, i) => workflowRecordTaskState({ client: r.client, path: { executionId: i.payload.executionId }, headers: commandHeaders(r, i), body: { data: { ...i.payload, ...(i.payload.workAssignmentId === undefined ? {} : { workAssignmentReference: { id: i.payload.workAssignmentId, tenantId: r.tenantId } }), evidence: i.payload.evidence.map((v) => ({ ...v })), lineage: i.payload.lineage.map((v) => ({ ...v })) }, meta: { reason: i.reason } } })); }
export function useWorkflowRecordTaskFailureCommand() { return useWorkflowCommand<WorkflowExecutionInput>("workflowRecordTaskFailure", (v) => ({ primaryId: v.executionId, relatedId: v.executionId }), (r, i) => workflowRecordTaskFailure({ client: r.client, path: { executionId: i.payload.executionId }, headers: commandHeaders(r, i), body: { data: { ...i.payload, ...(i.payload.workAssignmentId === undefined ? {} : { workAssignmentReference: { id: i.payload.workAssignmentId, tenantId: r.tenantId } }), evidence: i.payload.evidence.map((v) => ({ ...v })), lineage: i.payload.lineage.map((v) => ({ ...v })) }, meta: { reason: i.reason } } })); }
const publicError = (value: unknown) => value instanceof BbaSdkError ? value : value === null ? undefined : normalizeSdkError(undefined, value);
export function useWorkflowGetWorkflowQuery(id: string) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; const query = useQuery({ queryKey: workflowKeys.detail(tenant, id), enabled: runtime.ready !== null && id.trim().length > 0, queryFn: async (): Promise<WorkflowView> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await workflowGetWorkflow({ client: runtime.ready.client, path: { workflowId: id }, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); const v = response.data.data; return { id: v.workflowId, tenantId: v.tenantId, status: v.status, version: v.version }; } }); return { data: query.data, error: publicError(query.error), isPending: query.isPending }; }
export function useWorkflowGetWorkflowExecutionQuery(id: string, workflowId: string | null = null) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; const query = useQuery({ queryKey: workflowKeys.execution(tenant, workflowId, id), enabled: runtime.ready !== null && id.trim().length > 0, queryFn: async (): Promise<WorkflowExecutionView> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await workflowGetWorkflowExecution({ client: runtime.ready.client, path: { executionId: id }, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); const v = response.data.data; return { id: v.executionId, tenantId: v.tenantId, status: v.status, version: v.version }; } }); return { data: query.data, error: publicError(query.error), isPending: query.isPending }; }
