import { NavLink } from "react-router-dom";
import { FileText, Flag, Package, Target } from "@phosphor-icons/react";
import { Lineage, StatusBadge, type LineageItem } from "@bba/ui";
import { formatDate } from "../../i18n/index.js";
import { demoProjects } from "../fixtures/projects.js";
import { serviceProducts } from "../fixtures/products.js";
import { visibleStageLabel } from "../state-machine.js";

const activeProjects = demoProjects.filter((project) => project.status !== "READY_FOR_DELIVERY").slice(0, 3);
const awaitingDecision = demoProjects.filter((project) => project.pendingHumanAction).slice(0, 3);
const recentDeliveries = demoProjects.filter((project) => project.status === "READY_FOR_DELIVERY").slice(0, 3);

export function AgencyHome() {
  const lineage: readonly LineageItem[] = [
    { type: "Mission", id: "mission-publisher-context", label: "Institutional communication objective", state: "running", stateLabel: "In progress", icon: <Target size={18} /> },
    { type: "Institutional Asset", id: "asset-editorial-core", label: "Editorial Core", state: "awaiting", stateLabel: "Awaiting decision", icon: <FileText size={18} /> },
    { type: "Channel Variant", id: "variant-channel-set", label: "Blog · LinkedIn · Instagram", state: "neutral", stateLabel: "Locked", locked: true, icon: <Flag size={18} /> },
    { type: "Distribution Package", id: "package-editorial-set", label: "Editorial Distribution Package", state: "neutral", stateLabel: "Not constituted", locked: true, icon: <Package size={18} /> },
  ];
  return <>
    <section className="agency-hero"><div><p className="agency-kicker"><span>AI Workforce</span><span>Human Governance</span></p><h1>Institutional work with explicit decisions and traceable lineage.</h1><p className="agency-lede">Start from a governed Mission, review the canonical Institutional Asset, and prepare Channel Variants without implying external publication.</p><div className="agency-actions"><NavLink className="agency-arrow" data-action="create-project" to="/services/publisher/new">Start controlled work →</NavLink><NavLink to="/missions/msn-024">Open Mission Workspace</NavLink><NavLink to="/projects">View active work</NavLink></div></div><div className="agency-hero-lineage"><Lineage title="Governance lineage" eyebrow="Publisher reference" items={lineage} /><p><StatusBadge state="attention">Connector not configured</StatusBadge> External publication is unavailable.</p></div></section>
    <section className="agency-dark"><div><p className="agency-kicker">A different operating model</p><h2>You choose the outcome.<br />The Agency organizes the work.</h2></div><ol>{["Choose a service", "Provide your context", "Follow the team", "Review important decisions", "Receive the final package"].map((item) => <li key={item}>{item}</li>)}</ol></section>
    <section className="agency-section"><header><p className="agency-kicker">Agency services</p><h2>What do you need to produce?</h2><p>Publisher is the executable reference service. Other disciplines are planned and do not simulate unavailable functionality.</p></header><div className="agency-service-grid">{serviceProducts.map((service, index) => <article className={service.status === "AVAILABLE" ? "available" : "planned"} key={service.id}><div><span>0{index + 1} / {service.category}</span><em>{service.status === "AVAILABLE" ? "Available" : "Planned"}</em></div><h3>{service.name}</h3><p>{service.outcome}</p><small>{service.deliverables}</small>{service.status === "AVAILABLE" ? <NavLink to="/services/publisher">Explore Publisher →</NavLink> : <span className="agency-muted">Future product — no simulation available</span>}</article>)}</div></section>
    <section className="agency-engagements" aria-labelledby="engagements-title"><header><div><p className="agency-kicker">In progress</p><h2 id="engagements-title">Your Agency engagements</h2></div><NavLink to="/projects">View all Projects →</NavLink></header><div>{activeProjects.map((project) => <NavLink className="agency-engagement" key={project.projectId} to={`/projects/${project.projectId}/context`}><span>{project.product.name}</span><h3>{project.title}</h3><p>{visibleStageLabel(project.visibleStage)}</p><small>Updated {formatDate(project.updatedAt)}</small></NavLink>)}</div></section>
    <section className="agency-decisions" aria-labelledby="decisions-title"><header><p className="agency-kicker">Human checkpoints</p><h2 id="decisions-title">Awaiting your decision</h2></header><div>{awaitingDecision.map((project) => <article key={project.projectId}><span>{project.pendingHumanAction}</span><h3>{project.title}</h3><p>The Agency will not move this outcome forward without your direction.</p><NavLink to={`/projects/${project.projectId}/${project.visibleStage === "PACKAGE_REVIEW" ? "review" : "context"}`}>Review decision →</NavLink></article>)}</div></section>
    <section className="agency-recent-deliveries" aria-labelledby="recent-deliveries-title"><header><div><p className="agency-kicker">Recent outcomes</p><h2 id="recent-deliveries-title">Recent deliveries</h2></div><NavLink to="/deliveries">View Deliveries →</NavLink></header><div>{recentDeliveries.map((project) => <NavLink key={project.projectId} to={`/projects/${project.projectId}/delivery`}><span>Editorial Package</span><strong>{project.title}</strong><small>Blog · LinkedIn · Instagram</small></NavLink>)}</div></section>
    <section className="agency-human"><div aria-hidden="true"><span>AI</span><i>+</i><span>H</span></div><div><p className="agency-kicker">Human control</p><h2>Nothing important moves forward without you.</h2><p>You approve the message, review content, understand the impact of changes, and decide when the outcome is ready.</p></div></section>
    <section className="agency-final-cta"><p className="agency-kicker">Ready to begin?</p><h2>Bring the context.<br />Leave with an outcome.</h2><NavLink className="agency-primary" to="/services/publisher/new">Start a Project</NavLink></section>
  </>;
}
