import { FileText, Flag, Package, Target } from "@phosphor-icons/react";
import { Lineage, StatusBadge, type LineageItem } from "@bba/ui";
import { NavLink } from "react-router-dom";

export function PublisherOverview() {
  const process = ["Understand Mission context", "Prepare the Institutional Asset", "Request Steward decision", "Derive Channel Variants", "Validate consistency", "Review each variant", "Constitute the Distribution Package"];
  const lineage: readonly LineageItem[] = [
    { type: "Mission", id: "mission-publisher-context", label: "Institutional communication objective", state: "running", stateLabel: "In progress", icon: <Target size={18} /> },
    { type: "Institutional Asset", id: "asset-editorial-core", label: "Editorial Core", state: "awaiting", stateLabel: "Awaiting decision", icon: <FileText size={18} /> },
    { type: "Channel Variant", id: "variant-channel-set", label: "Blog · LinkedIn · Instagram", state: "neutral", stateLabel: "Locked", locked: true, icon: <Flag size={18} /> },
    { type: "Distribution Package", id: "package-editorial-set", label: "Editorial Distribution Package", state: "neutral", stateLabel: "Not constituted", locked: true, icon: <Package size={18} /> },
  ];

  return <div className="agency-page publisher-overview"><NavLink className="agency-back" to="/services">← All services</NavLink><section className="publisher-hero"><div><p className="agency-kicker">Publisher reference / Available</p><h1>BBA Publisher</h1><p>Prepare institutional content through explicit Human Governance and traceable derivation.</p><NavLink className="agency-primary" data-action="create-project" to="/services/publisher/new">Create controlled work</NavLink></div><div className="publisher-boundary-card"><span>Distribution boundary</span><strong>Prepared,<br />not published</strong><small>Institutional Asset · Channel Variants · Distribution Package</small><StatusBadge state="attention">Connector not configured</StatusBadge></div></section><Lineage title="Canonical lineage" items={lineage} /><section className="publisher-facts"><article><span>You provide</span><p>Mission objective, audience, institutional sources, required facts, restrictions, tone, and intended channels.</p></article><article><span>You receive</span><p>An Institutional Asset, controlled Channel Variants, review findings, and a prepared Distribution Package.</p></article><article><span>You govern</span><p>Steward decisions remain explicit for the canonical asset and each derived variant.</p></article><article><span>Boundaries</span><p>This local reference does not retrieve URLs, process file bytes, configure Connectors, or publish externally.</p></article></section><section className="agency-section"><p className="agency-kicker">How the work happens</p><h2>AI Workforce progress remains separate from Steward decisions.</h2><div className="publisher-pipeline">{process.map((step, index) => <div key={step}><span>0{index + 1}</span><strong>{step}</strong><small>{index === 2 || index === 5 ? "Steward decision" : "AI Workforce"}</small></div>)}</div></section></div>;
}
