import { contentVariantSchema, editorialCoreSchema, publicationPlanSchema, reviewConsistency, type AgentDefinition, type AgentExecutionResult, type AgentExecutorPort, type EditorialCore, type LlmProvider, type PlatformContentVariant, type PublisherChannelId } from "@bba/publisher-prototype";
import type { EphemeralProviderCredential } from "./memory.js";
function extractJson(text: string) { const fenced = /```(?:json)?\s*([\s\S]*?)```/u.exec(text)?.[1]; return JSON.parse((fenced ?? text).trim()) as unknown; }
function schemaFor(agentId: string) { if (agentId.includes("context-analyst")) return editorialCoreSchema; if (agentId.includes("editorial-strategist")) return publicationPlanSchema; if (agentId.includes("platform-adapter")) return contentVariantSchema; return undefined; }
function prompt(definition: AgentDefinition, input: unknown, channelId?: PublisherChannelId) { return `You are the ${definition.role}. Return only valid JSON. Preserve facts, evidence references, prohibited claims, and human authority. ${channelId === undefined ? "" : `Adapt for ${channelId}.`} Input:\n${JSON.stringify(input)}`; }
function providerError(status: number) { return status === 401 || status === 403 ? "LLM_AUTHENTICATION_FAILED" : status === 429 ? "LLM_RATE_LIMITED" : "APPLICATION_FAILURE"; }
export class ByokAgentExecutor implements AgentExecutorPort {
  public constructor(private readonly credential: EphemeralProviderCredential, private readonly request: typeof fetch = fetch) {}
  public async execute<T>(definition: AgentDefinition, input: unknown, context: { readonly projectId: string; readonly channelId?: PublisherChannelId | undefined }): Promise<AgentExecutionResult<T>> {
    const started = Date.now();
    if (definition.id.includes("semantic-reviewer")) return { output: reviewConsistency(input as { core: EditorialCore; variants: readonly PlatformContentVariant[] }, new Date().toISOString()) as T, metadata: { provider: this.credential.provider, model: `${this.credential.model}+deterministic-review`, durationMs: Date.now() - started } };
    const output = this.credential.provider === "OPENAI" ? await this.openai(prompt(definition, input, context.channelId)) : await this.anthropic(prompt(definition, input, context.channelId)); const schema = schemaFor(definition.id); if (!schema) throw new Error("LLM_OUTPUT_INVALID");
    try { return { output: schema.parse(extractJson(output)) as T, metadata: { provider: this.credential.provider as LlmProvider, model: this.credential.model, durationMs: Date.now() - started } }; } catch { throw new Error("LLM_OUTPUT_INVALID"); }
  }
  private async openai(content: string) { const response = await this.request("https://api.openai.com/v1/responses", { method: "POST", headers: { authorization: `Bearer ${this.credential.apiKey}`, "content-type": "application/json" }, body: JSON.stringify({ model: this.credential.model, input: content }) }); if (!response.ok) throw new Error(providerError(response.status)); const body = await response.json() as { output_text?: string }; if (!body.output_text) throw new Error("LLM_OUTPUT_INVALID"); return body.output_text; }
  private async anthropic(content: string) { const response = await this.request("https://api.anthropic.com/v1/messages", { method: "POST", headers: { "x-api-key": this.credential.apiKey, "anthropic-version": "2023-06-01", "content-type": "application/json" }, body: JSON.stringify({ model: this.credential.model, max_tokens: 4096, messages: [{ role: "user", content }] }) }); if (!response.ok) throw new Error(providerError(response.status)); const body = await response.json() as { content?: Array<{ type: string; text?: string }> }; const text = body.content?.find((item) => item.type === "text")?.text; if (!text) throw new Error("LLM_OUTPUT_INVALID"); return text; }
}
