import assert from "node:assert/strict";
import { test } from "node:test";
import { KnowledgePolicyApplicationApi } from "../../src/application/bindings/KnowledgePolicyApplicationApi.js";
import { createKnowledgePolicyBindings } from "../../src/application/bindings/KnowledgePolicyBindings.js";
import { ApplicationCommandRunner } from "../../src/application/services/ApplicationCommandRunner.js";
import { ApplicationQueryRunner } from "../../src/application/services/ApplicationQueryRunner.js";
import { ReferenceApplicationTransactionFactory, ReferenceReadRepositorySessionFactory } from "../../src/infrastructure/persistence/ApplicationTransactionFactory.js";
import { ReferencePersistenceProvider } from "../../src/infrastructure/persistence/ReferencePersistenceProvider.js";
import { InMemoryKnowledgeReferenceValidation } from "../../src/modules/knowledge-policy/infrastructure/InMemoryKnowledgeReferenceValidation.js";
import { AssetId, AssetVersionId, TenantId } from "../../src/shared/identity/index.js";
import { AssetReference, AssetVersionReference } from "../../src/shared/references/index.js";
import type { ApplicationCommandContext, OperationCommandDto } from "../../src/application/dto/ApplicationContext.js";

const tenantId = "tenant_knowledge_api";
const now = "2026-07-27T15:00:00.000Z";
const context: ApplicationCommandContext = { tenantId, actor: { reference: "steward_knowledge_api" }, correlationId: "correlation_knowledge_api", causationId: "causation_knowledge_api" };
const audit = { occurredAt: now, evidence: [{ evidenceId: "evidence_knowledge_api", source: "test", type: "fixture", capturedAt: now }], lineage: [{ sourceId: "source_knowledge_api", targetId: "knowledge_knowledge_api", relationship: "references", declaredAt: now }] };
function knowledgeCommand(): OperationCommandDto { return { idempotencyKey: "create-knowledge-api", reason: "Create Knowledge", payload: { knowledgeId: "knowledge_knowledge_api", metadata: { title: "Knowledge", summary: "Summary", stewardNote: "Steward note", createdAt: now, updatedAt: now }, scope: { domainArea: "Governance", audience: "Stewards", constraints: ["tenant-bound"] }, assetReferences: [{ id: "asset_knowledge_api", tenantId }], assetVersionReferences: [{ assetId: "asset_knowledge_api", versionId: "asset_version_knowledge_api_v1", tenantId }], policyReferences: [], ...audit } }; }
test("Knowledge/Policy exposes the nine executable bindings", () => { const validation = new InMemoryKnowledgeReferenceValidation(); assert.equal(Object.keys(createKnowledgePolicyBindings(validation)).length, 9); });
test("Knowledge create commits once, replays generically and projects read-only", async () => { const provider = new ReferencePersistenceProvider(); const validation = new InMemoryKnowledgeReferenceValidation(); const tenant = TenantId.from(tenantId); validation.registerAsset(new AssetReference(AssetId.from("asset_knowledge_api"), tenant)); validation.registerAssetVersion(new AssetVersionReference(AssetId.from("asset_knowledge_api"), AssetVersionId.from("asset_version_knowledge_api_v1"), tenant)); const api = new KnowledgePolicyApplicationApi(new ApplicationCommandRunner(new ReferenceApplicationTransactionFactory(provider)), new ApplicationQueryRunner(new ReferenceReadRepositorySessionFactory(provider)), validation); const first = await api.createKnowledge(knowledgeCommand(), context); assert.deepEqual(await api.createKnowledge(knowledgeCommand(), context), first); assert.equal((await api.getKnowledge({ targetId: "knowledge_knowledge_api" }, { tenantId, correlationId: context.correlationId }))?.status, "PROPOSED"); assert.equal((await api.listKnowledge({}, { tenantId, correlationId: context.correlationId })).length, 1); assert.equal(provider.listAuditRecords(tenantId).length, 1); });
test("Knowledge/Policy executes every public command and query through provider-backed sessions", async () => {
  const provider = new ReferencePersistenceProvider(); const validation = new InMemoryKnowledgeReferenceValidation(); const tenant = TenantId.from(tenantId);
  validation.registerAsset(new AssetReference(AssetId.from("asset_knowledge_api"), tenant)); validation.registerAssetVersion(new AssetVersionReference(AssetId.from("asset_knowledge_api"), AssetVersionId.from("asset_version_knowledge_api_v1"), tenant));
  const api = new KnowledgePolicyApplicationApi(new ApplicationCommandRunner(new ReferenceApplicationTransactionFactory(provider)), new ApplicationQueryRunner(new ReferenceReadRepositorySessionFactory(provider)), validation);
  await api.createKnowledge(knowledgeCommand(), context);
  await api.curateKnowledge({ idempotencyKey: "curate-knowledge-api", reason: "Curate Knowledge", targetId: "knowledge_knowledge_api", payload: { curatorDecisionId: "decision_knowledge_api", ...audit } }, context);
  await api.linkKnowledgeAsset({ idempotencyKey: "link-knowledge-api", reason: "Link Knowledge", targetId: "knowledge_knowledge_api", payload: { relationship: { source: { id: "knowledge_knowledge_api", tenantId }, targetKind: "asset", target: { id: "asset_knowledge_api", tenantId }, type: "SUPPORTS", rationale: "Knowledge supports the Asset", evidence: audit.evidence, lineage: audit.lineage, createdAt: now }, ...audit } }, context);
  const policyPayload = { metadata: { title: "Governance Policy", summary: "Institutional rule", scope: "BBA Core", createdAt: now, updatedAt: now }, authorityContext: { ownerReference: { reference: "person:owner", tenantId }, stewardReference: { reference: "person:steward", tenantId }, authorityReference: { id: "authority_policy_api", tenantId }, decisionReference: { id: "decision_policy_api", tenantId } }, initialVersionId: "policy_version_api_v1", ruleSet: { rules: [{ ruleKey: "human-governance", statement: "Human authority remains final", obligation: "A steward records accountable rationale", applicability: "Institutional decisions", priority: 1, rationale: "Preserves accountability" }] }, authorityReference: { id: "authority_policy_api", tenantId }, decisionReference: { id: "decision_policy_api", tenantId } };
  await api.createPolicy({ idempotencyKey: "create-policy-api", reason: "Create Policy", targetId: "policy_api", payload: { ...policyPayload, ...audit } }, context);
  await api.createPolicyVersion({ idempotencyKey: "create-policy-version-api", reason: "Create Policy Version", targetId: "policy_api", payload: { versionId: "policy_version_api_v2", predecessorVersionId: "policy_version_api_v1", ruleSet: policyPayload.ruleSet, authorityReference: policyPayload.authorityReference, decisionReference: policyPayload.decisionReference, ...audit } }, context);
  const knowledge = await api.getKnowledge({ targetId: "knowledge_knowledge_api" }, { tenantId, correlationId: context.correlationId });
  const policy = await api.getPolicy({ targetId: "policy_api" }, { tenantId, correlationId: context.correlationId });
  assert.equal(knowledge?.status, "CURATED"); assert.equal(knowledge?.currentRevision, 3); assert.equal("relationships" in (knowledge as unknown as Record<string, unknown>), false);
  assert.equal(policy?.currentVersionId, "policy_version_api_v2"); assert.equal((await api.listPolicies({}, { tenantId, correlationId: context.correlationId })).length, 1); assert.equal((await api.listKnowledge({}, { tenantId, correlationId: context.correlationId })).length, 1);
  assert.equal(provider.listAuditRecords(tenantId).length, 5);
});
test("Knowledge validation fails before opening a Unit of Work", () => { const validation = new InMemoryKnowledgeReferenceValidation(); let opened = 0; const api = new KnowledgePolicyApplicationApi(new ApplicationCommandRunner({ open: () => { opened += 1; throw new Error("must not open"); } }), new ApplicationQueryRunner({ open: () => { throw new Error("must not read"); } }), validation); assert.throws(() => api.createKnowledge({ idempotencyKey: "invalid", reason: "invalid", payload: {} }, context), /knowledgeId/u); assert.equal(opened, 0); });
