import { Link } from "react-router-dom";
import { agencyDeliveryPackages } from "../content/deliveries/index.js";

const anatomy = [
  ["Purpose", "Why the Package exists and the customer outcome it supports."],
  ["Contents", "The complete reviewed result represented by the Package."],
  ["Artifacts", "The individual structured outputs included in the Package."],
  ["Review", "The explanatory checks considered before a future delivery."],
  ["Human approval", "The customer decision required before the Package is considered ready."],
  ["Versions", "The preserved evolution of artifacts and requested revisions."],
  ["Traceability", "The connection between Project context, artifacts, reviews, and decisions."],
  ["Limitations", "Constraints and responsibilities that remain visible in the final delivery."],
];
const reviewLifecycle = ["Confirm Package completeness", "Review artifact quality", "Inspect traceability", "Review limitations", "Request revisions when necessary", "Confirm the final Package"];

export function Deliveries() {
  return (
    <main className="page-shell deliveries-page">
      <section className="deliveries-hero container" aria-labelledby="deliveries-heading">
        <div><p className="section-kicker">Delivery Packages</p><h1 id="deliveries-heading">See what a completed BBA Agency Project delivers</h1><p>Delivery Packages bring together the approved artifacts, decisions, versions, quality findings, and limitations produced by a BBA Agency Project.</p><div className="deliveries-hero-links"><a href="#package-catalog">Explore the Packages <span aria-hidden="true">→</span></a><a href="#delivery-review">Learn how delivery works <span aria-hidden="true">→</span></a></div></div>
        <aside className="deliveries-disclosure"><span>Informational website</span><p>This informational website explains Delivery Packages. It does not generate, approve, export, download, or publish them.</p><a href="https://dev.bba.country" target="_blank" rel="noopener noreferrer" aria-label="View the functional Publisher prototype at dev.bba.country in a new tab">View the Publisher prototype <span aria-hidden="true">↗</span></a></aside>
      </section>
      <section className="deliveries-section container" aria-labelledby="package-definition"><p className="section-kicker">What is a Delivery Package?</p><h2 id="package-definition">A reviewed customer outcome, not a collection of isolated files</h2><p className="deliveries-lead">A Package keeps purpose, artifacts, review evidence, versions, decisions, and limitations together so the customer can understand what was produced and why.</p></section>
      <section className="deliveries-section container" aria-labelledby="package-anatomy"><p className="section-kicker">Common Package anatomy</p><h2 id="package-anatomy">The information that stays connected through delivery</h2><div className="deliveries-anatomy-grid">{anatomy.map(([name, description]) => <article key={name}><h3>{name}</h3><p>{description}</p></article>)}</div></section>
      <section className="deliveries-section container" id="delivery-review" aria-labelledby="delivery-review-heading"><p className="section-kicker">Quality and Human Review</p><h2 id="delivery-review-heading">Delivery remains subject to Human Governance</h2><p className="deliveries-lead">These explanatory checkpoints show how a future functional platform may organize customer review. They are not active controls on this website.</p><ol className="deliveries-review-lifecycle">{reviewLifecycle.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong></li>)}</ol></section>
      <section className="deliveries-section deliveries-revision-trace container" aria-labelledby="delivery-revisions"><article><p className="section-kicker">Revision lifecycle</p><h2 id="delivery-revisions">A revision preserves context instead of erasing it</h2><p>Customer guidance may affect artifacts, findings, and a prior final decision. A new version preserves earlier rationale, source references, and traceability.</p></article><article><p className="section-kicker">Traceability</p><h2>From Project context to a final Package</h2><p>Each Package makes the relationship between context, artifact versions, review checkpoints, and human decisions understandable without exposing platform internals.</p></article></section>
      <section className="deliveries-section container" id="package-catalog" aria-labelledby="package-catalog-heading"><p className="section-kicker">Package catalog</p><h2 id="package-catalog-heading">Explore what each BBA Agency Product delivers</h2><div className="deliveries-catalog">{agencyDeliveryPackages.map((deliveryPackage) => <article className="delivery-package-preview" key={deliveryPackage.id}><div className="delivery-package-preview-top"><span className={`delivery-status ${deliveryPackage.status.toLowerCase()}`}>{deliveryPackage.availability.label}</span><span>{deliveryPackage.category}</span></div><h3>{deliveryPackage.name}</h3><p>{deliveryPackage.purpose}</p><dl><div><dt>Product</dt><dd>{deliveryPackage.productName}</dd></div><div><dt>Representative Project</dt><dd>{deliveryPackage.projectName}</dd></div><div><dt>Customer outcome</dt><dd>{deliveryPackage.customerOutcome}</dd></div><div><dt>Representative artifacts</dt><dd>{deliveryPackage.artifacts.slice(0, 3).map((artifact) => artifact.name).join(" · ")}</dd></div></dl><p className="delivery-approval-indicator">Human approval required</p><Link to={deliveryPackage.route}>View what this Package contains <span aria-hidden="true">→</span></Link>{deliveryPackage.prototype.available ? <a className="delivery-prototype-link" href={deliveryPackage.prototype.url} target="_blank" rel="noopener noreferrer" aria-label="Explore the functional Publisher prototype at dev.bba.country in a new tab">Explore the functional Publisher prototype <span aria-hidden="true">↗</span></a> : null}</article>)}</div></section>
      <section className="deliveries-platform-disclosure container" aria-labelledby="static-platform-heading"><p className="section-kicker">Static versus Platform</p><h2 id="static-platform-heading">This site explains delivery. The functional platform may coordinate it.</h2><p>`bba.country` provides canonical informational examples. A future functional platform may assemble Packages, preserve revisions, and present review records, while human authority and any external Connector remain separate requirements.</p></section>
    </main>
  );
}
