import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { CreatePublisherProjectRequest, HumanDecision } from "@bba/publisher-prototype";
import { useBbaSdkRuntime } from "../provider/BbaSdkProvider.js";

export const projectKeys = { all: (tenantId: string) => ["agency-projects", tenantId] as const, detail: (tenantId: string, projectId: string) => ["agency-projects", tenantId, projectId] as const, ai: (tenantId: string) => ["agency-ai-settings", tenantId] as const };
function runtime() { const value = useBbaSdkRuntime(); if (!value.ready) throw new Error("AGENCY_SDK_NOT_READY"); return value.ready; }
export function useProjectsQuery() { const ready = runtime(); return useQuery({ queryKey: projectKeys.all(ready.tenantId), queryFn: async () => (await ready.agency.listProjects()).data }); }
export function useProjectQuery(projectId: string) { const ready = runtime(); return useQuery({ queryKey: projectKeys.detail(ready.tenantId, projectId), queryFn: async () => (await ready.agency.getProject(projectId)).data }); }
export function useCreateProjectCommand() { const ready = runtime(); const cache = useQueryClient(); return useMutation({ mutationFn: ({ request, idempotencyKey }: { request: CreatePublisherProjectRequest; idempotencyKey: string }) => ready.agency.createProject(request, idempotencyKey), onSuccess: () => cache.invalidateQueries({ queryKey: projectKeys.all(ready.tenantId) }) }); }
export function useExecuteProjectCommand(projectId: string) { const ready = runtime(); const cache = useQueryClient(); return useMutation({ mutationFn: (idempotencyKey: string) => ready.agency.executeProject(projectId, idempotencyKey), onSuccess: () => cache.invalidateQueries({ queryKey: projectKeys.detail(ready.tenantId, projectId) }) }); }
export function useProjectDecisionCommand(projectId: string) { const ready = runtime(); const cache = useQueryClient(); return useMutation({ mutationFn: ({ decision, idempotencyKey }: { decision: Omit<HumanDecision, "actorReference" | "occurredAt">; idempotencyKey: string }) => ready.agency.recordDecision(projectId, decision, idempotencyKey), onSuccess: () => cache.invalidateQueries({ queryKey: projectKeys.detail(ready.tenantId, projectId) }) }); }
export function useAiSettingsQuery() { const ready = runtime(); return useQuery({ queryKey: projectKeys.ai(ready.tenantId), queryFn: async () => (await ready.agency.getAiSettings()).data }); }
export function useConfigureAiCommand() { const ready = runtime(); const cache = useQueryClient(); return useMutation({ mutationFn: ({ value, idempotencyKey }: { value: { provider: "OPENAI" | "ANTHROPIC"; apiKey: string; model: string }; idempotencyKey: string }) => ready.agency.configureAi(value, idempotencyKey), onSuccess: () => cache.invalidateQueries({ queryKey: projectKeys.ai(ready.tenantId) }) }); }
