import { Alert, Badge, Button, Card, Field, Input, Select } from "@bba/ui";
import { useAiSettingsQuery, useConfigureAiCommand } from "@bba/sdk-react";
import { useState, type FormEvent } from "react";

export function AiSettingsPage() {
  const query = useAiSettingsQuery(); const command = useConfigureAiCommand(); const [provider, setProvider] = useState<"OPENAI" | "ANTHROPIC">("OPENAI"); const [model, setModel] = useState("gpt-5.6-terra"); const [apiKey, setApiKey] = useState("");
  function changeProvider(value: "OPENAI" | "ANTHROPIC") { setProvider(value); setModel(value === "OPENAI" ? "gpt-5.6-terra" : "claude-sonnet-5"); }
  async function submit(event: FormEvent) { event.preventDefault(); await command.mutateAsync({ value: { provider, model, apiKey }, idempotencyKey: crypto.randomUUID() }); setApiKey(""); }
  return <section className="bba-page bba-page--narrow"><header><span className="bba-page__eyebrow">Conta</span><h1>Modelos de IA</h1><p>Use sua própria chave para uma execução BYOK. A credencial permanece somente na memória do servidor por até 60 minutos.</p></header><Card><h2>Estado efêmero</h2>{query.data?.map((item) => <p key={item.provider}><strong>{item.provider}</strong> <Badge>{item.configured ? "Configurado" : "Não configurado"}</Badge>{item.configured ? ` ${item.model} · expira ${item.expiresAt}` : ""}</p>)}</Card><form className="bba-form" onSubmit={(event) => void submit(event)}><Card><Field label="Provedor"><Select value={provider} onChange={(event) => changeProvider(event.target.value as "OPENAI" | "ANTHROPIC")}><option value="OPENAI">OpenAI</option><option value="ANTHROPIC">Anthropic</option></Select></Field><Field label="Modelo"><Input required value={model} onChange={(event) => setModel(event.target.value)} /></Field><Field label="Chave da API"><Input autoComplete="off" required type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} /></Field><Alert title="Credencial protegida">A chave não é salva no navegador, não retorna pela API e não é incluída em logs ou prompts.</Alert><Button disabled={command.isPending} type="submit">Configurar por 60 minutos</Button></Card></form>{command.isError ? <Alert title="Configuração falhou">{command.error.message}</Alert> : null}</section>;
}
