import { expect, test, type Page } from "@playwright/test";

async function configure(page: Page) { await page.getByLabel("API base URL").fill("https://api.example.test"); await page.getByLabel("Bearer token").fill("token-e2e"); await page.getByLabel("Tenant").fill("tenant_e2e"); await page.getByLabel("Subject").fill("steward-e2e"); await page.getByLabel("Actor reference").fill("person:steward-e2e"); await page.getByRole("button", { name: "Iniciar sessão local" }).click(); }

test("Publisher delivers an approved three-channel Editorial Package", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name === "mobile", "The complete journey runs once; mobile shell remains covered separately"); test.setTimeout(60_000);
  const context = { contextId: "context-publisher", version: 1, title: "Lançamento Publisher", topic: "Governança editorial", objective: "Explicar o serviço", audience: "Lideranças", centralMessage: "Uma mensagem aprovada pode servir vários canais", tone: "Preciso", language: "pt-BR", requiredFacts: ["Aprovação humana é obrigatória"], requiredTerms: ["governança"], prohibitedClaims: ["publicação autônoma"], constraints: [], materials: [], channels: ["blog", "linkedin", "instagram"] };
  const core = { version: 1, objective: context.objective, audience: context.audience, centralMessage: context.centralMessage, claims: [{ id: "claim-1", statement: context.requiredFacts[0], evidenceIds: ["evidence-context"], required: true }], evidence: [{ id: "evidence-context", materialId: context.contextId, locator: "Contexto Editorial" }], tone: context.tone, requiredTerms: context.requiredTerms, prohibitedClaims: context.prohibitedClaims, language: context.language, limitations: ["No external publication"] };
  const variants = (["blog", "linkedin", "instagram"] as const).map((channelId) => ({ variantId: `variant-${channelId}`, version: 1, channelId, format: "content", blocks: [{ id: `block-${channelId}`, kind: "CLAIM", text: context.requiredFacts[0], sourceClaimIds: ["claim-1"] }], tags: ["governança"], metadata: { tone: "Preciso" }, editorialCoreVersion: 1 }));
  const consistency = { passed: true, findings: [{ code: "TRACEABILITY_PRESERVED", severity: "INFO", message: "Consistência preservada" }], reviewedAt: "2026-07-29T12:00:00.000Z" };
  const plan = { version: 1, strategy: "Preservar a mensagem", estimatedExecutionUnits: 60, items: variants.map((variant, index) => ({ channelId: variant.channelId, format: variant.format, purpose: "Adaptar", sequence: index + 1, adaptation: "Por canal" })) };
  const base = { projectId: "project-publisher", tenantId: "tenant_e2e", subject: "steward-e2e", actorReference: "person:steward-e2e", productId: "bba.publisher.multiplatform-publication", productVersion: "1.0.0", executionMode: "DETERMINISTIC", status: "COMPOSITION_READY", visibleStage: "Contexto confirmado", context, editorialCores: [], plans: [], variants: [], consistencyReports: [], packages: [], decisions: [], events: [], platform: { missionId: "mission-publisher", assetIds: [], transactionIds: [] }, currentAgentIndex: 0, currentChannelIndex: 0, createdAt: "2026-07-29T12:00:00.000Z", updatedAt: "2026-07-29T12:00:00.000Z" };
  let current: Record<string, unknown> = base; const envelope = () => JSON.stringify({ data: current, meta: { correlationId: "correlation-publisher" } });
  await page.route("https://api.example.test/agency/v1/projects**", async (route) => { const url = route.request().url(); const method = route.request().method(); if (method === "POST" && url.endsWith("/projects")) current = base; else if (url.endsWith("/execute")) current = current.status === "COMPOSITION_READY" ? { ...base, status: "AWAITING_EDITORIAL_CORE_APPROVAL", editorialCores: [core], visibleStage: "Núcleo editorial pronto" } : { ...base, status: "AWAITING_PACKAGE_APPROVAL", editorialCores: [core], plans: [plan], variants, consistencyReports: [consistency], packages: [{ packageId: "package-publisher", version: 1, projectId: "project-publisher", editorialCore: core, plan, variants, consistency, status: "AWAITING_REVIEW", disclaimer: "No external publication" }], visibleStage: "Pacote Editorial pronto" }; else if (url.endsWith("/decisions")) { const decision = route.request().postDataJSON() as { target: string }; current = decision.target === "EDITORIAL_CORE" ? { ...current, status: "RUNNING_EDITORIAL_PLAN" } : { ...current, status: "READY_FOR_DELIVERY", packages: ((current.packages ?? []) as Array<Record<string, unknown>>).map((item) => ({ ...item, status: "READY_FOR_DELIVERY" })) }; } await route.fulfill({ status: 200, contentType: "application/json", body: envelope() }); });
  await page.addInitScript(() => { let count = 0; Object.defineProperty(crypto, "randomUUID", { value: () => count++ === 0 ? "project-publisher" : `00000000-0000-4000-8000-${String(count).padStart(12, "0")}` }); }); await page.goto("/projects/new"); await configure(page);
  await page.getByLabel("Nome do Projeto").fill(context.title); await page.getByRole("textbox", { name: "Tema" }).fill(context.topic); await page.getByLabel("Objetivo da comunicação").fill(context.objective); await page.getByLabel("Público").fill(context.audience); await page.getByLabel("Mensagem principal").fill(context.centralMessage); await page.getByLabel("Fatos obrigatórios").fill(context.requiredFacts[0]); await expect(page.getByText("Pacote Editorial multicanal")).toBeVisible(); await page.getByRole("button", { name: "Confirmar e criar Projeto" }).click();
  await page.getByRole("button", { name: "Compreender contexto" }).click(); await page.getByLabel("Orientação ou justificativa da decisão").fill("Mensagem correta"); await page.getByRole("button", { name: "Aprovar" }).click(); await page.getByRole("button", { name: "Produzir Pacote Editorial" }).click(); await expect(page.getByRole("alert").filter({ hasText: "Consistência preservada" })).toBeVisible(); await page.getByLabel("Orientação ou justificativa da decisão").fill("Pacote pronto"); await page.getByRole("button", { name: "Aprovar" }).click(); await expect(page.getByText(/3 conteúdos adaptados/u)).toBeVisible();
});
