import { expect, test } from "@playwright/test";

test("golden path delivers a static Editorial Package", async ({ page }) => {
  test.setTimeout(60_000); await page.goto("/"); await expect(page.getByRole("heading", { name: "Como podemos ajudar?" })).toBeVisible(); await page.getByRole("link", { name: "Criar novo Projeto" }).click();
  await page.getByLabel("Título do Projeto").fill("Projeto E2E Publisher"); await page.getByLabel("O que precisa ser comunicado").fill("Lançamento do produto"); await page.getByLabel("Objetivo da comunicação").fill("Explicar o produto"); await page.getByLabel("Resultado esperado").fill("Pacote multicanal pronto"); await page.getByRole("button", { name: "Continuar →" }).click();
  await page.getByLabel("Público").fill("Builders e pesquisadores"); await page.getByLabel("Mensagem principal").fill("Inteligência pode ser coordenada com governança humana"); await page.getByRole("button", { name: "Continuar →" }).click(); await page.getByLabel("Materiais textuais").fill("Fonte institucional controlada"); await page.getByRole("button", { name: "Continuar →" }).click(); await page.getByLabel("Fatos obrigatórios").fill("Humanos mantêm autoridade"); await page.getByLabel("Termos obrigatórios").fill("governança humana"); await page.getByRole("button", { name: "Continuar →" }).click(); await page.getByRole("button", { name: "Continuar →" }).click(); await page.getByRole("button", { name: "Continuar →" }).click();
  await expect(page.getByRole("heading", { name: "Você receberá" })).toBeVisible(); await expect(page.getByText("Consumo estimado: 24 unidades de execução")).toBeVisible(); await page.getByRole("button", { name: "Criar Projeto →" }).click();
  await page.getByRole("button", { name: "Iniciar execução" }).click(); await page.getByRole("button", { name: "Avançar simulação →" }).click(); await expect(page.getByRole("heading", { name: "A equipe compreendeu corretamente o contexto?" })).toBeVisible(); await page.getByRole("button", { name: "Aprovar núcleo editorial" }).click();
  for (let index = 0; index < 5; index += 1) await page.getByRole("button", { name: "Avançar simulação →" }).click();
  await page.getByRole("link", { name: "Revisão" }).click(); await expect(page.getByText("Pronto para decisão")).toBeVisible(); await page.getByRole("button", { name: "Aprovar pacote" }).click(); await page.getByRole("link", { name: "Entrega" }).click(); await expect(page.locator(".project-status")).toHaveText("Pronto para entrega"); await expect(page.getByText("Nenhuma publicação externa foi realizada.")).toBeVisible();
});

test("revision path invalidates and regenerates all channel versions", async ({ page }) => {
  await page.goto("/projects/demo-final-review/review"); await page.getByLabel("Orientação ou justificativa").fill("Explicitar governança humana"); await page.getByRole("button", { name: "Solicitar alterações" }).click(); await expect(page.getByRole("dialog")).toContainText("Blog v1, LinkedIn v1, Instagram v1"); await page.getByRole("button", { name: "Confirmar alteração" }).click(); await page.getByRole("link", { name: "Conteúdos" }).click(); await expect(page.getByText("BLOG / v2")).toBeVisible(); await page.getByRole("button", { name: "Comparar versões" }).click(); await expect(page.getByRole("dialog")).toContainText("Versão anterior"); await page.getByRole("button", { name: "×" }).click(); await page.getByRole("link", { name: "Revisão" }).click(); await page.getByRole("button", { name: "Aprovar pacote" }).click(); await page.getByRole("link", { name: "Entrega" }).click(); await expect(page.locator(".project-status")).toHaveText("Pronto para entrega");
});

test("failure path explains and retries the failed stage", async ({ page }) => {
  await page.goto("/projects/demo-failure/content"); await expect(page.getByRole("alert")).toContainText("Não foi possível concluir esta etapa"); await expect(page.getByText("A simulação do adaptador de LinkedIn foi interrompida antes de concluir.")).toBeVisible(); await page.getByRole("button", { name: "Tentar novamente" }).click(); await expect(page.getByRole("alert")).toHaveCount(0); await expect(page.getByRole("button", { name: "Avançar simulação →" })).toBeVisible();
});
