import { AggregateRoot } from "../../../shared/aggregate/AggregateRoot.js";
import type { JsonObject } from "../../../shared/common/serialization.js";
import { deepFreeze, stableSerialize } from "../../../shared/common/serialization.js";
import { InvariantViolation } from "../../../shared/errors/InvariantViolation.js";
import type { EvidenceReference } from "../../../shared/evidence/EvidenceReference.js";
import { ConnectorExecutionId, ConnectorId, TenantId } from "../../../shared/identity/index.js";
import type { LineageReference } from "../../../shared/lineage/LineageReference.js";
import { ConnectorCapabilityReference, ConnectorExecutionReference, ConnectorReference } from "../../../shared/references/index.js";
import { Version } from "../../../shared/version/Version.js";
import type { CancelExecutionCommand, CompleteExecutionCommand, ConnectorAuditInput, CreateExecutionCommand, FailExecutionCommand, ExecutionLifecycleCommand } from "./ConnectorCommands.js";
import { ConnectorDomainEvent, ConnectorExecutionCancelled, ConnectorExecutionCreated, ConnectorExecutionFailed, ConnectorExecutionStarted, ConnectorExecutionSucceeded } from "./ConnectorEvents.js";
import { ConnectorRequestMetadata, ExternalEvidenceFailure, ExternalEvidenceSuccess, type ExternalEvidence } from "./ConnectorValues.js";
import { ConnectorExecutionStatus, type ConnectorExecutionStatusType } from "./ConnectorTypes.js";
import { evidenceFromJSON, lineageFromJSON } from "./ConnectorSerialization.js";

export interface ConnectorExecutionSnapshot { readonly schemaVersion: 1; readonly executionId: string; readonly tenantId: string; readonly connectorReference: JsonObject; readonly capabilityReference: JsonObject; readonly operationKey: string; readonly request: JsonObject; readonly status: ConnectorExecutionStatusType; readonly resultMetadata: JsonObject | null; readonly externalEvidence: JsonObject | null; readonly cancellationReason: string | null; readonly startedAt: string | null; readonly finishedAt: string | null; readonly evidence: readonly JsonObject[]; readonly lineage: readonly JsonObject[]; readonly version: number; }

export class ConnectorExecution extends AggregateRoot<ConnectorExecutionId> {
  private constructor(private readonly executionTenantId: TenantId, private readonly executionConnectorReference: ConnectorReference, private readonly executionCapabilityReference: ConnectorCapabilityReference, private readonly executionOperationKey: string, private readonly executionRequest: ConnectorRequestMetadata, private executionStatus: ConnectorExecutionStatusType, private executionResultMetadata: JsonObject | null, private executionExternalEvidence: ExternalEvidence | null, private executionCancellationReason: string | null, private executionStartedAt: string | null, private executionFinishedAt: string | null, private executionEvidence: EvidenceReference[], private executionLineage: LineageReference[], version: Version, id: ConnectorExecutionId) { super(id, version); }
  public static create(command: CreateExecutionCommand): ConnectorExecution {
    if (!command.connectorReference.tenantId.equals(command.capabilityReference.tenantId)) throw new InvariantViolation("Connector execution references crossed a Tenant boundary");
    if (!command.request.operationKey || command.operationKey.value !== command.request.operationKey) throw new InvariantViolation("Execution operationKey must match request metadata");
    const execution = new ConnectorExecution(command.connectorReference.tenantId, command.connectorReference, command.capabilityReference, command.operationKey.value, command.request, ConnectorExecutionStatus.CREATED, null, null, null, null, null, [...command.evidence], [...command.lineage], Version.initial(), command.executionId);
    execution.mutate(command); execution.emit(ConnectorExecutionCreated, command, { connectorExecutionId: execution.id.toString(), connectorReference: command.connectorReference.toJSON(), capabilityReference: command.capabilityReference.toJSON(), operationKey: command.operationKey.value, idempotencyKey: command.request.idempotencyKey }); return execution;
  }
  public static rehydrate(snapshot: ConnectorExecutionSnapshot): ConnectorExecution {
    if (snapshot.schemaVersion !== 1) throw new InvariantViolation("Unsupported ConnectorExecution snapshot schema");
    return new ConnectorExecution(TenantId.from(snapshot.tenantId), ConnectorReference.fromJSON(snapshot.connectorReference as { id: string; tenantId: string }), ConnectorCapabilityReference.fromJSON(snapshot.capabilityReference as { id: string; tenantId: string }), snapshot.operationKey, new ConnectorRequestMetadata(snapshot.request as never), snapshot.status, snapshot.resultMetadata, snapshot.externalEvidence === null ? null : (snapshot.externalEvidence.kind === "SUCCESS" ? new ExternalEvidenceSuccess(snapshot.externalEvidence as never) : new ExternalEvidenceFailure(snapshot.externalEvidence as never)), snapshot.cancellationReason, snapshot.startedAt, snapshot.finishedAt, snapshot.evidence.map(evidenceFromJSON), snapshot.lineage.map(lineageFromJSON), Version.from(snapshot.version), ConnectorExecutionId.from(snapshot.executionId));
  }
  public get tenantId(): TenantId { return this.executionTenantId; }
  public get connectorReference(): ConnectorReference { return new ConnectorReference(this.executionConnectorReference.id, this.executionConnectorReference.tenantId); }
  public get capabilityReference(): ConnectorCapabilityReference { return new ConnectorCapabilityReference(this.executionCapabilityReference.id, this.executionCapabilityReference.tenantId); }
  public get operationKey(): string { return this.executionOperationKey; }
  public get request(): ConnectorRequestMetadata { return new ConnectorRequestMetadata(this.executionRequest.toJSON() as never); }
  public get status(): ConnectorExecutionStatusType { return this.executionStatus; }
  public get externalEvidence(): ExternalEvidence | null { return this.executionExternalEvidence === null ? null : this.executionExternalEvidence.kind === "SUCCESS" ? new ExternalEvidenceSuccess(this.executionExternalEvidence.toJSON() as never) : new ExternalEvidenceFailure(this.executionExternalEvidence.toJSON() as never); }
  public get reference(): ConnectorExecutionReference { return new ConnectorExecutionReference(this.id, this.tenantId); }
  public start(command: ExecutionLifecycleCommand): void { if (this.status !== ConnectorExecutionStatus.CREATED) throw new InvariantViolation(`ConnectorExecution cannot start from ${this.status}`); this.executionStatus = ConnectorExecutionStatus.RUNNING; this.executionStartedAt = command.occurredAt; this.mutate(command); this.emit(ConnectorExecutionStarted, command); }
  public complete(command: CompleteExecutionCommand, resultMetadata: JsonObject): void { if (this.status !== ConnectorExecutionStatus.RUNNING) throw new InvariantViolation(`ConnectorExecution cannot complete from ${this.status}`); if (!(command.externalEvidence instanceof ExternalEvidenceSuccess)) throw new InvariantViolation("SUCCEEDED requires ExternalEvidenceSuccess"); const evidence = command.externalEvidence.toJSON(); this.executionStatus = ConnectorExecutionStatus.SUCCEEDED; this.executionExternalEvidence = command.externalEvidence; this.executionResultMetadata = resultMetadata; this.executionFinishedAt = command.occurredAt; this.mutate(command); this.emit(ConnectorExecutionSucceeded, command, { externalIdentifier: String(evidence.externalIdentifier), providerReference: String(evidence.providerReference), ...(typeof evidence.checksum === "string" ? { checksum: evidence.checksum } : {}) }); }
  public fail(command: FailExecutionCommand, resultMetadata: JsonObject): void { if (this.status !== ConnectorExecutionStatus.RUNNING) throw new InvariantViolation(`ConnectorExecution cannot fail from ${this.status}`); if (!(command.externalEvidence instanceof ExternalEvidenceFailure)) throw new InvariantViolation("FAILED requires ExternalEvidenceFailure"); const evidence = command.externalEvidence.toJSON(); this.executionStatus = ConnectorExecutionStatus.FAILED; this.executionExternalEvidence = command.externalEvidence; this.executionResultMetadata = resultMetadata; this.executionFinishedAt = command.occurredAt; this.mutate(command); this.emit(ConnectorExecutionFailed, command, { failureCode: String(evidence.failureCode), retryable: Boolean(evidence.retryable) }); }
  public cancel(command: CancelExecutionCommand): void { if (this.status !== ConnectorExecutionStatus.CREATED && this.status !== ConnectorExecutionStatus.RUNNING) throw new InvariantViolation(`ConnectorExecution cannot cancel from ${this.status}`); if (command.cancellationReason.trim().length === 0) throw new InvariantViolation("Cancellation reason is required"); this.executionStatus = ConnectorExecutionStatus.CANCELLED; this.executionCancellationReason = command.cancellationReason.trim(); this.executionFinishedAt = command.occurredAt; this.mutate(command); this.emit(ConnectorExecutionCancelled, command, { reason: this.executionCancellationReason }); }
  public toSnapshot(): ConnectorExecutionSnapshot { return deepFreeze({ schemaVersion: 1, executionId: this.id.toString(), tenantId: this.tenantId.toString(), connectorReference: this.connectorReference.toJSON(), capabilityReference: this.capabilityReference.toJSON(), operationKey: this.operationKey, request: this.request.toJSON(), status: this.status, resultMetadata: this.executionResultMetadata, externalEvidence: this.executionExternalEvidence?.toJSON() ?? null, cancellationReason: this.executionCancellationReason, startedAt: this.executionStartedAt, finishedAt: this.executionFinishedAt, evidence: this.executionEvidence.map((item) => item.toJSON()), lineage: this.executionLineage.map((item) => item.toJSON()), version: this.version.value }); }
  public serialize(): string { return stableSerialize(this.toSnapshot() as unknown as JsonObject); }
  private mutate(command: ConnectorAuditInput): void { if (command.reason.trim().length === 0 || command.evidence.length === 0 || command.lineage.length === 0) throw new InvariantViolation("ConnectorExecution mutation requires reason, Evidence and Lineage"); this.executionEvidence = [...this.executionEvidence, ...command.evidence]; this.executionLineage = [...this.executionLineage, ...command.lineage]; this.incrementVersion(); }
  private emit(EventType: new (props: import("./ConnectorEvents.js").ConnectorEventProps) => ConnectorDomainEvent, command: ConnectorAuditInput, payload: JsonObject = {}): void { this.recordEvent(new EventType({ aggregateId: this.id.toString(), tenantId: this.tenantId, occurredAt: command.occurredAt, version: this.version, correlationId: command.correlationId.toString(), ...(command.causationId === undefined ? {} : { causationId: command.causationId.toString() }), evidenceIds: command.evidence.map((item) => item.evidenceId.toString()), lineage: command.lineage.map((item) => item.toJSON()), payload })); }
}
