import { aiWorkforceAssignAgent, aiWorkforceCompleteExecution, aiWorkforceProvisionAgent, aiWorkforceStartExecution } from "@bba/api-client";
import { useQueryClient } from "@tanstack/react-query";
import { useCallback } from "react";
import type { CommandIntent } from "../commands/command-types.js";
import { commandHeaders, executeCommand, requireReady, type GeneratedCommandResponse } from "../commands/execute-command.js";
import { useCommandIntent } from "../commands/use-command-intent.js";
import type { EvidenceInput, LineageInput } from "../missions/mission-commands.js";
import { useBbaSdkRuntime, type ReadySdkRuntime } from "../provider/BbaSdkProvider.js";

export interface CapabilityInput { readonly name: string; readonly scope: string; readonly qualityCriteria?: readonly string[]; readonly limitations?: readonly string[]; }
export interface WorkforceAuditInput { readonly occurredAt: string; readonly evidence: readonly EvidenceInput[]; readonly lineage: readonly LineageInput[]; }
export interface ProvisionAgentInput extends WorkforceAuditInput { readonly agentId: string; readonly name: string; readonly purpose: string; readonly definitionVersion: string; readonly capabilities: readonly CapabilityInput[]; }
export interface AssignAgentInput extends WorkforceAuditInput { readonly agentId: string; readonly workAssignmentId: string; readonly missionId: string; readonly title: string; readonly responsibility: string; readonly authorityId: string; readonly decisionId: string; readonly governanceAssignmentId?: string; readonly requiredCapabilities: readonly CapabilityInput[]; readonly assignmentPolicy?: { readonly exclusive?: boolean; readonly concurrencyKey?: string; readonly maxDurationSeconds?: number }; }
export interface StartExecutionInput extends WorkforceAuditInput { readonly agentId: string; readonly executionId: string; readonly workAssignmentId: string; readonly missionId: string; }
export interface CompleteExecutionInput extends WorkforceAuditInput { readonly executionId: string; readonly result: { readonly output: Readonly<Record<string, string | number | boolean | null>>; readonly uncertainty?: string; readonly limitations?: readonly string[]; readonly provenance?: readonly string[] }; }

type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };
const audit = (value: WorkforceAuditInput): { [key: string]: JsonValue } => ({ occurredAt: value.occurredAt, evidence: value.evidence.map((item) => ({ ...item })), lineage: value.lineage.map((item) => ({ ...item })) });
const capabilities = (values: readonly CapabilityInput[]): JsonValue[] => values.map((value) => ({ name: value.name, scope: value.scope, qualityCriteria: [...(value.qualityCriteria ?? [])], limitations: [...(value.limitations ?? [])] }));
function useWorkforceCommand<T>(operationId: string, ids: (payload: T) => { primaryId: string; relatedId?: string }, invoke: (runtime: ReadySdkRuntime, intent: CommandIntent<T>) => Promise<GeneratedCommandResponse>) { const runtime = useBbaSdkRuntime(); const queryClient = useQueryClient(); const execute = useCallback((intent: CommandIntent<T>) => { const ready = requireReady(runtime.ready); return executeCommand(ready, queryClient, operationId, intent, () => invoke(ready, intent), ids(intent.payload)); }, [ids, invoke, operationId, queryClient, runtime.ready]); return useCommandIntent(execute); }
export function useAiWorkforceProvisionAgentCommand() { return useWorkforceCommand<ProvisionAgentInput>("aiWorkforceProvisionAgent", (p) => ({ primaryId: p.agentId }), (r, i) => aiWorkforceProvisionAgent({ client: r.client, headers: commandHeaders(r, i), body: { data: { agentId: i.payload.agentId, name: i.payload.name, purpose: i.payload.purpose, definitionVersion: i.payload.definitionVersion, capabilities: capabilities(i.payload.capabilities), ...audit(i.payload) }, meta: { reason: i.reason } } })); }
export function useAiWorkforceAssignAgentCommand() { return useWorkforceCommand<AssignAgentInput>("aiWorkforceAssignAgent", (p) => ({ primaryId: p.agentId }), (r, i) => aiWorkforceAssignAgent({ client: r.client, path: { agentId: i.payload.agentId }, headers: commandHeaders(r, i), body: { data: { agentId: i.payload.agentId, workAssignmentId: i.payload.workAssignmentId, missionId: i.payload.missionId, title: i.payload.title, responsibility: i.payload.responsibility, authorityId: i.payload.authorityId, decisionId: i.payload.decisionId, ...(i.payload.governanceAssignmentId === undefined ? {} : { governanceAssignmentId: i.payload.governanceAssignmentId }), requiredCapabilities: capabilities(i.payload.requiredCapabilities), ...(i.payload.assignmentPolicy === undefined ? {} : { assignmentPolicy: { ...i.payload.assignmentPolicy } }), ...audit(i.payload) }, meta: { reason: i.reason } } })); }
export function useAiWorkforceStartExecutionCommand() { return useWorkforceCommand<StartExecutionInput>("aiWorkforceStartExecution", (p) => ({ primaryId: p.agentId, relatedId: p.executionId }), (r, i) => aiWorkforceStartExecution({ client: r.client, path: { agentId: i.payload.agentId }, headers: commandHeaders(r, i), body: { data: { ...i.payload, evidence: i.payload.evidence.map((v) => ({ ...v })), lineage: i.payload.lineage.map((v) => ({ ...v })) }, meta: { reason: i.reason } } })); }
export function useAiWorkforceCompleteExecutionCommand() { return useWorkforceCommand<CompleteExecutionInput>("aiWorkforceCompleteExecution", (p) => ({ primaryId: p.executionId, relatedId: p.executionId }), (r, i) => aiWorkforceCompleteExecution({ client: r.client, path: { executionId: i.payload.executionId }, headers: commandHeaders(r, i), body: { data: { executionId: i.payload.executionId, result: { output: { ...i.payload.result.output }, ...(i.payload.result.uncertainty === undefined ? {} : { uncertainty: i.payload.result.uncertainty }), limitations: [...(i.payload.result.limitations ?? [])], provenance: [...(i.payload.result.provenance ?? [])] }, ...audit(i.payload) }, meta: { reason: i.reason } } })); }
