import { aiWorkforceGetAgent, aiWorkforceGetExecution } from "@bba/api-client";
import { useQuery } from "@tanstack/react-query";
import { BbaSdkError, normalizeSdkError } from "../errors/BbaSdkError.js";
import { useBbaSdkRuntime } from "../provider/BbaSdkProvider.js";
import { agentKeys, executionKeys } from "../query-keys/product-keys.js";

export interface AgentView { readonly id: string; readonly tenantId: string; readonly name: string; readonly purpose: string; readonly definitionVersion: string; readonly lifecycleStatus: string; readonly status: string; readonly availability: string; readonly capabilityCount: number; readonly assignmentCount: number; readonly version: number; }
export interface ExecutionView { readonly id: string; readonly tenantId: string; readonly missionId: string | null; readonly agentId: string | null; readonly workAssignmentId: string | null; readonly status: string; readonly hasResult: boolean; readonly failure: string | null; readonly version: number; }
const publicError = (value: unknown) => value instanceof BbaSdkError ? value : value === null ? undefined : normalizeSdkError(undefined, value);
const referenceId = (value: unknown): string | null => value !== null && typeof value === "object" && !Array.isArray(value) && typeof (value as Record<string, unknown>).id === "string" ? String((value as Record<string, unknown>).id) : null;
export function useAiWorkforceGetAgentQuery(agentId: string) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; const query = useQuery({ queryKey: agentKeys.detail(tenant, agentId), enabled: runtime.ready !== null && agentId.trim().length > 0, queryFn: async (): Promise<AgentView> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await aiWorkforceGetAgent({ client: runtime.ready.client, path: { agentId }, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); const value = response.data.data; return { id: value.agentId, tenantId: value.tenantId, name: value.name, purpose: value.purpose, definitionVersion: value.definitionVersion, lifecycleStatus: value.lifecycleStatus, status: value.status, availability: value.availability, capabilityCount: value.capabilities.length, assignmentCount: value.assignments.length, version: value.version }; } }); return { data: query.data, error: publicError(query.error), isPending: query.isPending }; }
export function useAiWorkforceGetExecutionQuery(executionId: string) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; const query = useQuery({ queryKey: executionKeys.detail(tenant, executionId), enabled: runtime.ready !== null && executionId.trim().length > 0, queryFn: async (): Promise<ExecutionView> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await aiWorkforceGetExecution({ client: runtime.ready.client, path: { executionId }, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); const value = response.data.data; return { id: value.executionId, tenantId: value.tenantId, missionId: referenceId(value.missionReference), agentId: referenceId(value.agentReference), workAssignmentId: referenceId(value.workAssignmentReference), status: value.status, hasResult: value.result !== null, failure: value.failure, version: value.version }; } }); return { data: query.data, error: publicError(query.error), isPending: query.isPending }; }
