export const publisherProductId = "bba.publisher.multiplatform-publication" as const;
export const publisherProductVersion = "1.0.0" as const;
export const publisherChannels = ["blog", "linkedin", "instagram"] as const;
export type PublisherChannelId = typeof publisherChannels[number];
export type PublisherExecutionMode = "DETERMINISTIC" | "BYOK";
export type LlmProvider = "OPENAI" | "ANTHROPIC";
export interface EditorialMaterialReference { readonly id: string; readonly kind: "TEXT" | "URL" | "FILE_METADATA"; readonly title: string; readonly content?: string | undefined; readonly url?: string | undefined; readonly file?: { readonly name: string; readonly mediaType: string; readonly size: number; readonly description: string } | undefined; }
export interface EditorialContext { readonly contextId: string; readonly version: number; readonly title: string; readonly topic: string; readonly objective: string; readonly audience: string; readonly centralMessage: string; readonly tone: string; readonly language: string; readonly callToAction?: string | undefined; readonly requiredFacts: readonly string[]; readonly requiredTerms: readonly string[]; readonly prohibitedClaims: readonly string[]; readonly constraints: readonly string[]; readonly materials: readonly EditorialMaterialReference[]; readonly channels: readonly PublisherChannelId[]; }
export interface EvidenceReference { readonly id: string; readonly materialId: string; readonly locator: string; readonly limitation?: string | undefined; }
export interface EditorialClaim { readonly id: string; readonly statement: string; readonly evidenceIds: readonly string[]; readonly required: boolean; }
export interface EditorialCore { readonly version: number; readonly objective: string; readonly audience: string; readonly centralMessage: string; readonly claims: readonly EditorialClaim[]; readonly evidence: readonly EvidenceReference[]; readonly tone: string; readonly requiredTerms: readonly string[]; readonly prohibitedClaims: readonly string[]; readonly callToAction?: string | undefined; readonly language: string; readonly limitations: readonly string[]; }
export interface PublicationPlanItem { readonly channelId: PublisherChannelId; readonly format: string; readonly purpose: string; readonly sequence: number; readonly adaptation: string; }
export interface PublicationPlan { readonly version: number; readonly strategy: string; readonly items: readonly PublicationPlanItem[]; readonly estimatedExecutionUnits: number; }
export interface VariantContentBlock { readonly id: string; readonly kind: "CLAIM" | "CONTEXT" | "CTA"; readonly text: string; readonly sourceClaimIds: readonly string[]; }
export interface PlatformContentVariant { readonly variantId: string; readonly version: number; readonly channelId: PublisherChannelId; readonly format: string; readonly title?: string | undefined; readonly blocks: readonly VariantContentBlock[]; readonly callToAction?: string | undefined; readonly tags: readonly string[]; readonly metadata: Readonly<Record<string, string | number | readonly string[]>>; readonly editorialCoreVersion: number; }
export interface ConsistencyFinding { readonly code: string; readonly severity: "INFO" | "BLOCKING"; readonly message: string; readonly variantId?: string | undefined; readonly claimId?: string | undefined; }
export interface ConsistencyReport { readonly passed: boolean; readonly findings: readonly ConsistencyFinding[]; readonly reviewedAt: string; }
export interface HumanDecision { readonly decisionId: string; readonly target: "EDITORIAL_CORE" | "EDITORIAL_PACKAGE"; readonly targetVersion: number; readonly outcome: "APPROVED" | "REJECTED" | "REVISION_REQUESTED"; readonly rationale: string; readonly actorReference: string; readonly occurredAt: string; }
export interface AgentDefinition { readonly id: string; readonly role: string; readonly objective: string; readonly allowedTools: readonly string[]; readonly modelPolicy: "balanced-editorial-v1"; readonly requiresHumanReview: boolean; readonly inputSchemaVersion: "1"; readonly outputSchemaVersion: "1"; }
export type PublisherProjectStatus = "CONTEXT_CONFIRMED" | "COMPOSITION_READY" | "RUNNING_CONTEXT_ANALYSIS" | "AWAITING_EDITORIAL_CORE_APPROVAL" | "RUNNING_EDITORIAL_PLAN" | "RUNNING_CHANNEL_ADAPTATION" | "RUNNING_CONSISTENCY_REVIEW" | "AWAITING_PACKAGE_APPROVAL" | "REVISION_REQUESTED" | "REJECTED" | "READY_FOR_DELIVERY" | "FAILED";
export interface RuntimeEvent { readonly eventId: string; readonly type: string; readonly projectId: string; readonly stageId?: string | undefined; readonly agentId?: string | undefined; readonly occurredAt: string; readonly correlationId: string; readonly causationId?: string | undefined; readonly provider?: LlmProvider | "DETERMINISTIC" | undefined; readonly model?: string | undefined; readonly durationMs?: number | undefined; readonly inputTokens?: number | undefined; readonly outputTokens?: number | undefined; readonly message?: string | undefined; }
export interface PlatformReferences { readonly missionId?: string | undefined; readonly knowledgeId?: string | undefined; readonly workflowId?: string | undefined; readonly workflowExecutionId?: string | undefined; readonly assetIds: readonly string[]; readonly reviewId?: string | undefined; readonly publicationId?: string | undefined; readonly transactionIds: readonly string[]; }
export interface EditorialPackage { readonly packageId: string; readonly version: number; readonly projectId: string; readonly editorialCore: EditorialCore; readonly plan: PublicationPlan; readonly variants: readonly PlatformContentVariant[]; readonly consistency: ConsistencyReport; readonly status: "AWAITING_REVIEW" | "READY_FOR_DELIVERY" | "REJECTED"; readonly disclaimer: string; }
export interface PublisherProject { readonly projectId: string; readonly tenantId: string; readonly subject: string; readonly actorReference: string; readonly productId: typeof publisherProductId; readonly productVersion: typeof publisherProductVersion; readonly executionMode: PublisherExecutionMode; readonly provider?: LlmProvider | undefined; readonly status: PublisherProjectStatus; readonly visibleStage: string; readonly context: EditorialContext; readonly editorialCores: readonly EditorialCore[]; readonly plans: readonly PublicationPlan[]; readonly variants: readonly PlatformContentVariant[]; readonly consistencyReports: readonly ConsistencyReport[]; readonly packages: readonly EditorialPackage[]; readonly decisions: readonly HumanDecision[]; readonly events: readonly RuntimeEvent[]; readonly platform: PlatformReferences; readonly currentAgentIndex: number; readonly currentChannelIndex: number; readonly failure?: { readonly code: string; readonly message: string; readonly retryable: boolean; readonly stageId: string } | undefined; readonly createdAt: string; readonly updatedAt: string; }
export interface AgentExecutionMetadata { readonly provider: LlmProvider | "DETERMINISTIC"; readonly model: string; readonly durationMs: number; readonly inputTokens?: number | undefined; readonly outputTokens?: number | undefined; }
export interface AgentExecutionResult<T> { readonly output: T; readonly metadata: AgentExecutionMetadata; }
export interface AgentExecutorPort { execute<T>(definition: AgentDefinition, input: unknown, context: { readonly projectId: string; readonly channelId?: PublisherChannelId | undefined }): Promise<AgentExecutionResult<T>>; }
export interface PublisherProductDefinition { readonly id: typeof publisherProductId; readonly version: typeof publisherProductVersion; readonly family: "BBA Publisher"; readonly categoryId: "AGENCY-SERVICE-CATEGORY-004"; readonly categoryName: "Publication Strategy"; readonly name: "Multiplatform Publication Package"; readonly customerOutcome: string; readonly agents: readonly AgentDefinition[]; readonly channels: readonly PublisherChannelId[]; readonly deliverables: readonly string[]; readonly estimatedExecutionUnits: 60; readonly limitations: readonly string[]; }
