import type { AggregateDto, ApplicationCommandContext, OperationCommandDto, QueryContext, QueryDto } from "../dto/ApplicationContext.js";

export interface MissionCommandApiPort { createMission(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; activateMission(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; renameMission(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; completeMission(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; }
export interface MissionQueryApiPort { getMission(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; }
export interface GovernanceCommandApiPort { createAuthority(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; createDecision(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; approveDecision(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; rejectDecision(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; finalizeDecision(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; }
export interface GovernanceQueryApiPort { getAuthority(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; getDecision(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; }
export interface WorkforceCommandApiPort { provisionAgent(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; assignAgent(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; startExecution(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; completeExecution(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; }
export interface WorkforceQueryApiPort { getAgent(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; getExecution(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; }
export interface AssetCommandApiPort { createAsset(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; produceAsset(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; createVersion(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; archiveAsset(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; supersedeAsset(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; }
export interface AssetQueryApiPort { getAsset(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; listAssets(query: QueryDto, context: QueryContext): Promise<readonly AggregateDto[]>; }
export interface KnowledgePolicyCommandApiPort { createKnowledge(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; curateKnowledge(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; createPolicy(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; createPolicyVersion(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; linkKnowledgeAsset(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; }
export interface KnowledgePolicyQueryApiPort { getKnowledge(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; getPolicy(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; listKnowledge(query: QueryDto, context: QueryContext): Promise<readonly AggregateDto[]>; listPolicies(query: QueryDto, context: QueryContext): Promise<readonly AggregateDto[]>; }
export interface WorkflowCommandApiPort { createWorkflow(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; activateWorkflow(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; archiveWorkflow(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; startWorkflow(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; advanceStage(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; pauseWorkflow(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; resumeWorkflow(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; completeWorkflow(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; cancelWorkflow(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; }
export interface WorkflowQueryApiPort { getWorkflow(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; getExecution(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; }
export interface ReviewCommandApiPort { createReview(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; startReview(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; openSession(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; recordFinding(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; closeSession(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; completeReview(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; archiveReview(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; }
export interface ReviewQueryApiPort { getReview(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; }
export interface PublicationCommandApiPort { createPublication(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; preparePublication(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; authorizePublication(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; recordPublicationOutcome(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; archivePublication(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; }
export interface PublicationQueryApiPort { getPublication(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; }
export interface ConnectorCommandApiPort { registerConnector(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; activateConnector(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; suspendConnector(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; retireConnector(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; createExecution(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; startExecution(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; completeExecution(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; failExecution(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; cancelExecution(command: OperationCommandDto, context: ApplicationCommandContext): Promise<AggregateDto>; }
export interface ConnectorQueryApiPort { getConnector(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; getExecution(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; getExecutionByIdempotency(query: QueryDto, context: QueryContext): Promise<AggregateDto | null>; }
