import { governanceApproveDecision, governanceAssignAuthority, governanceCreateAuthority, governanceCreateDecision, governanceFinalizeDecision, governanceRejectDecision } from "@bba/api-client";
import { useQueryClient } from "@tanstack/react-query";
import { useCallback } from "react";
import type { CommandIntent } from "../commands/command-types.js";
import { commandHeaders, executeCommand, requireReady, type GeneratedCommandResponse } from "../commands/execute-command.js";
import { useCommandIntent } from "../commands/use-command-intent.js";
import type { EvidenceInput, LineageInput } from "../missions/mission-commands.js";
import { useBbaSdkRuntime, type ReadySdkRuntime } from "../provider/BbaSdkProvider.js";

export interface GovernanceAuditInput { readonly occurredAt: string; readonly evidence: readonly EvidenceInput[]; readonly lineage: readonly LineageInput[]; }
export interface AuthorityScopeInput { readonly purpose: string; readonly actions: readonly string[]; readonly constraints?: readonly string[]; }
export interface CreateAuthorityInput extends GovernanceAuditInput { readonly authorityId: string; readonly level: "ADVISORY" | "OPERATIONAL" | "INSTITUTIONAL" | "FINAL"; readonly scope: AuthorityScopeInput; }
export interface AssignAuthorityInput extends GovernanceAuditInput { readonly authorityId: string; readonly expectedVersion: number; readonly assignmentId: string; readonly delegateReference: string; readonly scope: AuthorityScopeInput; readonly period: { readonly startsAt: string; readonly endsAt: string }; }
export interface CreateDecisionInput extends GovernanceAuditInput { readonly decisionId: string; readonly missionId: string; readonly decisionType: string; readonly authorityId: string; readonly assignmentId?: string; }
export interface DecisionMutationInput extends GovernanceAuditInput { readonly decisionId: string; readonly expectedVersion: number; }
export interface DecisionApprovalInput extends DecisionMutationInput { readonly approvalId: string; readonly authorityId: string; readonly assignmentId?: string; readonly outcome?: string; }

type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };
const audit = (value: GovernanceAuditInput): { [key: string]: JsonValue } => ({ occurredAt: value.occurredAt, evidence: value.evidence.map((item) => ({ ...item })), lineage: value.lineage.map((item) => ({ ...item })) });
const scope = (value: AuthorityScopeInput): { [key: string]: JsonValue } => ({ purpose: value.purpose, actions: [...value.actions], ...(value.constraints === undefined ? {} : { constraints: [...value.constraints] }) });
function useGovernanceCommand<T>(operationId: string, primaryId: (payload: T) => string, invoke: (runtime: ReadySdkRuntime, intent: CommandIntent<T>) => Promise<GeneratedCommandResponse>) { const runtime = useBbaSdkRuntime(); const queryClient = useQueryClient(); const execute = useCallback((intent: CommandIntent<T>) => { const ready = requireReady(runtime.ready); return executeCommand(ready, queryClient, operationId, intent, () => invoke(ready, intent), { primaryId: primaryId(intent.payload) }); }, [invoke, operationId, primaryId, queryClient, runtime.ready]); return useCommandIntent(execute); }

export function useGovernanceCreateAuthorityCommand() { return useGovernanceCommand<CreateAuthorityInput>("governanceCreateAuthority", (p) => p.authorityId, (r, i) => governanceCreateAuthority({ client: r.client, headers: commandHeaders(r, i), body: { data: { authorityId: i.payload.authorityId, level: i.payload.level, scope: scope(i.payload.scope), ...audit(i.payload) }, meta: { reason: i.reason } } })); }
export function useGovernanceAssignAuthorityCommand() { return useGovernanceCommand<AssignAuthorityInput>("governanceAssignAuthority", (p) => p.authorityId, (r, i) => governanceAssignAuthority({ client: r.client, path: { authorityId: i.payload.authorityId }, headers: commandHeaders(r, i), body: { data: { authorityId: i.payload.authorityId, expectedVersion: i.payload.expectedVersion, assignmentId: i.payload.assignmentId, delegateReference: i.payload.delegateReference, scope: scope(i.payload.scope), period: { ...i.payload.period }, ...audit(i.payload) }, meta: { reason: i.reason } } })); }
export function useGovernanceCreateDecisionCommand() { return useGovernanceCommand<CreateDecisionInput>("governanceCreateDecision", (p) => p.decisionId, (r, i) => governanceCreateDecision({ client: r.client, headers: commandHeaders(r, i), body: { data: { decisionId: i.payload.decisionId, missionId: i.payload.missionId, decisionType: i.payload.decisionType, authorityId: i.payload.authorityId, ...(i.payload.assignmentId === undefined ? {} : { assignmentId: i.payload.assignmentId }), ...audit(i.payload) }, meta: { reason: i.reason } } })); }
export function useGovernanceApproveDecisionCommand() { return useGovernanceCommand<DecisionApprovalInput>("governanceApproveDecision", (p) => p.decisionId, (r, i) => governanceApproveDecision({ client: r.client, path: { decisionId: i.payload.decisionId }, headers: commandHeaders(r, i), body: { data: { ...i.payload, evidence: i.payload.evidence.map((v) => ({ ...v })), lineage: i.payload.lineage.map((v) => ({ ...v })) }, meta: { reason: i.reason } } })); }
export function useGovernanceRejectDecisionCommand() { return useGovernanceCommand<DecisionApprovalInput>("governanceRejectDecision", (p) => p.decisionId, (r, i) => governanceRejectDecision({ client: r.client, path: { decisionId: i.payload.decisionId }, headers: commandHeaders(r, i), body: { data: { ...i.payload, evidence: i.payload.evidence.map((v) => ({ ...v })), lineage: i.payload.lineage.map((v) => ({ ...v })) }, meta: { reason: i.reason } } })); }
export function useGovernanceFinalizeDecisionCommand() { return useGovernanceCommand<DecisionMutationInput>("governanceFinalizeDecision", (p) => p.decisionId, (r, i) => governanceFinalizeDecision({ client: r.client, path: { decisionId: i.payload.decisionId }, headers: commandHeaders(r, i), body: { data: { ...i.payload, evidence: i.payload.evidence.map((v) => ({ ...v })), lineage: i.payload.lineage.map((v) => ({ ...v })) }, meta: { reason: i.reason } } })); }
