import { governanceGetAuthority, governanceGetDecision } from "@bba/api-client";
import { useQuery } from "@tanstack/react-query";
import { BbaSdkError, normalizeSdkError } from "../errors/BbaSdkError.js";
import { useBbaSdkRuntime } from "../provider/BbaSdkProvider.js";
import { authorityKeys, decisionKeys } from "../query-keys/product-keys.js";

export interface AuthorityView { readonly id: string; readonly tenantId: string; readonly actorReference: string; readonly level: string; readonly status: string; readonly version: number; readonly assignmentCount: number; }
export interface DecisionView { readonly id: string; readonly tenantId: string; readonly missionId: string; readonly decisionType: string; readonly status: string; readonly version: number; readonly authorityId: string; readonly hasApproval: boolean; }
const publicError = (value: unknown) => value instanceof BbaSdkError ? value : value === null ? undefined : normalizeSdkError(undefined, value);
export function useGovernanceGetAuthorityQuery(authorityId: string) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; const query = useQuery({ queryKey: authorityKeys.detail(tenant, authorityId), enabled: runtime.ready !== null && authorityId.trim().length > 0, queryFn: async (): Promise<AuthorityView> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await governanceGetAuthority({ client: runtime.ready.client, path: { authorityId }, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); const value = response.data.data; return { id: value.authorityId, tenantId: value.tenantId, actorReference: value.actorReference, level: value.level, status: value.status, version: value.version, assignmentCount: value.assignments.length }; } }); return { data: query.data, error: publicError(query.error), isPending: query.isPending }; }
export function useGovernanceGetDecisionQuery(decisionId: string) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; const query = useQuery({ queryKey: decisionKeys.detail(tenant, decisionId), enabled: runtime.ready !== null && decisionId.trim().length > 0, queryFn: async (): Promise<DecisionView> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await governanceGetDecision({ client: runtime.ready.client, path: { decisionId }, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); const value = response.data.data; return { id: value.decisionId, tenantId: value.tenantId, missionId: value.missionId, decisionType: value.decisionType, status: value.status, version: value.version, authorityId: value.authorityReference.id, hasApproval: value.approval !== undefined }; } }); return { data: query.data, error: publicError(query.error), isPending: query.isPending }; }
