export type Channel = "BLOG" | "LINKEDIN" | "INSTAGRAM";
export type ProjectScenario = "new-project" | "running-context-analysis" | "awaiting-core-approval" | "core-revision-requested" | "running-content-generation" | "awaiting-package-approval" | "package-blocked" | "package-revision-requested" | "ready-for-delivery" | "recoverable-failure";
export type PublisherProjectStatus = "DRAFT" | "RUNNING" | "AWAITING_USER" | "REVISION_REQUESTED" | "READY_FOR_DELIVERY" | "FAILED" | "REJECTED";
export type PublisherVisibleStage = "CONTEXT_RECEIVED" | "UNDERSTANDING_CONTEXT" | "CORE_APPROVAL" | "PLANNING_STRATEGY" | "PRODUCING_CONTENT" | "VALIDATING_CONSISTENCY" | "PACKAGE_REVIEW" | "DELIVERY";
export type PublisherProjectAction = "START" | "APPROVE_CORE" | "REVISE_CORE" | "REJECT_CORE" | "CONTINUE" | "APPROVE_PACKAGE" | "REVISE_PACKAGE" | "REJECT_PACKAGE" | "RETRY" | "EXPORT" | "EDIT_CONTEXT";
export interface EditorialContextView { readonly version: number; readonly summary: string; readonly objective: string; readonly expectedOutcome: string; readonly audience: string; readonly centralMessage: string; readonly tone: string; readonly language: string; readonly callToAction?: string | undefined; readonly textualMaterials: readonly string[]; readonly urls: readonly string[]; readonly files: readonly { name: string; type: string; size: string; description: string }[]; readonly requiredFacts: readonly string[]; readonly requiredTerms: readonly string[]; readonly prohibitedClaims: readonly string[]; readonly limitations: readonly string[]; readonly notes: string; readonly channels: readonly Channel[]; }
export interface EditorialClaimView { readonly id: string; readonly statement: string; readonly evidenceIds: readonly string[]; readonly source: string; readonly validation: "VALIDATED" | "UNCERTAIN"; }
export interface EditorialCoreView { readonly version: number; readonly interpretedObjective: string; readonly audience: string; readonly centralMessage: string; readonly tone: string; readonly callToAction: string; readonly claims: readonly EditorialClaimView[]; readonly requiredTerms: readonly string[]; readonly prohibitedClaims: readonly string[]; readonly limitations: readonly string[]; readonly uncertainties: readonly string[]; readonly revisionReason?: string | undefined; }
export interface PublicationPlanView { readonly objective: string; readonly sequence: readonly Channel[]; readonly channels: readonly { channel: Channel; purpose: string; audience: string; format: string; approach: string; callToAction: string; relationship: string; limitations: string; agent: string }[]; readonly deliverables: readonly string[]; }
export interface ContentBlockView { readonly id: string; readonly text: string; readonly claimIds: readonly string[]; }
export interface PlatformContentVariantView { readonly channel: Channel; readonly version: number; readonly title: string; readonly subtitle?: string | undefined; readonly blocks: readonly ContentBlockView[]; readonly callToAction: string; readonly tags: readonly string[]; readonly carouselSlides?: readonly string[] | undefined; readonly metadata: readonly string[]; readonly revisionReason?: string | undefined; }
export interface ReviewFindingView { readonly id: string; readonly category: string; readonly severity: "APPROVED" | "WARNING" | "BLOCKING" | "RESOLVED"; readonly channel: Channel | "PACKAGE"; readonly excerpt: string; readonly rule: string; readonly explanation: string; readonly recommendation: string; }
export interface HumanDecisionView { readonly id: string; readonly target: "EDITORIAL_CORE" | "EDITORIAL_PACKAGE"; readonly outcome: "APPROVED" | "REJECTED" | "REVISION_REQUESTED"; readonly rationale: string; readonly responsible: string; readonly occurredAt: string; readonly affectedVersions: readonly string[]; }
export interface AgentParticipationView { readonly id: string; readonly role: string; readonly visibleStage: string; readonly status: "WAITING" | "WORKING" | "COMPLETE" | "FAILED"; readonly simulatedTime: string; readonly resultVersion: number; readonly technicalName: string; }
export interface ProjectTimelineItemView { readonly id: string; readonly label: string; readonly status: "NOT_STARTED" | "RUNNING" | "COMPLETE" | "AWAITING_USER" | "FAILED" | "SUPERSEDED"; readonly occurredAt?: string | undefined; readonly detail: string; }
export interface PackageReviewView { readonly findings: readonly ReviewFindingView[]; readonly categories: readonly { label: string; status: "APPROVED" | "WARNING" | "BLOCKING" }[]; readonly version: number; }
export interface PublisherPackageView { readonly packageVersion: number; readonly approvedAt: string; readonly responsible: string; readonly status: "READY_FOR_DELIVERY"; }
export interface PublisherProjectView { readonly projectId: string; readonly title: string; readonly createdAt: string; readonly updatedAt: string; readonly product: { readonly id: string; readonly version: string; readonly name: string; readonly customerOutcome: string }; readonly visibleStage: PublisherVisibleStage; readonly status: PublisherProjectStatus; readonly scenario: ProjectScenario; readonly editorialContext: EditorialContextView; readonly editorialCores: readonly EditorialCoreView[]; readonly publicationPlan?: PublicationPlanView | undefined; readonly variants: readonly PlatformContentVariantView[]; readonly review?: PackageReviewView | undefined; readonly delivery?: PublisherPackageView | undefined; readonly agents: readonly AgentParticipationView[]; readonly decisions: readonly HumanDecisionView[]; readonly timeline: readonly ProjectTimelineItemView[]; readonly consumption: { readonly estimated: 24; readonly observed: number; readonly label: string }; readonly executionMode: "DETERMINISTIC" | "BYOK"; readonly pendingHumanAction?: string | undefined; readonly failure?: { readonly stage: PublisherVisibleStage; readonly reason: string; readonly retryable: boolean } | undefined; readonly availableActions: readonly PublisherProjectAction[]; }
export interface PublisherDraft { title: string; communicationNeed: string; objective: string; expectedOutcome: string; language: string; audience: string; centralMessage: string; tone: string; callToAction: string; textualMaterials: string; urls: string; fileName: string; fileType: string; fileSize: string; fileDescription: string; requiredFacts: string; requiredTerms: string; prohibitedClaims: string; limitations: string; notes: string; channels: Channel[]; executionMode: "DETERMINISTIC" | "BYOK"; }
export type PublisherProjectEvent = { type: "PROJECT_CREATED" } | { type: "EXECUTION_STARTED" } | { type: "CONTEXT_ANALYSIS_COMPLETED" } | { type: "EDITORIAL_CORE_APPROVED"; rationale?: string | undefined } | { type: "EDITORIAL_CORE_REVISION_REQUESTED"; guidance: string } | { type: "EDITORIAL_CORE_REJECTED"; rationale: string } | { type: "EDITORIAL_PLAN_COMPLETED" } | { type: "CHANNEL_CONTENT_COMPLETED"; channel: Channel } | { type: "CONSISTENCY_REVIEW_COMPLETED" } | { type: "PACKAGE_APPROVED"; rationale?: string | undefined } | { type: "PACKAGE_REVISION_REQUESTED"; guidance: string } | { type: "PACKAGE_REJECTED"; rationale: string } | { type: "STEP_FAILED"; stage: PublisherVisibleStage; reason: string } | { type: "STEP_RETRIED"; stage: PublisherVisibleStage };
