import { contentVariantsV1, contentVariantsV2 } from "./fixtures/content-variants.js";
import { editorialCoreV1, editorialCoreV2 } from "./fixtures/editorial-cores.js";
import { publicationPlan } from "./fixtures/publication-plans.js";
import { approvedReview } from "./fixtures/review-findings.js";
import type { HumanDecisionView, PublisherProjectEvent, PublisherProjectView } from "./models.js";

const now = () => new Date().toISOString();
function decision(target: HumanDecisionView["target"], outcome: HumanDecisionView["outcome"], rationale: string, affectedVersions: string[]): HumanDecisionView { return { id: crypto.randomUUID(), target, outcome, rationale, responsible: "Responsável pelo Projeto", occurredAt: now(), affectedVersions }; }
const stageIndex = { CONTEXT_RECEIVED: 0, UNDERSTANDING_CONTEXT: 1, CORE_APPROVAL: 2, PLANNING_STRATEGY: 3, PRODUCING_CONTENT: 4, VALIDATING_CONSISTENCY: 5, PACKAGE_REVIEW: 6, DELIVERY: 7 } as const;
function update(project: PublisherProjectView, values: Partial<PublisherProjectView>): PublisherProjectView { const visibleStage = values.visibleStage ?? project.visibleStage; const status = values.status ?? project.status; const currentIndex = stageIndex[visibleStage]; const timeline = project.timeline.map((item, index) => ({ ...item, status: index < currentIndex ? "COMPLETE" as const : index > currentIndex ? "NOT_STARTED" as const : status === "FAILED" ? "FAILED" as const : status === "AWAITING_USER" ? "AWAITING_USER" as const : status === "READY_FOR_DELIVERY" ? "COMPLETE" as const : "RUNNING" as const })); return { ...project, ...values, timeline, updatedAt: now() }; }
export function publisherProjectReducer(project: PublisherProjectView, event: PublisherProjectEvent): PublisherProjectView {
  switch (event.type) {
    case "PROJECT_CREATED": return project;
    case "EXECUTION_STARTED": return update(project, { visibleStage: "UNDERSTANDING_CONTEXT", status: "RUNNING", scenario: "running-context-analysis", pendingHumanAction: undefined, availableActions: ["CONTINUE"] });
    case "CONTEXT_ANALYSIS_COMPLETED": return update(project, { visibleStage: "CORE_APPROVAL", status: "AWAITING_USER", scenario: "awaiting-core-approval", editorialCores: [editorialCoreV1], pendingHumanAction: "Aprovar ou solicitar alteração do núcleo editorial", availableActions: ["APPROVE_CORE", "REVISE_CORE", "REJECT_CORE", "EDIT_CONTEXT"] });
    case "EDITORIAL_CORE_APPROVED": return update(project, { visibleStage: "PLANNING_STRATEGY", status: "RUNNING", decisions: [...project.decisions, decision("EDITORIAL_CORE", "APPROVED", event.rationale ?? "Núcleo editorial aprovado", [`Editorial Core v${project.editorialCores.at(-1)?.version ?? 1}`])], pendingHumanAction: undefined, availableActions: ["CONTINUE"] });
    case "EDITORIAL_CORE_REVISION_REQUESTED": return update(project, { visibleStage: "CORE_APPROVAL", status: "AWAITING_USER", scenario: "core-revision-requested", editorialCores: [editorialCoreV1, editorialCoreV2], decisions: [...project.decisions, decision("EDITORIAL_CORE", "REVISION_REQUESTED", event.guidance, ["Editorial Core v1", "Conteúdos posteriores"] )], pendingHumanAction: "Revisar a nova versão do núcleo editorial", availableActions: ["APPROVE_CORE", "REVISE_CORE", "REJECT_CORE"] });
    case "EDITORIAL_CORE_REJECTED": return update(project, { status: "REJECTED", decisions: [...project.decisions, decision("EDITORIAL_CORE", "REJECTED", event.rationale, [`Editorial Core v${project.editorialCores.at(-1)?.version ?? 1}`])], pendingHumanAction: undefined, availableActions: [] });
    case "EDITORIAL_PLAN_COMPLETED": return update(project, { visibleStage: "PRODUCING_CONTENT", status: "RUNNING", publicationPlan, scenario: "running-content-generation", availableActions: ["CONTINUE"] });
    case "CHANNEL_CONTENT_COMPLETED": { const variants = event.channel === "INSTAGRAM" ? contentVariantsV1 : contentVariantsV1.filter((variant) => ["BLOG", "LINKEDIN"].slice(0, event.channel === "BLOG" ? 1 : 2).includes(variant.channel)); return update(project, { variants, visibleStage: event.channel === "INSTAGRAM" ? "VALIDATING_CONSISTENCY" : "PRODUCING_CONTENT", availableActions: ["CONTINUE"] }); }
    case "CONSISTENCY_REVIEW_COMPLETED": return update(project, { visibleStage: "PACKAGE_REVIEW", status: "AWAITING_USER", scenario: "awaiting-package-approval", variants: project.variants.length ? project.variants : contentVariantsV1, review: approvedReview, pendingHumanAction: "Revisar e decidir sobre o Pacote Editorial", availableActions: ["APPROVE_PACKAGE", "REVISE_PACKAGE", "REJECT_PACKAGE"] });
    case "PACKAGE_APPROVED": return update(project, { visibleStage: "DELIVERY", status: "READY_FOR_DELIVERY", scenario: "ready-for-delivery", delivery: { packageVersion: project.review?.version ?? 1, approvedAt: now(), responsible: "Responsável pelo Projeto", status: "READY_FOR_DELIVERY" }, decisions: [...project.decisions, decision("EDITORIAL_PACKAGE", "APPROVED", event.rationale ?? "Pacote aprovado", [`Pacote Editorial v${project.review?.version ?? 1}`])], pendingHumanAction: undefined, availableActions: ["EXPORT"] });
    case "PACKAGE_REVISION_REQUESTED": return update(project, { visibleStage: "PACKAGE_REVIEW", status: "AWAITING_USER", scenario: "package-revision-requested", variants: contentVariantsV2, review: { ...approvedReview, version: 2 }, decisions: [...project.decisions, decision("EDITORIAL_PACKAGE", "REVISION_REQUESTED", event.guidance, ["Blog v1", "LinkedIn v1", "Instagram v1", "Aprovação anterior"] )], pendingHumanAction: "Revisar as três variantes regeneradas", availableActions: ["APPROVE_PACKAGE", "REVISE_PACKAGE", "REJECT_PACKAGE"] });
    case "PACKAGE_REJECTED": return update(project, { status: "REJECTED", decisions: [...project.decisions, decision("EDITORIAL_PACKAGE", "REJECTED", event.rationale, ["Pacote Editorial"] )], pendingHumanAction: undefined, availableActions: [] });
    case "STEP_FAILED": return update(project, { visibleStage: event.stage, status: "FAILED", scenario: "recoverable-failure", failure: { stage: event.stage, reason: event.reason, retryable: true }, pendingHumanAction: "Tentar novamente a etapa", availableActions: ["RETRY"] });
    case "STEP_RETRIED": return update(project, { visibleStage: event.stage, status: "RUNNING", failure: undefined, pendingHumanAction: undefined, availableActions: ["CONTINUE"] });
  }
}
export function visibleStageLabel(stage: PublisherProjectView["visibleStage"]): string { return { CONTEXT_RECEIVED: "Contexto recebido", UNDERSTANDING_CONTEXT: "Compreendendo contexto", CORE_APPROVAL: "Aguardando sua aprovação", PLANNING_STRATEGY: "Planejando estratégia", PRODUCING_CONTENT: "Produzindo conteúdos", VALIDATING_CONSISTENCY: "Validando consistência", PACKAGE_REVIEW: "Pacote disponível para revisão", DELIVERY: "Pronto para entrega" }[stage]; }
export function deriveNextEvent(project: PublisherProjectView): PublisherProjectEvent | undefined { if (project.visibleStage === "CONTEXT_RECEIVED") return { type: "EXECUTION_STARTED" }; if (project.visibleStage === "UNDERSTANDING_CONTEXT") return { type: "CONTEXT_ANALYSIS_COMPLETED" }; if (project.visibleStage === "PLANNING_STRATEGY") return { type: "EDITORIAL_PLAN_COMPLETED" }; if (project.visibleStage === "PRODUCING_CONTENT") { const channels = ["BLOG", "LINKEDIN", "INSTAGRAM"] as const; return { type: "CHANNEL_CONTENT_COMPLETED", channel: channels[Math.min(project.variants.length, 2)]! }; } if (project.visibleStage === "VALIDATING_CONSISTENCY") return { type: "CONSISTENCY_REVIEW_COMPLETED" }; return undefined; }
