import { connectorActivateConnector, connectorCancelExecution, connectorCompleteExecution, connectorCreateExecution, connectorFailExecution, connectorGetConnector, connectorGetConnectorExecution, connectorRegisterConnector, connectorRetireConnector, connectorStartExecution, connectorSuspendConnector } from "@bba/api-client";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useCallback } from "react";
import type { CommandIntent } from "../commands/command-types.js"; import { commandHeaders, executeCommand, requireReady, type GeneratedCommandResponse } from "../commands/execute-command.js"; import { useCommandIntent } from "../commands/use-command-intent.js"; import { BbaSdkError, normalizeSdkError } from "../errors/BbaSdkError.js"; import type { EvidenceInput, LineageInput } from "../missions/mission-commands.js"; import { useBbaSdkRuntime, type ReadySdkRuntime } from "../provider/BbaSdkProvider.js"; import { connectorKeys } from "../query-keys/product-keys.js";
export interface ConnectorAuditInput { readonly occurredAt: string; readonly evidence: readonly EvidenceInput[]; readonly lineage: readonly LineageInput[]; }
export interface RegisterConnectorInput extends ConnectorAuditInput { readonly connectorId: string; readonly name: string; readonly capabilityId: string; readonly capabilityType: "PUBLISH" | "IMPORT" | "EXPORT" | "SEARCH" | "VALIDATION" | "WEBHOOK"; readonly supportedOperationKeys: readonly string[]; }
export interface ConnectorLifecycleInput extends ConnectorAuditInput { readonly connectorId: string; }
export interface CreateConnectorExecutionInput extends ConnectorAuditInput { readonly executionId: string; readonly connectorId: string; readonly capabilityId: string; readonly operationKey: string; readonly requestKey: string; readonly requestIdempotencyKey: string; readonly targetReference: string; readonly requestedAt: string; }
export interface ConnectorExecutionActionInput extends ConnectorAuditInput { readonly executionId: string; readonly cancellationReason?: string; readonly externalEvidence?: { readonly kind: "SUCCESS" | "FAILURE"; readonly providerReference: string; readonly receivedAt: string; readonly externalIdentifier?: string; readonly checksum?: string; readonly failureCode?: string; readonly failureReason?: string; readonly retryable?: boolean }; }
export interface ConnectorView { readonly id: string; readonly tenantId: string; readonly status: string; readonly version: number; } export interface ConnectorExecutionView { readonly id: string; readonly tenantId: string; readonly status: string; readonly version: number; }
type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue }; const audit = (v: ConnectorAuditInput): { [key: string]: JsonValue } => ({ occurredAt: v.occurredAt, evidence: v.evidence.map((x) => ({ ...x })), lineage: v.lineage.map((x) => ({ ...x })) });
function useConnectorCommand<T>(operationId: string, ids: (v: T) => { primaryId: string; relatedId?: string }, invoke: (r: ReadySdkRuntime, i: CommandIntent<T>) => Promise<GeneratedCommandResponse>) { const runtime = useBbaSdkRuntime(); const queryClient = useQueryClient(); const execute = useCallback((intent: CommandIntent<T>) => { const ready = requireReady(runtime.ready); return executeCommand(ready, queryClient, operationId, intent, () => invoke(ready, intent), ids(intent.payload)); }, [ids, invoke, operationId, queryClient, runtime.ready]); return useCommandIntent(execute); }
export function useConnectorRegisterConnectorCommand() { return useConnectorCommand<RegisterConnectorInput>("connectorRegisterConnector", (v) => ({ primaryId: v.connectorId }), (r, i) => connectorRegisterConnector({ client: r.client, headers: commandHeaders(r, i), body: { data: { connectorId: i.payload.connectorId, metadata: { name: i.payload.name }, capabilities: [{ id: i.payload.capabilityId, type: i.payload.capabilityType, supportedOperationKeys: [...i.payload.supportedOperationKeys] }], ...audit(i.payload) }, meta: { reason: i.reason } } })); }
function lifecycle(operationId: string, call: typeof connectorActivateConnector) { return function useLifecycle() { return useConnectorCommand<ConnectorLifecycleInput>(operationId, (v) => ({ primaryId: v.connectorId }), (r, i) => call({ client: r.client, path: { connectorId: i.payload.connectorId }, headers: commandHeaders(r, i), body: { data: { connectorId: i.payload.connectorId, ...audit(i.payload) }, meta: { reason: i.reason } } })); }; }
export const useConnectorActivateConnectorCommand = lifecycle("connectorActivateConnector", connectorActivateConnector); export const useConnectorSuspendConnectorCommand = lifecycle("connectorSuspendConnector", connectorSuspendConnector); export const useConnectorRetireConnectorCommand = lifecycle("connectorRetireConnector", connectorRetireConnector);
export function useConnectorCreateExecutionCommand() { return useConnectorCommand<CreateConnectorExecutionInput>("connectorCreateExecution", (v) => ({ primaryId: v.executionId, relatedId: v.executionId }), (r, i) => connectorCreateExecution({ client: r.client, headers: commandHeaders(r, i), body: { data: { executionId: i.payload.executionId, connectorReference: { id: i.payload.connectorId, tenantId: r.tenantId }, capabilityReference: { id: i.payload.capabilityId, tenantId: r.tenantId }, operationKey: i.payload.operationKey, request: { requestKey: i.payload.requestKey, operationKey: i.payload.operationKey, idempotencyKey: i.payload.requestIdempotencyKey, targetReference: i.payload.targetReference, requestedAt: i.payload.requestedAt, technicalAttributes: {} }, ...audit(i.payload) }, meta: { reason: i.reason } } })); }
function executionAction(operationId: string, call: typeof connectorStartExecution) { return function useAction() { return useConnectorCommand<ConnectorExecutionActionInput>(operationId, (v) => ({ primaryId: v.executionId, relatedId: v.executionId }), (r, i) => call({ client: r.client, path: { executionId: i.payload.executionId }, headers: commandHeaders(r, i), body: { data: { executionId: i.payload.executionId, ...(i.payload.cancellationReason === undefined ? {} : { cancellationReason: i.payload.cancellationReason }), ...(i.payload.externalEvidence === undefined ? {} : { externalEvidence: { ...i.payload.externalEvidence, technicalMetadata: {} } }), ...audit(i.payload) }, meta: { reason: i.reason } } })); }; }
export const useConnectorStartExecutionCommand = executionAction("connectorStartExecution", connectorStartExecution); export const useConnectorCompleteExecutionCommand = executionAction("connectorCompleteExecution", connectorCompleteExecution); export const useConnectorFailExecutionCommand = executionAction("connectorFailExecution", connectorFailExecution); export const useConnectorCancelExecutionCommand = executionAction("connectorCancelExecution", connectorCancelExecution);
const publicError = (v: unknown) => v instanceof BbaSdkError ? v : v === null ? undefined : normalizeSdkError(undefined, v);
export function useConnectorGetConnectorQuery(id: string) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; const query = useQuery({ queryKey: connectorKeys.detail(tenant, id), enabled: runtime.ready !== null && id.trim().length > 0, queryFn: async (): Promise<ConnectorView> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await connectorGetConnector({ client: runtime.ready.client, path: { connectorId: id }, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); const v = response.data.data; return { id: v.connectorId, tenantId: v.tenantId, status: v.status, version: v.version }; } }); return { data: query.data, error: publicError(query.error), isPending: query.isPending }; }
export function useConnectorGetConnectorExecutionQuery(id: string) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; const query = useQuery({ queryKey: connectorKeys.execution(tenant, id), enabled: runtime.ready !== null && id.trim().length > 0, queryFn: async (): Promise<ConnectorExecutionView> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await connectorGetConnectorExecution({ client: runtime.ready.client, path: { executionId: id }, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); const v = response.data.data; return { id: v.executionId, tenantId: v.tenantId, status: v.status, version: v.version }; } }); return { data: query.data, error: publicError(query.error), isPending: query.isPending }; }
