import { knowledgePolicyCreateKnowledge, knowledgePolicyCreatePolicy, knowledgePolicyCreatePolicyVersion, knowledgePolicyCurateKnowledge, knowledgePolicyGetKnowledge, knowledgePolicyGetPolicy, knowledgePolicyLinkKnowledgeAsset, knowledgePolicyListKnowledge, knowledgePolicyListPolicies } from "@bba/api-client";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useCallback } from "react";
import type { CommandIntent } from "../commands/command-types.js";
import { commandHeaders, executeCommand, requireReady, type GeneratedCommandResponse } from "../commands/execute-command.js";
import { useCommandIntent } from "../commands/use-command-intent.js";
import { BbaSdkError, normalizeSdkError } from "../errors/BbaSdkError.js";
import type { EvidenceInput, LineageInput } from "../missions/mission-commands.js";
import { useBbaSdkRuntime, type ReadySdkRuntime } from "../provider/BbaSdkProvider.js";
import { knowledgeKeys, policyKeys, type ProductFilter } from "../query-keys/product-keys.js";

export interface KnowledgePolicyAuditInput { readonly occurredAt: string; readonly evidence: readonly EvidenceInput[]; readonly lineage: readonly LineageInput[]; }
export interface CreateKnowledgeInput extends KnowledgePolicyAuditInput { readonly knowledgeId: string; readonly title: string; readonly summary: string; readonly stewardNote: string; readonly createdAt: string; readonly updatedAt: string; readonly domainArea: string; readonly audience: string; readonly constraints: readonly string[]; readonly assetIds: readonly string[]; readonly assetVersions: readonly { readonly assetId: string; readonly versionId: string }[]; readonly policyIds: readonly string[]; }
export interface CurateKnowledgeInput extends KnowledgePolicyAuditInput { readonly knowledgeId: string; readonly curatorDecisionId: string; }
export interface LinkKnowledgeAssetInput extends KnowledgePolicyAuditInput { readonly knowledgeId: string; readonly assetId: string; readonly relationshipType: "SUPPORTS" | "EXPLAINS" | "SUMMARIZES" | "IMPLEMENTS"; readonly rationale: string; readonly createdAt: string; }
export interface PolicyRuleInput { readonly ruleKey: string; readonly statement: string; readonly obligation: string; readonly applicability: string; readonly priority: number; readonly rationale: string; }
export interface CreatePolicyInput extends KnowledgePolicyAuditInput { readonly policyId: string; readonly title: string; readonly summary: string; readonly scope: string; readonly createdAt: string; readonly updatedAt: string; readonly ownerReference: string; readonly stewardReference: string; readonly authorityId: string; readonly decisionId: string; readonly initialVersionId: string; readonly rule: PolicyRuleInput; }
export interface CreatePolicyVersionInput extends KnowledgePolicyAuditInput { readonly policyId: string; readonly versionId: string; readonly predecessorVersionId: string; readonly authorityId: string; readonly decisionId: string; readonly rule: PolicyRuleInput; }
export interface KnowledgeView { readonly id: string; readonly tenantId: string; readonly status: string; readonly title: string; readonly summary: string; readonly domainArea: string; readonly audience: string; readonly currentRevision: number; readonly version: number; }
export interface PolicyView { readonly id: string; readonly tenantId: string; readonly status: string; readonly title: string; readonly summary: string; readonly scope: string; readonly currentVersionId: string; readonly version: number; }
type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };
const audit = (value: KnowledgePolicyAuditInput): { [key: string]: JsonValue } => ({ occurredAt: value.occurredAt, evidence: value.evidence.map((item) => ({ ...item })), lineage: value.lineage.map((item) => ({ ...item })) });
const refs = (ids: readonly string[], tenantId: string): JsonValue[] => ids.map((id) => ({ id, tenantId })); const ruleSet = (rule: PolicyRuleInput): JsonValue => ({ rules: [{ ...rule }] });
function useKnowledgePolicyCommand<T>(operationId: string, id: (value: T) => string, invoke: (runtime: ReadySdkRuntime, intent: CommandIntent<T>) => Promise<GeneratedCommandResponse>) { const runtime = useBbaSdkRuntime(); const queryClient = useQueryClient(); const execute = useCallback((intent: CommandIntent<T>) => { const ready = requireReady(runtime.ready); return executeCommand(ready, queryClient, operationId, intent, () => invoke(ready, intent), { primaryId: id(intent.payload) }); }, [id, invoke, operationId, queryClient, runtime.ready]); return useCommandIntent(execute); }
export function useKnowledgePolicyCreateKnowledgeCommand() { return useKnowledgePolicyCommand<CreateKnowledgeInput>("knowledgePolicyCreateKnowledge", (v) => v.knowledgeId, (r, i) => knowledgePolicyCreateKnowledge({ client: r.client, headers: commandHeaders(r, i), body: { data: { knowledgeId: i.payload.knowledgeId, metadata: { title: i.payload.title, summary: i.payload.summary, stewardNote: i.payload.stewardNote, createdAt: i.payload.createdAt, updatedAt: i.payload.updatedAt }, scope: { domainArea: i.payload.domainArea, audience: i.payload.audience, constraints: [...i.payload.constraints] }, assetReferences: refs(i.payload.assetIds, r.tenantId), assetVersionReferences: i.payload.assetVersions.map((v) => ({ ...v, tenantId: r.tenantId })), policyReferences: refs(i.payload.policyIds, r.tenantId), ...audit(i.payload) }, meta: { reason: i.reason } } })); }
export function useKnowledgePolicyCurateKnowledgeCommand() { return useKnowledgePolicyCommand<CurateKnowledgeInput>("knowledgePolicyCurateKnowledge", (v) => v.knowledgeId, (r, i) => knowledgePolicyCurateKnowledge({ client: r.client, path: { knowledgeId: i.payload.knowledgeId }, headers: commandHeaders(r, i), body: { data: { knowledgeId: i.payload.knowledgeId, curatorDecisionId: i.payload.curatorDecisionId, ...audit(i.payload) }, meta: { reason: i.reason } } })); }
export function useKnowledgePolicyLinkKnowledgeAssetCommand() { return useKnowledgePolicyCommand<LinkKnowledgeAssetInput>("knowledgePolicyLinkKnowledgeAsset", (v) => v.knowledgeId, (r, i) => knowledgePolicyLinkKnowledgeAsset({ client: r.client, path: { knowledgeId: i.payload.knowledgeId }, headers: commandHeaders(r, i), body: { data: { knowledgeId: i.payload.knowledgeId, relationship: { source: { id: i.payload.knowledgeId, tenantId: r.tenantId }, targetKind: "asset", target: { id: i.payload.assetId, tenantId: r.tenantId }, type: i.payload.relationshipType, rationale: i.payload.rationale, evidence: i.payload.evidence.map((v) => ({ ...v })), lineage: i.payload.lineage.map((v) => ({ ...v })), createdAt: i.payload.createdAt }, ...audit(i.payload) }, meta: { reason: i.reason } } })); }
export function useKnowledgePolicyCreatePolicyCommand() { return useKnowledgePolicyCommand<CreatePolicyInput>("knowledgePolicyCreatePolicy", (v) => v.policyId, (r, i) => knowledgePolicyCreatePolicy({ client: r.client, headers: commandHeaders(r, i), body: { data: { policyId: i.payload.policyId, metadata: { title: i.payload.title, summary: i.payload.summary, scope: i.payload.scope, createdAt: i.payload.createdAt, updatedAt: i.payload.updatedAt }, authorityContext: { ownerReference: { reference: i.payload.ownerReference, tenantId: r.tenantId }, stewardReference: { reference: i.payload.stewardReference, tenantId: r.tenantId }, authorityReference: { id: i.payload.authorityId, tenantId: r.tenantId }, decisionReference: { id: i.payload.decisionId, tenantId: r.tenantId } }, initialVersionId: i.payload.initialVersionId, ruleSet: ruleSet(i.payload.rule), authorityReference: { id: i.payload.authorityId, tenantId: r.tenantId }, decisionReference: { id: i.payload.decisionId, tenantId: r.tenantId }, ...audit(i.payload) }, meta: { reason: i.reason } } })); }
export function useKnowledgePolicyCreatePolicyVersionCommand() { return useKnowledgePolicyCommand<CreatePolicyVersionInput>("knowledgePolicyCreatePolicyVersion", (v) => v.policyId, (r, i) => knowledgePolicyCreatePolicyVersion({ client: r.client, path: { policyId: i.payload.policyId }, headers: commandHeaders(r, i), body: { data: { policyId: i.payload.policyId, versionId: i.payload.versionId, predecessorVersionId: i.payload.predecessorVersionId, ruleSet: ruleSet(i.payload.rule), authorityReference: { id: i.payload.authorityId, tenantId: r.tenantId }, decisionReference: { id: i.payload.decisionId, tenantId: r.tenantId }, ...audit(i.payload) }, meta: { reason: i.reason } } })); }
const publicError = (value: unknown) => value instanceof BbaSdkError ? value : value === null ? undefined : normalizeSdkError(undefined, value);
function usePublicQuery<T>(key: readonly unknown[], enabled: boolean, queryFn: () => Promise<T>) { const query = useQuery({ queryKey: key, enabled, queryFn }); return { data: query.data, error: publicError(query.error), isPending: query.isPending }; }
export function useKnowledgePolicyGetKnowledgeQuery(id: string) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; return usePublicQuery(knowledgeKeys.detail(tenant, id), runtime.ready !== null && id.trim().length > 0, async (): Promise<KnowledgeView> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await knowledgePolicyGetKnowledge({ client: runtime.ready.client, path: { knowledgeId: id }, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); const v = response.data.data; return { id: v.knowledgeId, tenantId: v.tenantId, status: v.status, title: v.title, summary: v.summary, domainArea: v.domainArea, audience: v.audience, currentRevision: v.currentRevision, version: v.version }; }); }
export function useKnowledgePolicyListKnowledgeQuery(filter: ProductFilter = {}) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; return usePublicQuery(knowledgeKeys.list(tenant, filter), runtime.ready !== null, async (): Promise<readonly KnowledgeView[]> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await knowledgePolicyListKnowledge({ client: runtime.ready.client, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); return response.data.data.map((v) => ({ id: v.knowledgeId, tenantId: v.tenantId, status: v.status, title: v.title, summary: v.summary, domainArea: v.domainArea, audience: v.audience, currentRevision: v.currentRevision, version: v.version })); }); }
export function useKnowledgePolicyGetPolicyQuery(id: string) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; return usePublicQuery(policyKeys.detail(tenant, id), runtime.ready !== null && id.trim().length > 0, async (): Promise<PolicyView> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await knowledgePolicyGetPolicy({ client: runtime.ready.client, path: { policyId: id }, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); const v = response.data.data; return { id: v.policyId, tenantId: v.tenantId, status: v.status, title: v.title, summary: v.summary, scope: v.scope, currentVersionId: v.currentVersionId, version: v.version }; }); }
export function useKnowledgePolicyListPoliciesQuery(filter: ProductFilter = {}) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; return usePublicQuery(policyKeys.list(tenant, filter), runtime.ready !== null, async (): Promise<readonly PolicyView[]> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await knowledgePolicyListPolicies({ client: runtime.ready.client, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); return response.data.data.map((v) => ({ id: v.policyId, tenantId: v.tenantId, status: v.status, title: v.title, summary: v.summary, scope: v.scope, currentVersionId: v.currentVersionId, version: v.version })); }); }
