import { CausationId, CorrelationId } from "../../shared/common/index.js";
import type { JsonObject } from "../../shared/common/serialization.js";
import { EvidenceReference } from "../../shared/evidence/EvidenceReference.js";
import { AssetId, AssetVersionId, EvidenceId, MissionId, TenantId } from "../../shared/identity/index.js";
import { LineageReference, type LineageRelationship } from "../../shared/lineage/LineageReference.js";
import { AssetReference, AuthorityReference, DecisionReference, InstitutionalActorReference, MissionReference } from "../../shared/references/index.js";
import { ApplicationError } from "../errors/ApplicationError.js";
import type { ApplicationCommandContext, AssetCommandResponseDto, AssetDto, AssetSummaryDto, CreateAssetRequestDto, GetAssetRequestDto, ListAssetsRequestDto, QueryContext, RegisterAssetRequestDto, RetireAssetRequestDto } from "../dto/ApplicationContext.js";
import type { TransactionalRepositorySession, ReadRepositorySession } from "../services/TransactionalRepositorySession.js";
import type { ValidatedCommandContext } from "../services/ApplicationCommandRunner.js";
import type { CommandBindingDescriptor, QueryBindingDescriptor } from "./ApplicationBindingTypes.js";
import { Asset } from "../../modules/institutional-assets/domain/Asset.js";
import { AssetAuthorityContext } from "../../modules/institutional-assets/domain/AssetAuthorityContext.js";
import { AssetClassification, AssetTag, type AssetCategory, type Sensitivity } from "../../modules/institutional-assets/domain/AssetClassification.js";
import { AssetMetadata } from "../../modules/institutional-assets/domain/AssetMetadata.js";
import { CanonicalContent } from "../../modules/institutional-assets/domain/CanonicalContent.js";
import { archiveAsset, createAsset } from "../../modules/institutional-assets/application/AssetUseCases.js";

type JsonRecord = Record<string, unknown>;
export type AssetRepositories = Pick<TransactionalRepositorySession, "asset">;
export type ReadAssetRepositories = Pick<ReadRepositorySession, "asset">;

function object(value: unknown, field: string): JsonRecord { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new ApplicationError("VALIDATION_FAILED", `${field} must be an object`, { field }); return value as JsonRecord; }
function required(value: unknown, field: string): string { if (typeof value !== "string" || value.trim() === "") throw new ApplicationError("VALIDATION_FAILED", `${field} is required`, { field }); return value; }
function array(value: unknown, field: string): readonly JsonRecord[] { if (!Array.isArray(value)) throw new ApplicationError("VALIDATION_FAILED", `${field} must be an array`, { field }); return value.map((item) => object(item, field)); }
function payload(command: { readonly payload: JsonObject }): JsonRecord { return object(command.payload, "payload"); }
function target(command: { readonly targetId?: string; readonly payload: JsonObject }, field: string): string { return required(command.targetId ?? payload(command)[field], field); }
function evidence(value: unknown): readonly EvidenceReference[] { return array(value, "evidence").map((item) => new EvidenceReference({ evidenceId: EvidenceId.from(required(item.evidenceId, "evidence.evidenceId")), source: required(item.source, "evidence.source"), type: required(item.type, "evidence.type"), capturedAt: required(item.capturedAt, "evidence.capturedAt"), ...(typeof item.locator === "string" ? { locator: item.locator } : {}), ...(typeof item.limitation === "string" ? { limitation: item.limitation } : {}) })); }
function lineage(value: unknown): readonly LineageReference[] { return array(value, "lineage").map((item) => new LineageReference({ sourceId: required(item.sourceId, "lineage.sourceId"), targetId: required(item.targetId, "lineage.targetId"), relationship: required(item.relationship, "lineage.relationship") as LineageRelationship, declaredAt: required(item.declaredAt, "lineage.declaredAt"), ...(typeof item.reason === "string" ? { reason: item.reason } : {}) })); }
function audit(command: { readonly reason: string; readonly payload: JsonObject }, context: ValidatedCommandContext) { const data = payload(command); return { reason: command.reason, occurredAt: required(data.occurredAt, "occurredAt"), correlationId: CorrelationId.from(context.correlationId), ...(context.causationId === undefined ? {} : { causationId: CausationId.from(context.causationId) }), evidence: evidence(data.evidence), lineage: lineage(data.lineage) }; }
function validateCommon(command: { readonly payload: JsonObject }): void { const data = payload(command); required(data.occurredAt, "occurredAt"); evidence(data.evidence); lineage(data.lineage); }
function mapTarget<T extends { readonly targetId?: string; readonly payload: JsonObject }>(request: T, field: string): T { const value = payload(request)[field]; return request.targetId === undefined && typeof value === "string" ? { ...request, targetId: value } : request; }
function validateCreate(command: CreateAssetRequestDto | RegisterAssetRequestDto): void { const data = payload(command); target(command, "assetId"); validateCommon(command); required(data.initialVersionId, "initialVersionId"); required(data.missionId, "missionId"); required(data.authorityDecisionId, "authorityDecisionId"); object(data.metadata, "metadata"); object(data.classification, "classification"); object(data.authorityContext, "authorityContext"); object(data.content, "content"); }
function validateRetire(command: RetireAssetRequestDto): void { target(command, "assetId"); validateCommon(command); required(payload(command).authorityId, "authorityId"); required(payload(command).decisionId, "decisionId"); }
function validateQuery(query: GetAssetRequestDto | ListAssetsRequestDto): void { if ("targetId" in query && query.targetId !== undefined && query.targetId.trim() === "") throw new ApplicationError("VALIDATION_FAILED", "targetId cannot be empty", {}); }
function actor(value: unknown, field: string, tenantId: TenantId): InstitutionalActorReference { const item = object(value, field); return new InstitutionalActorReference(required(item.reference, `${field}.reference`), TenantId.from(typeof item.tenantId === "string" ? item.tenantId : tenantId.toString())); }
function createCommand(command: CreateAssetRequestDto | RegisterAssetRequestDto, context: ValidatedCommandContext) { const data = payload(command); const tenantId = TenantId.from(context.tenantId); const metadata = object(data.metadata, "metadata"); const classification = object(data.classification, "classification"); const authority = object(data.authorityContext, "authorityContext"); const content = object(data.content, "content"); return { assetId: AssetId.from(target(command, "assetId")), tenantId, missionReference: new MissionReference(MissionId.from(required(data.missionId, "missionId")), tenantId), metadata: new AssetMetadata({ title: required(metadata.title, "metadata.title"), summary: required(metadata.summary, "metadata.summary"), purpose: required(metadata.purpose, "metadata.purpose"), createdAt: required(metadata.createdAt, "metadata.createdAt"), updatedAt: required(metadata.updatedAt, "metadata.updatedAt") }), classification: new AssetClassification({ primaryCategory: required(classification.primaryCategory, "classification.primaryCategory") as AssetCategory, secondaryCategories: Array.isArray(classification.secondaryCategories) ? classification.secondaryCategories.map(String) as AssetCategory[] : [], sensitivity: required(classification.sensitivity, "classification.sensitivity") as Sensitivity, tags: Array.isArray(classification.tags) ? classification.tags.map((tag) => new AssetTag(String(tag))) : [] }), authorityContext: new AssetAuthorityContext({ ownerReference: actor(authority.ownerReference, "authorityContext.ownerReference", tenantId), stewardReference: actor(authority.stewardReference, "authorityContext.stewardReference", tenantId), custodianReference: actor(authority.custodianReference, "authorityContext.custodianReference", tenantId), authorReferences: array(authority.authorReferences, "authorityContext.authorReferences").map((item) => actor(item, "authorityContext.authorReferences", tenantId)), ...(typeof authority.decisionReference === "object" && authority.decisionReference !== null ? { decisionReference: DecisionReference.fromJSON(object(authority.decisionReference, "authorityContext.decisionReference") as { id: string; tenantId: string }) } : {}) }), initialVersionId: AssetVersionId.from(required(data.initialVersionId, "initialVersionId")), content: new CanonicalContent({ meaning: required(content.meaning, "content.meaning"), data: object(content.data, "content.data") as JsonObject, ...(typeof content.language === "string" ? { language: content.language } : {}) }), authorityDecisionReference: DecisionReference.fromJSON({ id: required(data.authorityDecisionId, "authorityDecisionId"), tenantId: context.tenantId }), ...audit(command, context) }; }
function retireCommand(command: RetireAssetRequestDto, context: ValidatedCommandContext) { const data = payload(command); return { authorityReference: AuthorityReference.fromJSON({ id: required(data.authorityId, "authorityId"), tenantId: context.tenantId }), decisionReference: DecisionReference.fromJSON({ id: required(data.decisionId, "decisionId"), tenantId: context.tenantId }), ...audit(command, context) }; }
function assetDto(asset: Asset): AssetDto { return Object.freeze({ assetId: asset.id.toString(), tenantId: asset.tenantId.toString(), missionReference: { id: asset.missionReference.id.toString(), tenantId: asset.missionReference.tenantId.toString() }, status: asset.status, currentVersionId: asset.currentVersionId.toString(), versionCount: asset.versions.length, version: asset.version.value }); }
function assetSummaryDto(asset: Asset): AssetSummaryDto { return Object.freeze({ assetId: asset.id.toString(), tenantId: asset.tenantId.toString(), status: asset.status, currentVersionId: asset.currentVersionId.toString(), version: asset.version.value }); }

export interface InstitutionalAssetsBindings { readonly createAsset: CommandBindingDescriptor<CreateAssetRequestDto, AssetCommandResponseDto, AssetCommandResponseDto, AssetRepositories>; readonly registerAsset: CommandBindingDescriptor<RegisterAssetRequestDto, AssetCommandResponseDto, AssetCommandResponseDto, AssetRepositories>; readonly retireAsset: CommandBindingDescriptor<RetireAssetRequestDto, AssetCommandResponseDto, AssetCommandResponseDto, AssetRepositories>; readonly getAsset: QueryBindingDescriptor<GetAssetRequestDto, Asset | null, AssetDto | null, ReadAssetRepositories>; readonly listAssets: QueryBindingDescriptor<ListAssetsRequestDto, readonly Asset[], readonly AssetSummaryDto[], ReadAssetRepositories>; }

export const institutionalAssetsBindings: InstitutionalAssetsBindings = Object.freeze({
  createAsset: { boundedContext: "institutional-assets", exportName: "createAsset", operationName: "CreateAsset", apiPortMethod: "createAsset", repositoryView: { repositories: ["asset"] }, useCaseExport: "createAsset", requestMapper: (request: CreateAssetRequestDto) => mapTarget(request, "assetId"), validator: validateCreate, repositorySelector: (repositories: TransactionalRepositorySession): AssetRepositories => Object.freeze({ asset: repositories.asset }), confirmedResourceType: "Asset", handler: async (command: CreateAssetRequestDto, context: ValidatedCommandContext, repositories: AssetRepositories): Promise<AssetCommandResponseDto> => { await createAsset(repositories.asset, createCommand(command, context)); return Object.freeze({ transactionId: context.transactionId, status: "COMMITTED", resourceReferences: Object.freeze([{ resourceType: "Asset", resourceId: target(command, "assetId") }]) }); }, responseMapper: (result: AssetCommandResponseDto) => result },
  registerAsset: { boundedContext: "institutional-assets", exportName: "createAsset", operationName: "RegisterAsset", apiPortMethod: "registerAsset", repositoryView: { repositories: ["asset"] }, useCaseExport: "createAsset (alias)", requestMapper: (request: RegisterAssetRequestDto) => mapTarget(request, "assetId"), validator: validateCreate, repositorySelector: (repositories: TransactionalRepositorySession): AssetRepositories => Object.freeze({ asset: repositories.asset }), confirmedResourceType: "Asset", handler: async (command: RegisterAssetRequestDto, context: ValidatedCommandContext, repositories: AssetRepositories): Promise<AssetCommandResponseDto> => { await createAsset(repositories.asset, createCommand(command, context)); return Object.freeze({ transactionId: context.transactionId, status: "COMMITTED", resourceReferences: Object.freeze([{ resourceType: "Asset", resourceId: target(command, "assetId") }]) }); }, responseMapper: (result: AssetCommandResponseDto) => result },
  retireAsset: { boundedContext: "institutional-assets", exportName: "archiveAsset", operationName: "RetireAsset", apiPortMethod: "retireAsset", repositoryView: { repositories: ["asset"] }, useCaseExport: "archiveAsset", requestMapper: (request: RetireAssetRequestDto) => mapTarget(request, "assetId"), validator: validateRetire, repositorySelector: (repositories: TransactionalRepositorySession): AssetRepositories => Object.freeze({ asset: repositories.asset }), confirmedResourceType: "Asset", handler: async (command: RetireAssetRequestDto, context: ValidatedCommandContext, repositories: AssetRepositories): Promise<AssetCommandResponseDto> => { const assetId = AssetId.from(target(command, "assetId")); await archiveAsset(repositories.asset, TenantId.from(context.tenantId), assetId, retireCommand(command, context)); return Object.freeze({ transactionId: context.transactionId, status: "COMMITTED", resourceReferences: Object.freeze([{ resourceType: "Asset", resourceId: assetId.toString() }]) }); }, responseMapper: (result: AssetCommandResponseDto) => result },
  getAsset: { boundedContext: "institutional-assets", exportName: "AssetRepository.findById", operationName: "getAsset", apiPortMethod: "getAsset", repositoryView: { repositories: ["asset"] }, requestMapper: (request: GetAssetRequestDto) => request, validator: validateQuery, repositorySelector: (repositories: ReadRepositorySession): ReadAssetRepositories => Object.freeze({ asset: repositories.asset }), handler: async (query: GetAssetRequestDto, context: QueryContext, repositories: ReadAssetRepositories): Promise<Asset | null> => query.targetId === undefined ? null : repositories.asset.findById(TenantId.from(context.tenantId), AssetId.from(query.targetId)), responseMapper: (result: Asset | null) => result === null ? null : assetDto(result) },
  listAssets: { boundedContext: "institutional-assets", exportName: "AssetRepository.listByTenant", operationName: "listAssets", apiPortMethod: "listAssets", repositoryView: { repositories: ["asset"] }, requestMapper: (request: ListAssetsRequestDto) => request, validator: validateQuery, repositorySelector: (repositories: ReadRepositorySession): ReadAssetRepositories => Object.freeze({ asset: repositories.asset }), handler: async (_query: ListAssetsRequestDto, context: QueryContext, repositories: ReadAssetRepositories): Promise<readonly Asset[]> => repositories.asset.listByTenant(TenantId.from(context.tenantId)), responseMapper: (result: readonly Asset[]) => result.map(assetSummaryDto) }
}) as InstitutionalAssetsBindings;
