import type { JsonObject } from "../../shared/common/serialization.js";
import { CausationId, CorrelationId } from "../../shared/common/index.js";
import { EvidenceReference } from "../../shared/evidence/EvidenceReference.js";
import { EvidenceId, KnowledgeId, PolicyId, PolicyVersionId, TenantId } from "../../shared/identity/index.js";
import { LineageReference, type LineageRelationship } from "../../shared/lineage/LineageReference.js";
import { AssetReference, AssetVersionReference, AuthorityReference, DecisionReference, KnowledgeReference, PolicyReference } from "../../shared/references/index.js";
import { ApplicationError } from "../errors/ApplicationError.js";
import type { ApplicationCommandContext, CommittedOperationResultDto, CreateKnowledgeRequestDto, CreatePolicyRequestDto, CreatePolicyVersionRequestDto, CurateKnowledgeRequestDto, GetKnowledgeRequestDto, GetPolicyRequestDto, KnowledgeDto, LinkKnowledgeAssetRequestDto, ListKnowledgeRequestDto, ListPoliciesRequestDto, PolicyDto, QueryContext } from "../dto/ApplicationContext.js";
import type { ReadRepositorySession, TransactionalRepositorySession } from "../services/TransactionalRepositorySession.js";
import type { ValidatedCommandContext } from "../services/ApplicationCommandRunner.js";
import { createKnowledge, createPolicy, createPolicyVersion, curateKnowledge, linkKnowledgeAsset } from "../../modules/knowledge-policy/application/index.js";
import { Knowledge } from "../../modules/knowledge-policy/domain/Knowledge.js";
import { KnowledgeMetadata } from "../../modules/knowledge-policy/domain/KnowledgeMetadata.js";
import { KnowledgeScope } from "../../modules/knowledge-policy/domain/KnowledgeScope.js";
import { KnowledgeRelationship } from "../../modules/knowledge-policy/domain/KnowledgeRelationship.js";
import { Policy } from "../../modules/knowledge-policy/domain/Policy.js";
import { PolicyAuthorityContext } from "../../modules/knowledge-policy/domain/PolicyAuthorityContext.js";
import { PolicyMetadata } from "../../modules/knowledge-policy/domain/PolicyMetadata.js";
import { PolicyRuleSet } from "../../modules/knowledge-policy/domain/PolicyRuleSet.js";
import type { KnowledgeReferenceValidationPort } from "../../modules/knowledge-policy/ports/KnowledgeReferenceValidationPort.js";
import type { CommandBindingDescriptor, QueryBindingDescriptor } from "./ApplicationBindingTypes.js";

type R = Record<string, unknown>; type Repositories = Pick<TransactionalRepositorySession, "knowledge" | "policy">; type Reads = Pick<ReadRepositorySession, "knowledge" | "policy">;
function object(value: unknown, field: string): R { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new ApplicationError("VALIDATION_FAILED", `${field} must be an object`, { field }); return value as R; }
function required(value: unknown, field: string): string { if (typeof value !== "string" || value.trim() === "") throw new ApplicationError("VALIDATION_FAILED", `${field} is required`, { field }); return value; }
function data(command: { readonly payload: JsonObject }): R { return object(command.payload, "payload"); }
function target(command: { readonly targetId?: string; readonly payload: JsonObject }, field: string): string { return required(command.targetId ?? data(command)[field], field); }
function audit(command: { readonly reason: string; readonly payload: JsonObject }, context: ValidatedCommandContext) { const p = data(command); const ev = Array.isArray(p.evidence) ? p.evidence.map((x) => object(x, "evidence")).map((x) => new EvidenceReference({ evidenceId: EvidenceId.from(required(x.evidenceId, "evidence.evidenceId")), source: required(x.source, "evidence.source"), type: required(x.type, "evidence.type"), capturedAt: required(x.capturedAt, "evidence.capturedAt") })) : []; const lin = Array.isArray(p.lineage) ? p.lineage.map((x) => object(x, "lineage")).map((x) => new LineageReference({ sourceId: required(x.sourceId, "lineage.sourceId"), targetId: required(x.targetId, "lineage.targetId"), relationship: required(x.relationship, "lineage.relationship") as LineageRelationship, declaredAt: required(x.declaredAt, "lineage.declaredAt") })) : []; if (ev.length === 0 || lin.length === 0) throw new ApplicationError("VALIDATION_FAILED", "evidence and lineage are required", {}); return { reason: command.reason, occurredAt: required(p.occurredAt, "occurredAt"), correlationId: CorrelationId.from(context.correlationId), ...(context.causationId === undefined ? {} : { causationId: CausationId.from(context.causationId) }), evidence: ev, lineage: lin }; }
function mapTarget<T extends { readonly targetId?: string; readonly payload: JsonObject }>(r: T, field: string): T { return r.targetId === undefined ? { ...r, targetId: target(r, field) } : r; }
function validate(command: { readonly payload: JsonObject }, field: string): void { target(command, field); const p = data(command); required(p.occurredAt, "occurredAt"); }
function refs(value: unknown, field: string, map: (x: R) => unknown): readonly unknown[] { if (!Array.isArray(value)) throw new ApplicationError("VALIDATION_FAILED", `${field} must be an array`, { field }); return value.map((x) => map(object(x, field))); }
function createKnowledgeCommand(c: CreateKnowledgeRequestDto, x: ValidatedCommandContext) { const p = data(c); return { knowledgeId: KnowledgeId.from(target(c, "knowledgeId")), tenantId: TenantId.from(x.tenantId), metadata: KnowledgeMetadata.fromJSON(object(p.metadata, "metadata") as JsonObject), scope: KnowledgeScope.fromJSON(object(p.scope, "scope") as JsonObject), assetReferences: refs(p.assetReferences, "assetReferences", (v) => AssetReference.fromJSON(v as { id: string; tenantId: string })) as AssetReference[], assetVersionReferences: refs(p.assetVersionReferences, "assetVersionReferences", (v) => AssetVersionReference.fromJSON(v as { assetId: string; versionId: string; tenantId: string })) as AssetVersionReference[], policyReferences: refs(p.policyReferences ?? [], "policyReferences", (v) => PolicyReference.fromJSON(v as { id: string; tenantId: string })) as PolicyReference[], ...audit(c, x) } as never; }
function committed(id: string, type: string, resourceId: string): CommittedOperationResultDto { return Object.freeze({ transactionId: id, status: "COMMITTED", resourceReferences: Object.freeze([{ resourceType: type, resourceId }]) }); }
function knowledgeDto(v: Knowledge): KnowledgeDto { return Object.freeze({ knowledgeId: v.id.toString(), tenantId: v.tenantId.toString(), status: v.status, title: v.metadata.title, summary: v.metadata.summary, domainArea: v.scope.domainArea, audience: v.scope.audience, currentRevision: v.currentRevision.value, version: v.version.value }); }
function policyDto(v: Policy): PolicyDto { return Object.freeze({ policyId: v.id.toString(), tenantId: v.tenantId.toString(), status: v.status, title: v.metadata.title, summary: v.metadata.summary, scope: v.metadata.scope, currentVersionId: v.currentVersionId.toString(), version: v.version.value }); }

export interface KnowledgePolicyBindings { readonly createKnowledge: CommandBindingDescriptor<CreateKnowledgeRequestDto, CommittedOperationResultDto, CommittedOperationResultDto, Repositories>; readonly curateKnowledge: CommandBindingDescriptor<CurateKnowledgeRequestDto, CommittedOperationResultDto, CommittedOperationResultDto, Repositories>; readonly linkKnowledgeAsset: CommandBindingDescriptor<LinkKnowledgeAssetRequestDto, CommittedOperationResultDto, CommittedOperationResultDto, Repositories>; readonly createPolicy: CommandBindingDescriptor<CreatePolicyRequestDto, CommittedOperationResultDto, CommittedOperationResultDto, Repositories>; readonly createPolicyVersion: CommandBindingDescriptor<CreatePolicyVersionRequestDto, CommittedOperationResultDto, CommittedOperationResultDto, Repositories>; readonly getKnowledge: QueryBindingDescriptor<GetKnowledgeRequestDto, Knowledge | null, KnowledgeDto | null, Reads>; readonly listKnowledge: QueryBindingDescriptor<ListKnowledgeRequestDto, readonly Knowledge[], readonly KnowledgeDto[], Reads>; readonly getPolicy: QueryBindingDescriptor<GetPolicyRequestDto, Policy | null, PolicyDto | null, Reads>; readonly listPolicies: QueryBindingDescriptor<ListPoliciesRequestDto, readonly Policy[], readonly PolicyDto[], Reads>; }
function base<T extends { readonly targetId?: string; readonly payload: JsonObject }>(request: T, field: string): T { return mapTarget(request, field); }
function commandBindings(validation: KnowledgeReferenceValidationPort): KnowledgePolicyBindings { const select = (r: TransactionalRepositorySession): Repositories => Object.freeze({ knowledge: r.knowledge, policy: r.policy }); const read = (r: ReadRepositorySession): Reads => Object.freeze({ knowledge: r.knowledge, policy: r.policy }); const common = { repositoryView: { repositories: ["knowledge", "policy"] }, repositorySelector: select } as const;
  const createKnowledgeBinding = { boundedContext: "knowledge-policy", exportName: "createKnowledge", operationName: "CreateKnowledge", apiPortMethod: "createKnowledge", ...common, useCaseExport: "createKnowledge", requestMapper: (r: CreateKnowledgeRequestDto) => base(r, "knowledgeId"), validator: (r: CreateKnowledgeRequestDto) => validate(r, "knowledgeId"), confirmedResourceType: "Knowledge", handler: async (r: CreateKnowledgeRequestDto, c: ValidatedCommandContext, repos: Repositories) => { await createKnowledge(repos.knowledge, validation, createKnowledgeCommand(r, c)); return committed(c.transactionId, "Knowledge", target(r, "knowledgeId")); }, responseMapper: (r: CommittedOperationResultDto) => r } as unknown as KnowledgePolicyBindings["createKnowledge"];
  const simple = (operationName: string, method: "curateKnowledge" | "linkKnowledgeAsset" | "createPolicy" | "createPolicyVersion", field: string) => ({ boundedContext: "knowledge-policy", exportName: method, operationName, apiPortMethod: method, ...common, useCaseExport: method, requestMapper: (r: never) => base(r, field), validator: (r: never) => validate(r, field), confirmedResourceType: method === "createPolicy" || method === "createPolicyVersion" ? "Policy" : "Knowledge", handler: async (r: never, c: ValidatedCommandContext, repos: Repositories) => { const p = data(r); const a = audit(r, c); if (method === "curateKnowledge") await curateKnowledge(repos.knowledge, TenantId.from(c.tenantId), KnowledgeId.from(target(r, field)), { ...a, curatorReference: DecisionReference.fromJSON({ id: required(p.curatorDecisionId, "curatorDecisionId"), tenantId: c.tenantId }) } as never); else if (method === "linkKnowledgeAsset") await linkKnowledgeAsset(repos.knowledge, validation, TenantId.from(c.tenantId), KnowledgeId.from(target(r, field)), { ...a, relationship: KnowledgeRelationship.fromJSON(object(p.relationship, "relationship") as JsonObject) }); else if (method === "createPolicy") await createPolicy(repos.policy, { ...a, policyId: PolicyId.from(target(r, field)), tenantId: TenantId.from(c.tenantId), metadata: PolicyMetadata.fromJSON(object(p.metadata, "metadata") as JsonObject), authorityContext: PolicyAuthorityContext.fromJSON(object(p.authorityContext, "authorityContext") as JsonObject), initialVersionId: PolicyVersionId.from(required(p.initialVersionId, "initialVersionId")), ruleSet: PolicyRuleSet.fromJSON(object(p.ruleSet, "ruleSet") as JsonObject), authorityReference: AuthorityReference.fromJSON(object(p.authorityReference, "authorityReference") as { id: string; tenantId: string }), decisionReference: DecisionReference.fromJSON(object(p.decisionReference, "decisionReference") as { id: string; tenantId: string }) } as never); else await createPolicyVersion(repos.policy, TenantId.from(c.tenantId), PolicyId.from(target(r, field)), { ...a, versionId: PolicyVersionId.from(required(p.versionId, "versionId")), predecessorVersionId: PolicyVersionId.from(required(p.predecessorVersionId, "predecessorVersionId")), ruleSet: PolicyRuleSet.fromJSON(object(p.ruleSet, "ruleSet") as JsonObject), authorityReference: AuthorityReference.fromJSON(object(p.authorityReference, "authorityReference") as { id: string; tenantId: string }), decisionReference: DecisionReference.fromJSON(object(p.decisionReference, "decisionReference") as { id: string; tenantId: string }) } as never); return committed(c.transactionId, method === "createPolicy" || method === "createPolicyVersion" ? "Policy" : "Knowledge", target(r, field)); }, responseMapper: (r: CommittedOperationResultDto) => r }) as never;
  return { createKnowledge: createKnowledgeBinding, curateKnowledge: simple("CurateKnowledge", "curateKnowledge", "knowledgeId"), linkKnowledgeAsset: simple("LinkKnowledgeAsset", "linkKnowledgeAsset", "knowledgeId"), createPolicy: simple("CreatePolicy", "createPolicy", "policyId"), createPolicyVersion: simple("CreatePolicyVersion", "createPolicyVersion", "policyId"), getKnowledge: { boundedContext: "knowledge-policy", exportName: "KnowledgeRepository.findById", operationName: "getKnowledge", apiPortMethod: "getKnowledge", repositoryView: { repositories: ["knowledge"] }, requestMapper: (r: import("../dto/ApplicationContext.js").QueryDto) => r, validator: () => undefined, repositorySelector: read, handler: (q: import("../dto/ApplicationContext.js").QueryDto, c: import("../dto/ApplicationContext.js").QueryContext, r: Reads) => q.targetId === undefined ? Promise.resolve(null) : r.knowledge.findById(TenantId.from(c.tenantId), KnowledgeId.from(q.targetId)), responseMapper: (r: Knowledge | null) => r === null ? null : knowledgeDto(r) }, listKnowledge: { boundedContext: "knowledge-policy", exportName: "KnowledgeRepository.listByTenant", operationName: "listKnowledge", apiPortMethod: "listKnowledge", repositoryView: { repositories: ["knowledge"] }, requestMapper: (r: import("../dto/ApplicationContext.js").QueryDto) => r, validator: () => undefined, repositorySelector: read, handler: (_q: import("../dto/ApplicationContext.js").QueryDto, c: import("../dto/ApplicationContext.js").QueryContext, r: Reads) => r.knowledge.listByTenant(TenantId.from(c.tenantId)), responseMapper: (r: readonly Knowledge[]) => r.map(knowledgeDto) }, getPolicy: { boundedContext: "knowledge-policy", exportName: "PolicyRepository.findById", operationName: "getPolicy", apiPortMethod: "getPolicy", repositoryView: { repositories: ["policy"] }, requestMapper: (r: import("../dto/ApplicationContext.js").QueryDto) => r, validator: () => undefined, repositorySelector: read, handler: (q: import("../dto/ApplicationContext.js").QueryDto, c: import("../dto/ApplicationContext.js").QueryContext, r: Reads) => q.targetId === undefined ? Promise.resolve(null) : r.policy.findById(TenantId.from(c.tenantId), PolicyId.from(q.targetId)), responseMapper: (r: Policy | null) => r === null ? null : policyDto(r) }, listPolicies: { boundedContext: "knowledge-policy", exportName: "PolicyRepository.listByTenant", operationName: "listPolicies", apiPortMethod: "listPolicies", repositoryView: { repositories: ["policy"] }, requestMapper: (r: import("../dto/ApplicationContext.js").QueryDto) => r, validator: () => undefined, repositorySelector: read, handler: (_q: import("../dto/ApplicationContext.js").QueryDto, c: import("../dto/ApplicationContext.js").QueryContext, r: Reads) => r.policy.listByTenant(TenantId.from(c.tenantId)), responseMapper: (r: readonly Policy[]) => r.map(policyDto) } } as unknown as KnowledgePolicyBindings; }
export function createKnowledgePolicyBindings(validation: KnowledgeReferenceValidationPort): KnowledgePolicyBindings { if (validation === undefined || validation === null) throw new ApplicationError("APPLICATION_FAILURE", "KnowledgeReferenceValidationPort is required"); return commandBindings(validation); }
