import { CausationId, CorrelationId } from "../../shared/common/index.js";
import type { JsonObject } from "../../shared/common/serialization.js";
import { EvidenceReference } from "../../shared/evidence/EvidenceReference.js";
import { ConnectorId, EvidenceId, PublicationId, PublicationPackageId, PublicationRecordId, PublicationVersionId, TenantId } from "../../shared/identity/index.js";
import { LineageReference } from "../../shared/lineage/LineageReference.js";
import { AssetReference, AssetVersionReference, ConnectorReference, KnowledgeReference, MissionReference, ReviewReference } from "../../shared/references/index.js";
import { ApplicationError } from "../errors/ApplicationError.js";
import type { ApplicationCommandContext, CommittedOperationResultDto, GetPublicationRequestDto, PublicationCommandRequestDto, PublicationDto, QueryContext } from "../dto/ApplicationContext.js";
import type { ReadRepositorySession, TransactionalRepositorySession } from "../services/TransactionalRepositorySession.js";
import type { ValidatedCommandContext } from "../services/ApplicationCommandRunner.js";
import { archivePublication, authorizePublication, createPublication, preparePublication, recordPublicationOutcome } from "../../modules/publication/application/index.js";
import { Publication } from "../../modules/publication/domain/Publication.js";
import { PublicationDestination } from "../../modules/publication/domain/PublicationPackage.js";
import type { PublicationConnectorEvidencePort, PublicationGovernancePort, PublicationMissionPort, PublicationReferenceValidationPort, PublicationReviewPort } from "../../modules/publication/ports/index.js";
type Repositories = Pick<TransactionalRepositorySession, "publication">; type Reads = Pick<ReadRepositorySession, "publication">;
export interface PublicationDependencies { readonly mission: PublicationMissionPort; readonly references: PublicationReferenceValidationPort; readonly governance: PublicationGovernancePort; readonly review: PublicationReviewPort; readonly connectorEvidence: PublicationConnectorEvidencePort; }
const object = (v: unknown): Record<string, unknown> => v !== null && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : {};
const required = (v: unknown, f: string): string => typeof v === "string" && v.trim() ? v : (() => { throw new ApplicationError("VALIDATION_FAILED", `${f} is required`, { f }); })();
function payload(c: PublicationCommandRequestDto) { return object(c.payload); } function target(c: PublicationCommandRequestDto, f: string) { return required(c.targetId ?? payload(c)[f], f); } function normalize(c: PublicationCommandRequestDto, f: string) { return c.targetId ? c : { ...c, targetId: target(c, f) }; }
function audit(c: PublicationCommandRequestDto, x: ValidatedCommandContext) { const p = payload(c); return { reason: c.reason, occurredAt: required(p.occurredAt, "occurredAt"), correlationId: CorrelationId.from(x.correlationId), ...(x.causationId ? { causationId: CausationId.from(x.causationId) } : {}), evidence: (Array.isArray(p.evidence) ? p.evidence : []).map((v) => { const e = object(v); return new EvidenceReference({ evidenceId: EvidenceId.from(required(e.evidenceId, "evidence.evidenceId")), source: required(e.source, "evidence.source"), type: required(e.type, "evidence.type"), capturedAt: required(e.capturedAt, "evidence.capturedAt") }); }), lineage: (Array.isArray(p.lineage) ? p.lineage : []).map((v) => { const e = object(v); return new LineageReference({ sourceId: required(e.sourceId, "lineage.sourceId"), targetId: required(e.targetId, "lineage.targetId"), relationship: required(e.relationship, "lineage.relationship") as never, declaredAt: required(e.declaredAt, "lineage.declaredAt") }); }) }; }
function result(x: string, id: string) { return Object.freeze({ transactionId: x, status: "COMMITTED", resourceReferences: Object.freeze([{ resourceType: "Publication", resourceId: id }]) }); } function dto(v: Publication): PublicationDto { return { publicationId: v.id.toString(), tenantId: v.tenantId.toString(), status: v.status, version: v.version.value }; }
export function createPublicationBindings(deps: PublicationDependencies): Record<string, unknown> { if (Object.values(deps).some((v) => !v)) throw new ApplicationError("APPLICATION_FAILURE", "Publication collaborators are required"); const select = (r: TransactionalRepositorySession): Repositories => ({ publication: r.publication }); const read = (r: ReadRepositorySession): Reads => ({ publication: r.publication }); const bind = (name: string, fn: (c: PublicationCommandRequestDto, x: ValidatedCommandContext, r: Repositories) => Promise<CommittedOperationResultDto>, field = "publicationId") => ({ boundedContext: "publication", exportName: name, operationName: name, apiPortMethod: name[0]!.toLowerCase() + name.slice(1), repositoryView: { repositories: ["publication"] }, useCaseExport: name, requestMapper: (c: PublicationCommandRequestDto) => normalize(c, field), validator: (c: PublicationCommandRequestDto) => { target(c, field); required(payload(c).occurredAt, "occurredAt"); }, repositorySelector: select, confirmedResourceType: "Publication", handler: (c: PublicationCommandRequestDto, x: ValidatedCommandContext, r: Repositories) => fn(c, x, r), responseMapper: (v: CommittedOperationResultDto) => v }); const out: Record<string, unknown> = {};
  out.createPublication = bind("CreatePublication", async (c, x, r) => { const p = payload(c); const tenant = TenantId.from(x.tenantId); await createPublication(r.publication, deps.mission, deps.references, { ...audit(c, x), publicationId: PublicationId.from(target(c, "publicationId")), packageId: PublicationPackageId.from(required(p.packageId, "packageId")), tenantId: tenant, missionReference: MissionReference.fromJSON(object(p.missionReference) as never), items: (Array.isArray(p.items) ? p.items : []).map((v) => { const i = object(v); return { assetReference: AssetReference.fromJSON(object(i.assetReference) as never), assetVersionReference: AssetVersionReference.fromJSON(object(i.assetVersionReference) as never) }; }), destinations: (Array.isArray(p.destinations) ? p.destinations : []).map((v) => { const d = object(v); return new PublicationDestination({ tenantId: tenant, key: required(d.key, "destination.key"), audience: required(d.audience, "destination.audience"), purpose: required(d.purpose, "destination.purpose") }); }), knowledgeReferences: (Array.isArray(p.knowledgeReferences) ? p.knowledgeReferences : []).map((v) => KnowledgeReference.fromJSON(object(v) as never)), metadata: object(p.metadata) as never }); return result(x.transactionId, target(c, "publicationId")); });
  for (const [name, fn] of [["PreparePublication", preparePublication], ["AuthorizePublication", authorizePublication], ["ArchivePublication", archivePublication], ["RecordPublicationOutcome", recordPublicationOutcome]] as const) out[name[0]!.toLowerCase() + name.slice(1)] = bind(name, async (c, x, r) => { const p = payload(c); const id = target(c, "publicationId"); if (name === "PreparePublication") await fn(r.publication, deps.review, deps.references, TenantId.from(x.tenantId), PublicationId.from(id), ReviewReference.fromJSON(object(p.reviewReference) as never), audit(c, x) as never); else if (name === "AuthorizePublication") await fn(r.publication, deps.governance, deps.review, TenantId.from(x.tenantId), PublicationId.from(id), ReviewReference.fromJSON(object(p.reviewReference) as never), audit(c, x) as never); else if (name === "ArchivePublication") await fn(r.publication, deps.governance, TenantId.from(x.tenantId), PublicationId.from(id), audit(c, x) as never); else await fn(r.publication, deps.connectorEvidence, TenantId.from(x.tenantId), PublicationId.from(id), { ...audit(c, x), publicationVersionId: PublicationVersionId.from(required(p.publicationVersionId, "publicationVersionId")), observationBatchKey: required(p.observationBatchKey, "observationBatchKey"), observations: (Array.isArray(p.observations) ? p.observations : []).map((value) => { const observation = object(value); const connector = object(observation.connectorReference); return { recordId: PublicationRecordId.from(required(observation.recordId, "observation.recordId")), connectorReference: new ConnectorReference(ConnectorId.from(required(connector.id, "observation.connectorReference.id")), TenantId.from(required(connector.tenantId, "observation.connectorReference.tenantId"))), destinationKey: required(observation.destinationKey, "observation.destinationKey"), result: required(observation.result, "observation.result"), observedAt: required(observation.observedAt, "observation.observedAt"), evidence: (Array.isArray(observation.evidence) ? observation.evidence : []).map((item) => { const evidence = object(item); return new EvidenceReference({ evidenceId: EvidenceId.from(required(evidence.evidenceId, "observation.evidence.evidenceId")), source: required(evidence.source, "observation.evidence.source"), type: required(evidence.type, "observation.evidence.type"), capturedAt: required(evidence.capturedAt, "observation.evidence.capturedAt") }); }), ...(typeof observation.externalIdentifier === "string" ? { externalIdentifier: observation.externalIdentifier } : {}), ...(typeof observation.failureReason === "string" ? { failureReason: observation.failureReason } : {}) }; }) } as never); return result(x.transactionId, id); });
  out.getPublication = { boundedContext: "publication", exportName: "PublicationRepository.findById", operationName: "getPublication", apiPortMethod: "getPublication", repositoryView: { repositories: ["publication"] }, requestMapper: (q: GetPublicationRequestDto) => q, validator: (q: GetPublicationRequestDto) => { if (!q.targetId) throw new ApplicationError("VALIDATION_FAILED", "targetId is required", {}); }, repositorySelector: read, handler: (q: GetPublicationRequestDto, x: QueryContext, r: Reads) => r.publication.findById(TenantId.from(x.tenantId), PublicationId.from(q.targetId!)), responseMapper: (v: Publication | null) => v ? dto(v) : null }; return out; }
