import { CausationId, CorrelationId } from "../../shared/common/index.js";
import type { JsonObject } from "../../shared/common/serialization.js";
import { EvidenceReference } from "../../shared/evidence/EvidenceReference.js";
import { EvidenceId, ReviewId, ReviewConclusionId, ReviewFindingId, ReviewRequestId, ReviewSessionId, TenantId } from "../../shared/identity/index.js";
import { LineageReference } from "../../shared/lineage/LineageReference.js";
import { MissionReference } from "../../shared/references/index.js";
import { ApplicationError } from "../errors/ApplicationError.js";
import type { ApplicationCommandContext, CommittedOperationResultDto, GetReviewRequestDto, PublicationCommandRequestDto, QueryContext, ReviewCommandRequestDto, ReviewDto } from "../dto/ApplicationContext.js";
import type { ReadRepositorySession, TransactionalRepositorySession } from "../services/TransactionalRepositorySession.js";
import type { ValidatedCommandContext } from "../services/ApplicationCommandRunner.js";
import { archiveReview, cancelSession, closeSession, completeReview, createReview, openSession, planSession, recordFinding, startReview } from "../../modules/review/application/index.js";
import { Review } from "../../modules/review/domain/Review.js";
import { ReviewScope } from "../../modules/review/domain/ReviewScope.js";
import type { ReviewGovernancePort, ReviewMissionPort, ReviewPublicationPort, ReviewReferenceValidationPort, ReviewWorkflowPort } from "../../modules/review/ports/index.js";

export interface ReviewDependencies { readonly mission: ReviewMissionPort; readonly references: ReviewReferenceValidationPort; readonly governance: ReviewGovernancePort; readonly workflow: ReviewWorkflowPort; readonly publication: ReviewPublicationPort; }
type Repositories = Pick<TransactionalRepositorySession, "review">; type Reads = Pick<ReadRepositorySession, "review">;
const object = (v: unknown): Record<string, unknown> => v !== null && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : {};
const required = (v: unknown, f: string): string => typeof v === "string" && v.trim() ? v : (() => { throw new ApplicationError("VALIDATION_FAILED", `${f} is required`, { f }); })();
function payload(c: ReviewCommandRequestDto) { return object(c.payload); } function target(c: ReviewCommandRequestDto, f: string) { return required(c.targetId ?? payload(c)[f], f); }
function audit(c: ReviewCommandRequestDto, x: ValidatedCommandContext) { const p = payload(c); return { reason: c.reason, occurredAt: required(p.occurredAt, "occurredAt"), correlationId: CorrelationId.from(x.correlationId), ...(x.causationId ? { causationId: CausationId.from(x.causationId) } : {}), evidence: (Array.isArray(p.evidence) ? p.evidence : []).map((v) => { const e = object(v); return new EvidenceReference({ evidenceId: EvidenceId.from(required(e.evidenceId, "evidence.evidenceId")), source: required(e.source, "evidence.source"), type: required(e.type, "evidence.type"), capturedAt: required(e.capturedAt, "evidence.capturedAt") }); }), lineage: (Array.isArray(p.lineage) ? p.lineage : []).map((v) => { const e = object(v); return new LineageReference({ sourceId: required(e.sourceId, "lineage.sourceId"), targetId: required(e.targetId, "lineage.targetId"), relationship: required(e.relationship, "lineage.relationship") as never, declaredAt: required(e.declaredAt, "lineage.declaredAt") }); }) }; }
function normalize(c: ReviewCommandRequestDto, f: string) { return c.targetId ? c : { ...c, targetId: target(c, f) }; }
function result(x: string, id: string) { return Object.freeze({ transactionId: x, status: "COMMITTED", resourceReferences: Object.freeze([{ resourceType: "Review", resourceId: id }]) }); }
function dto(v: Review): ReviewDto { return { reviewId: v.id.toString(), tenantId: v.tenantId.toString(), status: v.status, version: v.version.value }; }
function validate(c: ReviewCommandRequestDto, f: string) { target(c, f); required(payload(c).occurredAt, "occurredAt"); }
export function createReviewBindings(deps: ReviewDependencies): Record<string, unknown> {
  if (Object.values(deps).some((v) => !v)) throw new ApplicationError("APPLICATION_FAILURE", "Review collaborators are required");
  const select = (r: TransactionalRepositorySession): Repositories => ({ review: r.review }); const read = (r: ReadRepositorySession): Reads => ({ review: r.review }); const bind = (name: string, fn: (c: PublicationCommandRequestDto, x: ValidatedCommandContext, r: Repositories) => Promise<CommittedOperationResultDto>, field = "reviewId") => ({ boundedContext: "review", exportName: name, operationName: name, apiPortMethod: name[0]!.toLowerCase() + name.slice(1), repositoryView: { repositories: ["review"] }, useCaseExport: name, requestMapper: (c: ReviewCommandRequestDto) => normalize(c, field), validator: (c: ReviewCommandRequestDto) => validate(c, field), repositorySelector: select, confirmedResourceType: "Review", handler: (c: ReviewCommandRequestDto, x: ValidatedCommandContext, r: Repositories) => fn(c, x, r), responseMapper: (v: CommittedOperationResultDto) => v });
  const out: Record<string, unknown> = {};
  out.createReview = bind("CreateReview", async (c, x, r) => { const p = payload(c); const id = target(c, "reviewId"); await createReview(r.review, deps.mission, deps.references, { ...audit(c, x), reviewId: ReviewId.from(id), requestId: ReviewRequestId.from(required(p.requestId, "requestId")), tenantId: TenantId.from(x.tenantId), missionReference: MissionReference.fromJSON(object(p.missionReference) as never), scope: ReviewScope.fromJSON(object(p.scope) as JsonObject), reviewType: required(p.reviewType, "reviewType"), criteria: Array.isArray(p.criteria) ? p.criteria.map(String) : [], requestedBy: required(p.requestedBy, "requestedBy") as never, requestedAt: required(p.requestedAt, "requestedAt") } as never); return result(x.transactionId, id); });
  for (const [name, fn] of [["StartReview", startReview], ["PlanSession", planSession], ["OpenSession", openSession], ["RecordFinding", recordFinding], ["CloseSession", closeSession], ["CancelSession", cancelSession], ["CompleteReview", completeReview], ["ArchiveReview", archiveReview]] as const) out[name[0]!.toLowerCase() + name.slice(1)] = bind(name, async (c, x, r) => { const p = payload(c); const id = target(c, "reviewId"); const a = audit(c, x); if (name === "StartReview") await fn(r.review, deps.mission, deps.references, deps.workflow, TenantId.from(x.tenantId), ReviewId.from(id), a as never); else if (name === "CompleteReview") await fn(r.review, deps.governance, deps.workflow, deps.publication, TenantId.from(x.tenantId), ReviewId.from(id), { ...a, conclusionId: ReviewConclusionId.from(required(p.conclusionId, "conclusionId")), outcome: required(p.outcome, "outcome"), rationale: required(p.rationale, "rationale") } as never); else if (name === "ArchiveReview") await fn(r.review, deps.governance, TenantId.from(x.tenantId), ReviewId.from(id), a as never); else await fn(r.review, TenantId.from(x.tenantId), ReviewId.from(id), { ...a, ...(p.sessionId ? { sessionId: ReviewSessionId.from(String(p.sessionId)) } : {}), ...(p.findingId ? { findingId: ReviewFindingId.from(String(p.findingId)) } : {}), ...(p.statement ? { statement: String(p.statement), category: String(p.category), severity: String(p.severity), recommendation: String(p.recommendation) } : {}) } as never); return result(x.transactionId, id); });
  out.getReview = { boundedContext: "review", exportName: "ReviewRepository.findById", operationName: "getReview", apiPortMethod: "getReview", repositoryView: { repositories: ["review"] }, requestMapper: (q: GetReviewRequestDto) => q, validator: (q: GetReviewRequestDto) => { if (!q.targetId) throw new ApplicationError("VALIDATION_FAILED", "targetId is required", {}); }, repositorySelector: read, handler: (q: GetReviewRequestDto, x: QueryContext, r: Reads) => r.review.findById(TenantId.from(x.tenantId), ReviewId.from(q.targetId!)), responseMapper: (v: Review | null) => v ? dto(v) : null };
  return out;
}
