import { CausationId, CorrelationId } from "../../shared/common/index.js";
import type { JsonObject } from "../../shared/common/serialization.js";
import { EvidenceReference } from "../../shared/evidence/EvidenceReference.js";
import { EvidenceId, MissionId, StageId, TaskId, TenantId, WorkflowExecutionId, WorkflowId } from "../../shared/identity/index.js";
import { LineageReference } from "../../shared/lineage/LineageReference.js";
import { AssetReference, AssetVersionReference, DecisionReference, KnowledgeReference, MissionReference, PolicyReference, WorkAssignmentReference, WorkflowReference } from "../../shared/references/index.js";
import { ApplicationError } from "../errors/ApplicationError.js";
import type { ApplicationCommandContext, CommittedOperationResultDto, GetWorkflowExecutionRequestDto, GetWorkflowRequestDto, QueryContext, WorkflowCommandRequestDto, WorkflowDto, WorkflowExecutionDto } from "../dto/ApplicationContext.js";
import type { ReadRepositorySession, TransactionalRepositorySession } from "../services/TransactionalRepositorySession.js";
import type { ValidatedCommandContext } from "../services/ApplicationCommandRunner.js";
import type { CommandBindingDescriptor, QueryBindingDescriptor } from "./ApplicationBindingTypes.js";
import { activateWorkflow, advanceStage, archiveWorkflow, cancelWorkflow, completeWorkflow, createWorkflow, failWorkflowExecution, pauseWorkflow, recordTaskFailure, recordTaskState, resumeWorkflow, startWorkflow } from "../../modules/workflow/application/index.js";
import { Workflow } from "../../modules/workflow/domain/Workflow.js";
import { WorkflowExecution } from "../../modules/workflow/domain/WorkflowExecution.js";
import { WorkflowMetadata } from "../../modules/workflow/domain/WorkflowMetadata.js";
import { StageDefinition, TaskDefinition } from "../../modules/workflow/domain/WorkflowDefinitions.js";
import type { MissionWorkflowPort, WorkflowAssetPort, WorkflowAssignmentPort, WorkflowDependencyGraphPort, WorkflowGovernancePort, WorkflowKnowledgePort } from "../../modules/workflow/ports/index.js";

export interface WorkflowDependencies { readonly mission: MissionWorkflowPort; readonly governance: WorkflowGovernancePort; readonly graph: WorkflowDependencyGraphPort; readonly assets: WorkflowAssetPort; readonly knowledge: WorkflowKnowledgePort; readonly assignments: WorkflowAssignmentPort; }
type Repositories = Pick<TransactionalRepositorySession, "workflow" | "workflowExecution">; type Reads = Pick<ReadRepositorySession, "workflow" | "workflowExecution">;
const object = (v: unknown): Record<string, unknown> => (v !== null && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : {});
const required = (v: unknown, f: string): string => typeof v === "string" && v.trim() ? v : (() => { throw new ApplicationError("VALIDATION_FAILED", `${f} is required`, { f }); })();
function payload(c: WorkflowCommandRequestDto) { return object(c.payload); }
function target(c: WorkflowCommandRequestDto, f: string) { return required(c.targetId ?? payload(c)[f], f); }
function audit(c: WorkflowCommandRequestDto, x: ValidatedCommandContext) { const p = payload(c); return { reason: c.reason, occurredAt: required(p.occurredAt, "occurredAt"), correlationId: CorrelationId.from(x.correlationId), ...(x.causationId ? { causationId: CausationId.from(x.causationId) } : {}), evidence: (Array.isArray(p.evidence) ? p.evidence : []).map((v) => { const e = object(v); return new EvidenceReference({ evidenceId: EvidenceId.from(required(e.evidenceId, "evidence.evidenceId")), source: required(e.source, "evidence.source"), type: required(e.type, "evidence.type"), capturedAt: required(e.capturedAt, "evidence.capturedAt") }); }), lineage: (Array.isArray(p.lineage) ? p.lineage : []).map((v) => { const e = object(v); return new LineageReference({ sourceId: required(e.sourceId, "lineage.sourceId"), targetId: required(e.targetId, "lineage.targetId"), relationship: required(e.relationship, "lineage.relationship") as never, declaredAt: required(e.declaredAt, "lineage.declaredAt") }); }) }; }
function normalize(c: WorkflowCommandRequestDto, field: string): WorkflowCommandRequestDto { return c.targetId ? c : { ...c, targetId: target(c, field) }; }
function result(x: string, type: string, id: string): CommittedOperationResultDto { return Object.freeze({ transactionId: x, status: "COMMITTED", resourceReferences: Object.freeze([{ resourceType: type, resourceId: id }]) }); }
function workflowDto(v: Workflow): WorkflowDto { return { workflowId: v.id.toString(), tenantId: v.tenantId.toString(), status: v.status, version: v.version.value }; }
function executionDto(v: WorkflowExecution): WorkflowExecutionDto { return { executionId: v.id.toString(), tenantId: v.tenantId.toString(), status: v.status, version: v.version.value }; }
function validate(c: WorkflowCommandRequestDto, f: string) { target(c, f); required(payload(c).occurredAt, "occurredAt"); }
function commandFor(c: WorkflowCommandRequestDto, x: ValidatedCommandContext, extra: Record<string, unknown> = {}) { return { ...audit(c, x), ...extra }; }

export type WorkflowBindings = Record<string, unknown>;
export function createWorkflowBindings(deps: WorkflowDependencies): WorkflowBindings {
  if (Object.values(deps).some((v) => v === undefined || v === null)) throw new ApplicationError("APPLICATION_FAILURE", "Workflow collaborators are required");
  const select = (r: TransactionalRepositorySession): Repositories => ({ workflow: r.workflow, workflowExecution: r.workflowExecution }); const read = (r: ReadRepositorySession): Reads => ({ workflow: r.workflow, workflowExecution: r.workflowExecution });
  const command = (name: string, field: string, handler: (c: WorkflowCommandRequestDto, x: ValidatedCommandContext, r: Repositories) => Promise<string>, type = "Workflow") => ({ boundedContext: "workflow", exportName: name, operationName: name, apiPortMethod: name[0]!.toLowerCase() + name.slice(1), repositoryView: { repositories: ["workflow", "workflowExecution"] }, useCaseExport: name, requestMapper: (c: WorkflowCommandRequestDto) => normalize(c, field), validator: (c: WorkflowCommandRequestDto) => validate(c, field), repositorySelector: select, confirmedResourceType: type, handler: async (c: WorkflowCommandRequestDto, x: ValidatedCommandContext, r: Repositories) => result(x.transactionId, type, await handler(c, x, r)), responseMapper: (v: CommittedOperationResultDto) => v });
  const out: Record<string, unknown> = {};
  out.createWorkflow = command("CreateWorkflow", "workflowId", async (c, x, r) => { const p = payload(c); const tenant = TenantId.from(x.tenantId); const stages = (Array.isArray(p.stageDefinitions) ? p.stageDefinitions : []).map((v) => StageDefinition.fromSnapshot(object(v) as JsonObject)); const tasks = (Array.isArray(p.taskDefinitions) ? p.taskDefinitions : []).map((v) => TaskDefinition.fromSnapshot(object(v) as JsonObject)); await createWorkflow(r.workflow, deps.mission, deps.graph, deps.assets, deps.knowledge, { ...commandFor(c, x, { workflowId: WorkflowId.from(target(c, "workflowId")), tenantId: tenant, missionReference: MissionReference.fromJSON(object(p.missionReference) as never), metadata: WorkflowMetadata.fromJSON(object(p.metadata) as JsonObject), stageDefinitions: stages, taskDefinitions: tasks }) } as never); return target(c, "workflowId"); });
  for (const [name, fn, field] of [["ActivateWorkflow", activateWorkflow, "workflowId"], ["ArchiveWorkflow", archiveWorkflow, "workflowId"]] as const) out[name[0]!.toLowerCase() + name.slice(1)] = command(name, field, async (c, x, r) => { await fn(r.workflow, deps.governance, TenantId.from(x.tenantId), WorkflowId.from(target(c, field)), commandFor(c, x) as never); return target(c, field); });
  out.startWorkflow = command("StartWorkflow", "workflowId", async (c, x, r) => { const p = payload(c); const id = WorkflowExecutionId.from(required(p.executionId, "executionId")); await startWorkflow(r.workflow, r.workflowExecution, deps.governance, TenantId.from(x.tenantId), WorkflowId.from(target(c, "workflowId")), commandFor(c, x, { executionId: id, tenantId: TenantId.from(x.tenantId), workflowReference: WorkflowReference.fromJSON(object(p.workflowReference) as never), missionReference: MissionReference.fromJSON(object(p.missionReference) as never), initialStageId: StageId.from(required(p.initialStageId, "initialStageId")) }) as never); return id.toString(); }, "WorkflowExecution");
  for (const [name, fn] of [["AdvanceStage", advanceStage], ["CompleteWorkflow", completeWorkflow], ["CancelWorkflow", cancelWorkflow]] as const) out[name[0]!.toLowerCase() + name.slice(1)] = command(name, "executionId", async (c, x, r) => { const p = payload(c); const extra = name === "AdvanceStage" ? { nextStageId: StageId.from(required(p.nextStageId, "nextStageId")), disposition: required(p.disposition, "disposition") } : {}; await fn(r.workflowExecution, deps.governance, TenantId.from(x.tenantId), WorkflowExecutionId.from(target(c, "executionId")), commandFor(c, x, extra) as never); return target(c, "executionId"); }, "WorkflowExecution");
  for (const [name, fn] of [["PauseWorkflow", pauseWorkflow], ["ResumeWorkflow", resumeWorkflow], ["FailWorkflowExecution", failWorkflowExecution]] as const) out[name[0]!.toLowerCase() + name.slice(1)] = command(name, "executionId", async (c, x, r) => { const p = payload(c); const extra = name === "FailWorkflowExecution" ? { failure: required(p.failure, "failure") } : {}; await fn(r.workflowExecution, TenantId.from(x.tenantId), WorkflowExecutionId.from(target(c, "executionId")), commandFor(c, x, extra) as never); return target(c, "executionId"); }, "WorkflowExecution");
  out.recordTaskState = command("RecordTaskState", "executionId", async (c, x, r) => { const p = payload(c); await recordTaskState(r.workflowExecution, deps.assignments, TenantId.from(x.tenantId), WorkflowExecutionId.from(target(c, "executionId")), commandFor(c, x, { taskId: TaskId.from(required(p.taskId, "taskId")), observedState: required(p.observedState, "observedState"), ...(p.workAssignmentReference ? { workAssignmentReference: WorkAssignmentReference.fromJSON(object(p.workAssignmentReference) as never) } : {}) }) as never); return target(c, "executionId"); }, "WorkflowExecution");
  out.recordTaskFailure = command("RecordTaskFailure", "executionId", async (c, x, r) => { const p = payload(c); await recordTaskFailure(r.workflowExecution, deps.assignments, TenantId.from(x.tenantId), WorkflowExecutionId.from(target(c, "executionId")), commandFor(c, x, { taskId: TaskId.from(required(p.taskId, "taskId")), failure: required(p.failure, "failure"), ...(p.workAssignmentReference ? { workAssignmentReference: WorkAssignmentReference.fromJSON(object(p.workAssignmentReference) as never) } : {}) }) as never); return target(c, "executionId"); }, "WorkflowExecution");
  out.getWorkflow = { boundedContext: "workflow", exportName: "WorkflowRepository.findById", operationName: "getWorkflow", apiPortMethod: "getWorkflow", repositoryView: { repositories: ["workflow"] }, requestMapper: (q: GetWorkflowRequestDto) => q, validator: () => undefined, repositorySelector: read, handler: (q: GetWorkflowRequestDto, x: QueryContext, r: Reads) => q.targetId ? r.workflow.findById(TenantId.from(x.tenantId), WorkflowId.from(q.targetId)) : Promise.resolve(null), responseMapper: (v: Workflow | null) => v ? workflowDto(v) : null };
  out.getWorkflowExecution = { boundedContext: "workflow", exportName: "WorkflowExecutionRepository.findById", operationName: "getWorkflowExecution", apiPortMethod: "getWorkflowExecution", repositoryView: { repositories: ["workflowExecution"] }, requestMapper: (q: GetWorkflowExecutionRequestDto) => q, validator: () => undefined, repositorySelector: read, handler: (q: GetWorkflowExecutionRequestDto, x: QueryContext, r: Reads) => q.targetId ? r.workflowExecution.findById(TenantId.from(x.tenantId), WorkflowExecutionId.from(q.targetId)) : Promise.resolve(null), responseMapper: (v: WorkflowExecution | null) => v ? executionDto(v) : null };
  return out;
}
