import { AggregateRoot } from "../../../shared/aggregate/AggregateRoot.js";
import { CausationId, CorrelationId } from "../../../shared/common/index.js";
import type { JsonObject } from "../../../shared/common/serialization.js";
import { InvariantViolation } from "../../../shared/errors/InvariantViolation.js";
import { EvidenceReference } from "../../../shared/evidence/EvidenceReference.js";
import { EvidenceId } from "../../../shared/identity/EvidenceId.js";
import { ExecutionId } from "../../../shared/identity/ExecutionId.js";
import { TenantId } from "../../../shared/identity/TenantId.js";
import { LineageReference, type LineageReferenceProps } from "../../../shared/lineage/LineageReference.js";
import { AgentReference, MissionReference, WorkAssignmentReference } from "../../../shared/references/index.js";
import { Version } from "../../../shared/version/Version.js";
import type { ExecutionStatus } from "./ExecutionStatus.js";
import type { CancelExecutionCommand, CompleteExecutionCommand, FailExecutionCommand, StartExecutionCommand } from "./WorkforceCommands.js";
import { ExecutionCancelled, ExecutionCompleted, ExecutionFailed, ExecutionStarted } from "./WorkforceEvents.js";
import { ExecutionResult, type ExecutionResultProps } from "./ExecutionResult.js";

export interface ExecutionSnapshot { readonly executionId: string; readonly tenantId: string; readonly missionReference: JsonObject; readonly agentReference: JsonObject; readonly workAssignmentReference: JsonObject; readonly status: ExecutionStatus; readonly result: JsonObject | null; readonly failure: string | null; readonly evidence: readonly JsonObject[]; readonly lineage: readonly JsonObject[]; readonly version: number; }
function evidenceFrom(value: JsonObject): EvidenceReference { return new EvidenceReference({ evidenceId: EvidenceId.from(String(value.evidenceId)), source: String(value.source), type: String(value.type), capturedAt: String(value.capturedAt), ...(typeof value.locator === "string" ? { locator: value.locator } : {}), ...(typeof value.limitation === "string" ? { limitation: value.limitation } : {}) }); }
function lineageFrom(value: JsonObject): LineageReference { return new LineageReference(value as unknown as LineageReferenceProps); }

export class Execution extends AggregateRoot<ExecutionId> {
  private readonly executionTenantId: TenantId; private readonly executionMissionReference: MissionReference; private readonly executionAgentReference: AgentReference; private readonly executionWorkAssignmentReference: WorkAssignmentReference;
  private executionStatus: ExecutionStatus; private executionResult: ExecutionResult | null; private executionFailure: string | null; private readonly executionEvidence: EvidenceReference[]; private readonly executionLineage: LineageReference[];
  private constructor(id: ExecutionId, state: { tenantId: TenantId; missionReference: MissionReference; agentReference: AgentReference; workAssignmentReference: WorkAssignmentReference; status: ExecutionStatus; result: ExecutionResult | null; failure: string | null; evidence: EvidenceReference[]; lineage: LineageReference[]; version: Version }) {
    super(id, state.version); if (!state.missionReference.tenantId.equals(state.tenantId) || !state.agentReference.tenantId.equals(state.tenantId) || !state.workAssignmentReference.tenantId.equals(state.tenantId)) throw new InvariantViolation("Execution references must belong to its Tenant");
    this.executionTenantId = state.tenantId; this.executionMissionReference = state.missionReference; this.executionAgentReference = state.agentReference; this.executionWorkAssignmentReference = state.workAssignmentReference; this.executionStatus = state.status; this.executionResult = state.result; this.executionFailure = state.failure; this.executionEvidence = [...state.evidence]; this.executionLineage = [...state.lineage];
  }

  public static start(command: StartExecutionCommand): Execution { const execution = new Execution(command.executionId, { tenantId: command.tenantId, missionReference: command.missionReference, agentReference: command.agentReference, workAssignmentReference: command.workAssignmentReference, status: "PROPOSED", result: null, failure: null, evidence: [...command.evidence], lineage: [...command.lineage], version: Version.initial() }); execution.executionStatus = "RUNNING"; execution.incrementVersion(); execution.emit(ExecutionStarted, command); return execution; }
  public static rehydrate(snapshot: ExecutionSnapshot): Execution { return new Execution(ExecutionId.from(snapshot.executionId), { tenantId: TenantId.from(snapshot.tenantId), missionReference: MissionReference.fromJSON(snapshot.missionReference as { id: string; tenantId: string }), agentReference: AgentReference.fromJSON(snapshot.agentReference as { id: string; tenantId: string }), workAssignmentReference: WorkAssignmentReference.fromJSON(snapshot.workAssignmentReference as { id: string; tenantId: string }), status: snapshot.status, result: snapshot.result ? ExecutionResult.fromJSON(snapshot.result) : null, failure: snapshot.failure, evidence: snapshot.evidence.map(evidenceFrom), lineage: snapshot.lineage.map(lineageFrom), version: Version.from(snapshot.version) }); }

  public get tenantId(): TenantId { return this.executionTenantId; } public get missionReference(): MissionReference { return this.executionMissionReference; } public get agentReference(): AgentReference { return this.executionAgentReference; } public get workAssignmentReference(): WorkAssignmentReference { return this.executionWorkAssignmentReference; } public get status(): ExecutionStatus { return this.executionStatus; } public get result(): ExecutionResult | null { return this.executionResult; } public get failure(): string | null { return this.executionFailure; } public get evidence(): readonly EvidenceReference[] { return [...this.executionEvidence]; } public get lineage(): readonly LineageReference[] { return [...this.executionLineage]; }
  public complete(command: CompleteExecutionCommand): void { this.assertRunning(); this.executionResult = command.result instanceof ExecutionResult ? command.result : new ExecutionResult(command.result as ExecutionResultProps); this.executionStatus = "COMPLETED"; this.incrementVersion(); this.emit(ExecutionCompleted, command); }
  public fail(command: FailExecutionCommand): void { this.assertRunning(); const failure = command.failure.trim(); if (failure.length === 0) throw new InvariantViolation("Execution failure reason is required"); this.executionFailure = failure; this.executionStatus = "FAILED"; this.incrementVersion(); this.emit(ExecutionFailed, command, { failure }); }
  public cancel(command: CancelExecutionCommand): void { this.assertRunning(); this.executionStatus = "CANCELLED"; this.incrementVersion(); this.emit(ExecutionCancelled, command); }
  public toSnapshot(): ExecutionSnapshot { return { executionId: this.id.toString(), tenantId: this.tenantId.toString(), missionReference: this.missionReference.toJSON(), agentReference: this.agentReference.toJSON(), workAssignmentReference: this.workAssignmentReference.toJSON(), status: this.status, result: this.result?.toJSON() ?? null, failure: this.failure, evidence: this.evidence.map((item) => item.toJSON()), lineage: this.lineage.map((item) => item.toJSON()), version: this.version.value }; }
  private assertRunning(): void { if (this.executionStatus !== "RUNNING") throw new InvariantViolation(`Execution cannot be changed from ${this.executionStatus}`); }
  private emit(eventType: new (props: import("./WorkforceEvents.js").WorkforceEventProps) => import("./WorkforceEvents.js").WorkforceDomainEvent, command: { occurredAt: string; correlationId: CorrelationId; causationId?: CausationId; evidence: readonly EvidenceReference[]; lineage: readonly LineageReference[] }, payload: JsonObject = {}): void { this.recordEvent(new eventType({ aggregateId: this.id.toString(), tenantId: this.tenantId, occurredAt: command.occurredAt, version: this.version, correlationId: command.correlationId.toString(), ...(command.causationId ? { causationId: command.causationId.toString() } : {}), evidenceIds: command.evidence.map((item) => item.evidenceId.toString()), lineage: command.lineage.map((item) => item.toJSON()), payload })); }
}
