import { institutionalAssetsCreateAsset, institutionalAssetsGetAsset, institutionalAssetsListAssets, institutionalAssetsRegisterAsset, institutionalAssetsRetireAsset } from "@bba/api-client";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useCallback } from "react";
import type { CommandIntent } from "../commands/command-types.js";
import { commandHeaders, executeCommand, requireReady, type GeneratedCommandResponse } from "../commands/execute-command.js";
import { useCommandIntent } from "../commands/use-command-intent.js";
import { BbaSdkError, normalizeSdkError } from "../errors/BbaSdkError.js";
import type { EvidenceInput, LineageInput } from "../missions/mission-commands.js";
import { useBbaSdkRuntime, type ReadySdkRuntime } from "../provider/BbaSdkProvider.js";
import { assetKeys, type ProductFilter } from "../query-keys/product-keys.js";

export interface AssetAuditInput { readonly occurredAt: string; readonly evidence: readonly EvidenceInput[]; readonly lineage: readonly LineageInput[]; }
export interface AssetCreateInput extends AssetAuditInput { readonly assetId: string; readonly initialVersionId: string; readonly missionId: string; readonly authorityDecisionId: string; readonly metadata: { readonly title: string; readonly summary: string; readonly purpose: string; readonly createdAt: string; readonly updatedAt: string }; readonly classification: { readonly primaryCategory: string; readonly secondaryCategories: readonly string[]; readonly sensitivity: "PUBLIC" | "INTERNAL" | "CONFIDENTIAL" | "RESTRICTED"; readonly tags: readonly string[] }; readonly authorityContext: { readonly ownerReference: string; readonly stewardReference: string; readonly custodianReference: string; readonly authorReferences: readonly string[]; readonly decisionId?: string }; readonly content: { readonly meaning: string; readonly text: string; readonly language?: string }; }
export interface AssetRetireInput extends AssetAuditInput { readonly assetId: string; readonly authorityId: string; readonly decisionId: string; }
export interface AssetView { readonly id: string; readonly tenantId: string; readonly missionId: string; readonly status: string; readonly currentVersionId: string; readonly versionCount: number; readonly version: number; }
export interface AssetSummaryView { readonly id: string; readonly tenantId: string; readonly status: string; readonly currentVersionId: string; readonly version: number; }
type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };
const audit = (value: AssetAuditInput): { [key: string]: JsonValue } => ({ occurredAt: value.occurredAt, evidence: value.evidence.map((item) => ({ ...item })), lineage: value.lineage.map((item) => ({ ...item })) });
function createData(input: AssetCreateInput, tenantId: string): { [key: string]: JsonValue } { const actor = (reference: string) => ({ reference, tenantId }); return { assetId: input.assetId, initialVersionId: input.initialVersionId, missionId: input.missionId, authorityDecisionId: input.authorityDecisionId, metadata: { ...input.metadata }, classification: { ...input.classification, secondaryCategories: [...input.classification.secondaryCategories], tags: [...input.classification.tags] }, authorityContext: { ownerReference: actor(input.authorityContext.ownerReference), stewardReference: actor(input.authorityContext.stewardReference), custodianReference: actor(input.authorityContext.custodianReference), authorReferences: input.authorityContext.authorReferences.map(actor), ...(input.authorityContext.decisionId === undefined ? {} : { decisionReference: { id: input.authorityContext.decisionId, tenantId } }) }, content: { meaning: input.content.meaning, data: { text: input.content.text }, ...(input.content.language === undefined ? {} : { language: input.content.language }) }, ...audit(input) }; }
function useAssetCommand<T>(operationId: string, id: (value: T) => string, invoke: (runtime: ReadySdkRuntime, intent: CommandIntent<T>) => Promise<GeneratedCommandResponse>) { const runtime = useBbaSdkRuntime(); const queryClient = useQueryClient(); const execute = useCallback((intent: CommandIntent<T>) => { const ready = requireReady(runtime.ready); return executeCommand(ready, queryClient, operationId, intent, () => invoke(ready, intent), { primaryId: id(intent.payload) }); }, [id, invoke, operationId, queryClient, runtime.ready]); return useCommandIntent(execute); }
export function useInstitutionalAssetsCreateAssetCommand() { return useAssetCommand<AssetCreateInput>("institutionalAssetsCreateAsset", (v) => v.assetId, (r, i) => institutionalAssetsCreateAsset({ client: r.client, headers: commandHeaders(r, i), body: { data: { assetId: i.payload.assetId, ...createData(i.payload, r.tenantId) }, meta: { reason: i.reason } } })); }
export function useInstitutionalAssetsRegisterAssetCommand() { return useAssetCommand<AssetCreateInput>("institutionalAssetsRegisterAsset", (v) => v.assetId, (r, i) => institutionalAssetsRegisterAsset({ client: r.client, headers: commandHeaders(r, i), body: { data: { assetId: i.payload.assetId, ...createData(i.payload, r.tenantId) }, meta: { reason: i.reason } } })); }
export function useInstitutionalAssetsRetireAssetCommand() { return useAssetCommand<AssetRetireInput>("institutionalAssetsRetireAsset", (v) => v.assetId, (r, i) => institutionalAssetsRetireAsset({ client: r.client, path: { assetId: i.payload.assetId }, headers: commandHeaders(r, i), body: { data: { assetId: i.payload.assetId, authorityId: i.payload.authorityId, decisionId: i.payload.decisionId, ...audit(i.payload) }, meta: { reason: i.reason } } })); }
const publicError = (value: unknown) => value instanceof BbaSdkError ? value : value === null ? undefined : normalizeSdkError(undefined, value);
export function useInstitutionalAssetsGetAssetQuery(assetId: string) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; const query = useQuery({ queryKey: assetKeys.detail(tenant, assetId), enabled: runtime.ready !== null && assetId.trim().length > 0, queryFn: async (): Promise<AssetView> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await institutionalAssetsGetAsset({ client: runtime.ready.client, path: { assetId }, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); const value = response.data.data; return { id: value.assetId, tenantId: value.tenantId, missionId: value.missionReference.id, status: value.status, currentVersionId: value.currentVersionId, versionCount: value.versionCount, version: value.version }; } }); return { data: query.data, error: publicError(query.error), isPending: query.isPending }; }
export function useInstitutionalAssetsListAssetsQuery(filter: ProductFilter = {}) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; const query = useQuery({ queryKey: assetKeys.list(tenant, filter), enabled: runtime.ready !== null, queryFn: async (): Promise<readonly AssetSummaryView[]> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await institutionalAssetsListAssets({ client: runtime.ready.client, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); return response.data.data.map((value) => ({ id: value.assetId, tenantId: value.tenantId, status: value.status, currentVersionId: value.currentVersionId, version: value.version })); } }); return { data: query.data, error: publicError(query.error), isPending: query.isPending }; }
