import { reviewArchiveReview, reviewCancelSession, reviewCloseSession, reviewCompleteReview, reviewCreateReview, reviewGetReview, reviewOpenSession, reviewPlanSession, reviewRecordFinding, reviewStartReview } from "@bba/api-client";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useCallback } from "react";
import type { CommandIntent } from "../commands/command-types.js";
import { commandHeaders, executeCommand, requireReady, type GeneratedCommandResponse } from "../commands/execute-command.js";
import { useCommandIntent } from "../commands/use-command-intent.js";
import { BbaSdkError, normalizeSdkError } from "../errors/BbaSdkError.js";
import type { EvidenceInput, LineageInput } from "../missions/mission-commands.js";
import { useBbaSdkRuntime, type ReadySdkRuntime } from "../provider/BbaSdkProvider.js";
import { reviewKeys } from "../query-keys/product-keys.js";
export interface ReviewAuditInput { readonly occurredAt: string; readonly evidence: readonly EvidenceInput[]; readonly lineage: readonly LineageInput[]; }
export interface CreateReviewInput extends ReviewAuditInput { readonly reviewId: string; readonly requestId: string; readonly missionId: string; readonly targetKind: "asset" | "asset_version" | "knowledge" | "policy"; readonly targetId: string; readonly targetVersionId?: string; readonly reviewType: string; readonly criteria: readonly string[]; readonly requestedBy: string; readonly requestedAt: string; }
export interface ReviewActionInput extends ReviewAuditInput { readonly reviewId: string; readonly sessionId?: string; readonly reviewerReferences?: readonly string[]; readonly findingId?: string; readonly statement?: string; readonly category?: string; readonly severity?: string; readonly recommendation?: string; readonly conclusionId?: string; readonly outcome?: string; readonly rationale?: string; }
export interface ReviewView { readonly id: string; readonly tenantId: string; readonly status: string; readonly version: number; }
type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };
const audit = (value: ReviewAuditInput): { [key: string]: JsonValue } => ({ occurredAt: value.occurredAt, evidence: value.evidence.map((item) => ({ ...item })), lineage: value.lineage.map((item) => ({ ...item })) });
function useReviewCommand<T>(operationId: string, id: (value: T) => string, invoke: (runtime: ReadySdkRuntime, intent: CommandIntent<T>) => Promise<GeneratedCommandResponse>) { const runtime = useBbaSdkRuntime(); const queryClient = useQueryClient(); const execute = useCallback((intent: CommandIntent<T>) => { const ready = requireReady(runtime.ready); return executeCommand(ready, queryClient, operationId, intent, () => invoke(ready, intent), { primaryId: id(intent.payload) }); }, [id, invoke, operationId, queryClient, runtime.ready]); return useCommandIntent(execute); }
const actionData = (input: ReviewActionInput, tenantId: string): { [key: string]: JsonValue } => ({ reviewId: input.reviewId, ...(input.sessionId === undefined ? {} : { sessionId: input.sessionId }), ...(input.reviewerReferences === undefined ? {} : { reviewerReferences: input.reviewerReferences.map((reference) => ({ reference, tenantId })) }), ...(input.findingId === undefined ? {} : { findingId: input.findingId }), ...(input.statement === undefined ? {} : { statement: input.statement }), ...(input.category === undefined ? {} : { category: input.category }), ...(input.severity === undefined ? {} : { severity: input.severity }), ...(input.recommendation === undefined ? {} : { recommendation: input.recommendation }), ...(input.conclusionId === undefined ? {} : { conclusionId: input.conclusionId }), ...(input.outcome === undefined ? {} : { outcome: input.outcome }), ...(input.rationale === undefined ? {} : { rationale: input.rationale }), ...audit(input) });
export function useReviewCreateReviewCommand() { return useReviewCommand<CreateReviewInput>("reviewCreateReview", (v) => v.reviewId, (r, i) => { const target = i.payload.targetKind === "asset_version" ? { kind: "asset_version", reference: { assetId: i.payload.targetId, versionId: i.payload.targetVersionId ?? "", tenantId: r.tenantId } } : { kind: i.payload.targetKind, reference: { id: i.payload.targetId, tenantId: r.tenantId } }; return reviewCreateReview({ client: r.client, headers: commandHeaders(r, i), body: { data: { reviewId: i.payload.reviewId, requestId: i.payload.requestId, missionReference: { id: i.payload.missionId, tenantId: r.tenantId }, scope: { tenantId: r.tenantId, targets: [target] }, reviewType: i.payload.reviewType, criteria: [...i.payload.criteria], requestedBy: { reference: i.payload.requestedBy, tenantId: r.tenantId }, requestedAt: i.payload.requestedAt, ...audit(i.payload) }, meta: { reason: i.reason } } }); }); }
function reviewAction(operationId: string, call: typeof reviewStartReview) { return function useAction() { return useReviewCommand<ReviewActionInput>(operationId, (v) => v.reviewId, (r, i) => call({ client: r.client, path: { reviewId: i.payload.reviewId }, headers: commandHeaders(r, i), body: { data: actionData(i.payload, r.tenantId), meta: { reason: i.reason } } })); }; }
export const useReviewStartReviewCommand = reviewAction("reviewStartReview", reviewStartReview); export const useReviewPlanSessionCommand = reviewAction("reviewPlanSession", reviewPlanSession); export const useReviewOpenSessionCommand = reviewAction("reviewOpenSession", reviewOpenSession); export const useReviewRecordFindingCommand = reviewAction("reviewRecordFinding", reviewRecordFinding); export const useReviewCloseSessionCommand = reviewAction("reviewCloseSession", reviewCloseSession); export const useReviewCancelSessionCommand = reviewAction("reviewCancelSession", reviewCancelSession); export const useReviewCompleteReviewCommand = reviewAction("reviewCompleteReview", reviewCompleteReview); export const useReviewArchiveReviewCommand = reviewAction("reviewArchiveReview", reviewArchiveReview);
const publicError = (value: unknown) => value instanceof BbaSdkError ? value : value === null ? undefined : normalizeSdkError(undefined, value);
export function useReviewGetReviewQuery(id: string) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; const query = useQuery({ queryKey: reviewKeys.detail(tenant, id), enabled: runtime.ready !== null && id.trim().length > 0, queryFn: async (): Promise<ReviewView> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await reviewGetReview({ client: runtime.ready.client, path: { reviewId: id }, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); const v = response.data.data; return { id: v.reviewId, tenantId: v.tenantId, status: v.status, version: v.version }; } }); return { data: query.data, error: publicError(query.error), isPending: query.isPending }; }
