import { publicationArchivePublication, publicationAuthorizePublication, publicationCreatePublication, publicationGetPublication, publicationPreparePublication, publicationRecordPublicationOutcome } from "@bba/api-client";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useCallback } from "react";
import type { CommandIntent } from "../commands/command-types.js";
import { commandHeaders, executeCommand, requireReady, type GeneratedCommandResponse } from "../commands/execute-command.js";
import { useCommandIntent } from "../commands/use-command-intent.js";
import { BbaSdkError, normalizeSdkError } from "../errors/BbaSdkError.js";
import type { EvidenceInput, LineageInput } from "../missions/mission-commands.js";
import { useBbaSdkRuntime, type ReadySdkRuntime } from "../provider/BbaSdkProvider.js";
import { publicationKeys } from "../query-keys/product-keys.js";
export interface PublicationAuditInput { readonly occurredAt: string; readonly evidence: readonly EvidenceInput[]; readonly lineage: readonly LineageInput[]; }
export interface CreatePublicationInput extends PublicationAuditInput { readonly publicationId: string; readonly packageId: string; readonly missionId: string; readonly assetId: string; readonly assetVersionId: string; readonly destination: { readonly key: string; readonly audience: string; readonly purpose: string }; readonly knowledgeIds: readonly string[]; readonly title: string; }
export interface PublicationActionInput extends PublicationAuditInput { readonly publicationId: string; readonly reviewId?: string; readonly publicationVersionId?: string; readonly observationBatchKey?: string; readonly observation?: { readonly recordId: string; readonly connectorId: string; readonly destinationKey: string; readonly result: string; readonly observedAt: string; readonly externalIdentifier?: string; readonly failureReason?: string; readonly evidence: readonly EvidenceInput[] }; }
export interface PublicationView { readonly id: string; readonly tenantId: string; readonly status: string; readonly version: number; }
type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };
const audit = (value: PublicationAuditInput): { [key: string]: JsonValue } => ({ occurredAt: value.occurredAt, evidence: value.evidence.map((item) => ({ ...item })), lineage: value.lineage.map((item) => ({ ...item })) });
function usePublicationCommand<T>(operationId: string, id: (value: T) => string, invoke: (runtime: ReadySdkRuntime, intent: CommandIntent<T>) => Promise<GeneratedCommandResponse>) { const runtime = useBbaSdkRuntime(); const queryClient = useQueryClient(); const execute = useCallback((intent: CommandIntent<T>) => { const ready = requireReady(runtime.ready); return executeCommand(ready, queryClient, operationId, intent, () => invoke(ready, intent), { primaryId: id(intent.payload) }); }, [id, invoke, operationId, queryClient, runtime.ready]); return useCommandIntent(execute); }
export function usePublicationCreatePublicationCommand() { return usePublicationCommand<CreatePublicationInput>("publicationCreatePublication", (v) => v.publicationId, (r, i) => publicationCreatePublication({ client: r.client, headers: commandHeaders(r, i), body: { data: { publicationId: i.payload.publicationId, packageId: i.payload.packageId, missionReference: { id: i.payload.missionId, tenantId: r.tenantId }, items: [{ assetReference: { id: i.payload.assetId, tenantId: r.tenantId }, assetVersionReference: { assetId: i.payload.assetId, versionId: i.payload.assetVersionId, tenantId: r.tenantId } }], destinations: [{ ...i.payload.destination }], knowledgeReferences: i.payload.knowledgeIds.map((id) => ({ id, tenantId: r.tenantId })), metadata: { title: i.payload.title }, ...audit(i.payload) }, meta: { reason: i.reason } } })); }
function publicationAction(operationId: string, call: typeof publicationPreparePublication) { return function useAction() { return usePublicationCommand<PublicationActionInput>(operationId, (v) => v.publicationId, (r, i) => call({ client: r.client, path: { publicationId: i.payload.publicationId }, headers: commandHeaders(r, i), body: { data: { publicationId: i.payload.publicationId, ...(i.payload.reviewId === undefined ? {} : { reviewReference: { id: i.payload.reviewId, tenantId: r.tenantId } }), ...(i.payload.publicationVersionId === undefined ? {} : { publicationVersionId: i.payload.publicationVersionId }), ...(i.payload.observationBatchKey === undefined ? {} : { observationBatchKey: i.payload.observationBatchKey }), ...(i.payload.observation === undefined ? {} : { observations: [{ ...i.payload.observation, connectorReference: { id: i.payload.observation.connectorId, tenantId: r.tenantId }, evidence: i.payload.observation.evidence.map((v) => ({ ...v })) }] }), ...audit(i.payload) }, meta: { reason: i.reason } } })); }; }
export const usePublicationPreparePublicationCommand = publicationAction("publicationPreparePublication", publicationPreparePublication); export const usePublicationAuthorizePublicationCommand = publicationAction("publicationAuthorizePublication", publicationAuthorizePublication); export const usePublicationRecordPublicationOutcomeCommand = publicationAction("publicationRecordPublicationOutcome", publicationRecordPublicationOutcome); export const usePublicationArchivePublicationCommand = publicationAction("publicationArchivePublication", publicationArchivePublication);
const publicError = (value: unknown) => value instanceof BbaSdkError ? value : value === null ? undefined : normalizeSdkError(undefined, value);
export function usePublicationGetPublicationQuery(id: string) { const runtime = useBbaSdkRuntime(); const tenant = runtime.ready?.tenantId ?? "unresolved"; const query = useQuery({ queryKey: publicationKeys.detail(tenant, id), enabled: runtime.ready !== null && id.trim().length > 0, queryFn: async (): Promise<PublicationView> => { if (runtime.ready === null) throw new BbaSdkError("CONFIGURATION_MISSING", "SDK unavailable", undefined, undefined, undefined); const response = await publicationGetPublication({ client: runtime.ready.client, path: { publicationId: id }, headers: { "X-Tenant-Id": runtime.ready.tenantId } }); if (response.error !== undefined) throw normalizeSdkError(response.response?.status, response.error); const v = response.data.data; return { id: v.publicationId, tenantId: v.tenantId, status: v.status, version: v.version }; } }); return { data: query.data, error: publicError(query.error), isPending: query.isPending }; }
