import { AggregateRoot } from "../../../shared/aggregate/AggregateRoot.js";
import type { CausationId, CorrelationId, JsonObject } from "../../../shared/common/index.js";
import { InvariantViolation } from "../../../shared/errors/InvariantViolation.js";
import type { EvidenceReference } from "../../../shared/evidence/EvidenceReference.js";
import { KnowledgeId, TenantId } from "../../../shared/identity/index.js";
import type { LineageReference } from "../../../shared/lineage/LineageReference.js";
import { AssetReference, AssetVersionReference, DecisionReference, KnowledgeReference, PolicyReference } from "../../../shared/references/index.js";
import { Version } from "../../../shared/version/Version.js";
import type { ArchiveKnowledgeCommand, CreateKnowledgeCommand, CurateKnowledgeCommand, KnowledgePolicyAuditInput, LinkKnowledgeCommand, SupersedeKnowledgeCommand } from "./KnowledgePolicyCommands.js";
import { KnowledgeArchived, KnowledgeCreated, KnowledgeCurated, KnowledgeLinked, KnowledgePolicyDomainEvent, KnowledgeSuperseded } from "./KnowledgePolicyEvents.js";
import { evidenceFromJSON, lineageFromJSON } from "./KnowledgePolicySerialization.js";
import { KnowledgeMetadata } from "./KnowledgeMetadata.js";
import { KnowledgeRelationship } from "./KnowledgeRelationship.js";
import { KnowledgeRevisionNumber } from "./KnowledgeRevisionNumber.js";
import { KnowledgeScope } from "./KnowledgeScope.js";
import type { KnowledgeStatus } from "./KnowledgeStatus.js";

export interface KnowledgeSnapshot { readonly schemaVersion: 1; readonly knowledgeId: string; readonly tenantId: string; readonly metadata: JsonObject; readonly scope: JsonObject; readonly status: KnowledgeStatus; readonly currentRevision: number; readonly assetReferences: readonly JsonObject[]; readonly assetVersionReferences: readonly JsonObject[]; readonly policyReferences: readonly JsonObject[]; readonly relationships: readonly JsonObject[]; readonly supersededBy: JsonObject | null; readonly evidence: readonly JsonObject[]; readonly lineage: readonly JsonObject[]; readonly version: number; }
const STATUS = new Set<KnowledgeStatus>(["PROPOSED", "CURATED", "ARCHIVED", "SUPERSEDED"]);

export class Knowledge extends AggregateRoot<KnowledgeId> {
  private readonly knowledgeTenantId: TenantId; private knowledgeMetadata: KnowledgeMetadata; private readonly knowledgeScope: KnowledgeScope; private knowledgeStatus: KnowledgeStatus; private knowledgeCurrentRevision: KnowledgeRevisionNumber; private knowledgeAssetReferences: AssetReference[]; private knowledgeAssetVersionReferences: AssetVersionReference[]; private knowledgePolicyReferences: PolicyReference[]; private knowledgeRelationships: KnowledgeRelationship[]; private knowledgeSupersededBy: KnowledgeReference | null; private knowledgeEvidence: EvidenceReference[]; private knowledgeLineage: LineageReference[];
  private constructor(id: KnowledgeId, state: { tenantId: TenantId; metadata: KnowledgeMetadata; scope: KnowledgeScope; status: KnowledgeStatus; currentRevision: KnowledgeRevisionNumber; assetReferences: AssetReference[]; assetVersionReferences: AssetVersionReference[]; policyReferences: PolicyReference[]; relationships: KnowledgeRelationship[]; supersededBy: KnowledgeReference | null; evidence: EvidenceReference[]; lineage: LineageReference[]; version: Version }) {
    super(id, state.version);
    if (!STATUS.has(state.status)) throw new InvariantViolation("Knowledge status is not canonical");
    this.knowledgeTenantId = state.tenantId; this.knowledgeMetadata = state.metadata; this.knowledgeScope = state.scope; this.knowledgeStatus = state.status; this.knowledgeCurrentRevision = state.currentRevision; this.knowledgeAssetReferences = [...state.assetReferences]; this.knowledgeAssetVersionReferences = [...state.assetVersionReferences]; this.knowledgePolicyReferences = [...state.policyReferences]; this.knowledgeRelationships = [...state.relationships]; this.knowledgeSupersededBy = state.supersededBy; this.knowledgeEvidence = [...state.evidence]; this.knowledgeLineage = [...state.lineage]; this.assertState();
  }
  public static create(command: CreateKnowledgeCommand): Knowledge {
    const knowledge = new Knowledge(command.knowledgeId, { tenantId: command.tenantId, metadata: command.metadata, scope: command.scope, status: "PROPOSED", currentRevision: KnowledgeRevisionNumber.initial(), assetReferences: [...command.assetReferences], assetVersionReferences: [...command.assetVersionReferences], policyReferences: [...command.policyReferences], relationships: [], supersededBy: null, evidence: [...command.evidence], lineage: [...command.lineage], version: Version.initial() });
    knowledge.requireAudit(command); knowledge.incrementVersion(); knowledge.emit(KnowledgeCreated, command, { status: "PROPOSED", currentRevision: knowledge.currentRevision.value }); return knowledge;
  }
  public static rehydrate(snapshot: KnowledgeSnapshot): Knowledge {
    if (snapshot.schemaVersion !== 1) throw new InvariantViolation("Unsupported Knowledge snapshot schema");
    return new Knowledge(KnowledgeId.from(snapshot.knowledgeId), { tenantId: TenantId.from(snapshot.tenantId), metadata: KnowledgeMetadata.fromJSON(snapshot.metadata), scope: KnowledgeScope.fromJSON(snapshot.scope), status: snapshot.status, currentRevision: new KnowledgeRevisionNumber(snapshot.currentRevision), assetReferences: snapshot.assetReferences.map((item) => AssetReference.fromJSON(item as { id: string; tenantId: string })), assetVersionReferences: snapshot.assetVersionReferences.map((item) => AssetVersionReference.fromJSON(item as { assetId: string; versionId: string; tenantId: string })), policyReferences: snapshot.policyReferences.map((item) => PolicyReference.fromJSON(item as { id: string; tenantId: string })), relationships: snapshot.relationships.map((item) => KnowledgeRelationship.fromJSON(item)), supersededBy: snapshot.supersededBy ? KnowledgeReference.fromJSON(snapshot.supersededBy as { id: string; tenantId: string }) : null, evidence: snapshot.evidence.map((item) => evidenceFromJSON(item)), lineage: snapshot.lineage.map((item) => lineageFromJSON(item)), version: Version.from(snapshot.version) });
  }
  public get tenantId(): TenantId { return this.knowledgeTenantId; } public get metadata(): KnowledgeMetadata { return this.knowledgeMetadata; } public get scope(): KnowledgeScope { return this.knowledgeScope; } public get status(): KnowledgeStatus { return this.knowledgeStatus; } public get currentRevision(): KnowledgeRevisionNumber { return this.knowledgeCurrentRevision; } public get assetReferences(): readonly AssetReference[] { return [...this.knowledgeAssetReferences]; } public get assetVersionReferences(): readonly AssetVersionReference[] { return [...this.knowledgeAssetVersionReferences]; } public get policyReferences(): readonly PolicyReference[] { return [...this.knowledgePolicyReferences]; } public get relationships(): readonly KnowledgeRelationship[] { return [...this.knowledgeRelationships]; } public get supersededBy(): KnowledgeReference | null { return this.knowledgeSupersededBy; } public get evidence(): readonly EvidenceReference[] { return [...this.knowledgeEvidence]; } public get lineage(): readonly LineageReference[] { return [...this.knowledgeLineage]; }
  public get reference(): KnowledgeReference { return new KnowledgeReference(this.id, this.tenantId); }
  public curate(command: CurateKnowledgeCommand): void { if (this.status !== "PROPOSED") throw new InvariantViolation(`Knowledge cannot be curated from ${this.status}`); this.assertDecisionTenant(command.curatorReference); this.knowledgeStatus = "CURATED"; this.semanticMutation(command); this.emit(KnowledgeCurated, command, { currentRevision: this.currentRevision.value }); }
  public archive(command: ArchiveKnowledgeCommand): void { if (this.status !== "CURATED") throw new InvariantViolation(`Knowledge cannot be archived from ${this.status}`); this.assertDecisionTenant(command.decisionReference); this.knowledgeStatus = "ARCHIVED"; this.semanticMutation(command); this.emit(KnowledgeArchived, command); }
  public supersede(command: SupersedeKnowledgeCommand): void { if (this.status !== "CURATED") throw new InvariantViolation(`Knowledge cannot be superseded from ${this.status}`); this.assertDecisionTenant(command.decisionReference); if (!command.successorReference.tenantId.equals(this.tenantId) || command.successorReference.id.equals(this.id)) throw new InvariantViolation("Knowledge successor must be distinct and intra-Tenant"); this.knowledgeSupersededBy = command.successorReference; this.knowledgeStatus = "SUPERSEDED"; this.semanticMutation(command); this.emit(KnowledgeSuperseded, command, { successorKnowledgeId: command.successorReference.id.toString() }); }
  public link(command: LinkKnowledgeCommand): void { const relationship = command.relationship; if (!relationship.source.id.equals(this.id) || !relationship.source.tenantId.equals(this.tenantId)) throw new InvariantViolation("KnowledgeRelationship source must match its Aggregate owner"); if (this.knowledgeRelationships.some((item) => item.type === relationship.type && item.targetKey === relationship.targetKey)) throw new InvariantViolation("KnowledgeRelationship already exists"); this.addReferenceFor(relationship); this.knowledgeRelationships = [...this.knowledgeRelationships, relationship]; this.semanticMutation(command); this.emit(KnowledgeLinked, command, { relationshipType: relationship.type, target: relationship.target.toJSON() }); }
  public toSnapshot(): KnowledgeSnapshot { return { schemaVersion: 1, knowledgeId: this.id.toString(), tenantId: this.tenantId.toString(), metadata: this.metadata.toJSON(), scope: this.scope.toJSON(), status: this.status, currentRevision: this.currentRevision.value, assetReferences: this.assetReferences.map((item) => item.toJSON()), assetVersionReferences: this.assetVersionReferences.map((item) => item.toJSON()), policyReferences: this.policyReferences.map((item) => item.toJSON()), relationships: this.relationships.map((item) => item.toJSON()), supersededBy: this.supersededBy?.toJSON() ?? null, evidence: this.evidence.map((item) => item.toJSON()), lineage: this.lineage.map((item) => item.toJSON()), version: this.version.value }; }
  private addReferenceFor(relationship: KnowledgeRelationship): void { const target = relationship.target; if (target instanceof AssetVersionReference && !this.knowledgeAssetVersionReferences.some((item) => item.equals(target))) this.knowledgeAssetVersionReferences = [...this.knowledgeAssetVersionReferences, target]; else if (target instanceof AssetReference && !this.knowledgeAssetReferences.some((item) => item.equals(target))) this.knowledgeAssetReferences = [...this.knowledgeAssetReferences, target]; else if (target instanceof PolicyReference && !this.knowledgePolicyReferences.some((item) => item.equals(target))) this.knowledgePolicyReferences = [...this.knowledgePolicyReferences, target]; }
  private semanticMutation(command: KnowledgePolicyAuditInput): void { this.requireAudit(command); this.knowledgeCurrentRevision = this.knowledgeCurrentRevision.increment(); this.knowledgeEvidence = [...this.knowledgeEvidence, ...command.evidence]; this.knowledgeLineage = [...this.knowledgeLineage, ...command.lineage]; this.incrementVersion(); }
  private requireAudit(command: KnowledgePolicyAuditInput): void { if (command.reason.trim().length === 0 || command.evidence.length === 0 || command.lineage.length === 0) throw new InvariantViolation("Knowledge mutation requires reason, Evidence and Lineage"); }
  private assertDecisionTenant(reference: DecisionReference): void { if (!reference.tenantId.equals(this.tenantId)) throw new InvariantViolation("Knowledge decision crossed a Tenant boundary"); }
  private assertState(): void { if (this.knowledgeEvidence.length === 0 || this.knowledgeLineage.length === 0) throw new InvariantViolation("Knowledge requires Evidence and Lineage"); for (const reference of [...this.assetReferences, ...this.assetVersionReferences, ...this.policyReferences, ...this.relationships.map((item) => item.source), ...this.relationships.map((item) => item.target)]) if (!reference.tenantId.equals(this.tenantId)) throw new InvariantViolation("Knowledge references must remain Tenant-bound"); if (this.status === "SUPERSEDED" && this.supersededBy === null) throw new InvariantViolation("Superseded Knowledge requires a successor"); }
  private emit(eventType: new (props: import("./KnowledgePolicyEvents.js").KnowledgePolicyEventProps) => KnowledgePolicyDomainEvent, command: KnowledgePolicyAuditInput & { readonly correlationId: CorrelationId; readonly causationId?: CausationId }, payload: JsonObject = {}): void { this.recordEvent(new eventType({ aggregateId: this.id.toString(), tenantId: this.tenantId, occurredAt: command.occurredAt, version: this.version, correlationId: command.correlationId.toString(), ...(command.causationId ? { causationId: command.causationId.toString() } : {}), evidenceIds: command.evidence.map((item) => item.evidenceId.toString()), lineage: command.lineage.map((item) => item.toJSON()), payload })); }
}
