import { AggregateRoot } from "../../../shared/aggregate/AggregateRoot.js";
import type { CausationId, CorrelationId, JsonObject } from "../../../shared/common/index.js";
import { InvariantViolation } from "../../../shared/errors/InvariantViolation.js";
import { PolicyId, PolicyVersionId, TenantId } from "../../../shared/identity/index.js";
import { Version } from "../../../shared/version/Version.js";
import type { CreatePolicyCommand, CreatePolicyVersionCommand, GovernedPolicyAuditInput } from "./KnowledgePolicyCommands.js";
import { KnowledgePolicyDomainEvent, PolicyCreated, PolicyVersionCreated } from "./KnowledgePolicyEvents.js";
import { PolicyAuthorityContext } from "./PolicyAuthorityContext.js";
import { PolicyMetadata } from "./PolicyMetadata.js";
import type { PolicyStatus } from "./PolicyStatus.js";
import { PolicyVersion } from "./PolicyVersion.js";
import { PolicyVersionNumber } from "./PolicyVersionNumber.js";

export interface PolicySnapshot { readonly schemaVersion: 1; readonly policyId: string; readonly tenantId: string; readonly metadata: JsonObject; readonly authorityContext: JsonObject; readonly status: PolicyStatus; readonly versions: readonly JsonObject[]; readonly currentVersionId: string; readonly version: number; }
const STATUS = new Set<PolicyStatus>(["PROPOSED", "ACTIVE", "SUPERSEDED", "ARCHIVED"]);

export class Policy extends AggregateRoot<PolicyId> {
  private readonly policyTenantId: TenantId; private readonly policyMetadata: PolicyMetadata; private readonly policyAuthorityContext: PolicyAuthorityContext; private readonly policyStatus: PolicyStatus; private policyVersions: PolicyVersion[]; private policyCurrentVersionId: PolicyVersionId;
  private constructor(id: PolicyId, state: { tenantId: TenantId; metadata: PolicyMetadata; authorityContext: PolicyAuthorityContext; status: PolicyStatus; versions: PolicyVersion[]; currentVersionId: PolicyVersionId; version: Version }) {
    super(id, state.version);
    if (!STATUS.has(state.status)) throw new InvariantViolation("Policy status is not canonical");
    if (!state.authorityContext.tenantId.equals(state.tenantId)) throw new InvariantViolation("Policy authority context crossed a Tenant boundary");
    this.policyTenantId = state.tenantId; this.policyMetadata = state.metadata; this.policyAuthorityContext = state.authorityContext; this.policyStatus = state.status; this.policyVersions = [...state.versions]; this.policyCurrentVersionId = state.currentVersionId; this.assertState();
  }
  public static create(command: CreatePolicyCommand): Policy {
    const version = new PolicyVersion({ id: command.initialVersionId, policyId: command.policyId, tenantId: command.tenantId, number: PolicyVersionNumber.initial(), ruleSet: command.ruleSet, reason: command.reason, authorityDecisionReference: command.decisionReference, evidence: command.evidence, lineage: command.lineage, createdAt: command.occurredAt });
    const policy = new Policy(command.policyId, { tenantId: command.tenantId, metadata: command.metadata, authorityContext: command.authorityContext, status: "PROPOSED", versions: [version], currentVersionId: version.id, version: Version.initial() });
    policy.requireGovernedAudit(command); policy.incrementVersion(); policy.emit(PolicyCreated, command, { status: "PROPOSED", currentVersionId: version.id.toString() }); policy.emit(PolicyVersionCreated, command, { versionId: version.id.toString(), number: 1 }); return policy;
  }
  public static rehydrate(snapshot: PolicySnapshot): Policy {
    if (snapshot.schemaVersion !== 1) throw new InvariantViolation("Unsupported Policy snapshot schema");
    return new Policy(PolicyId.from(snapshot.policyId), { tenantId: TenantId.from(snapshot.tenantId), metadata: PolicyMetadata.fromJSON(snapshot.metadata), authorityContext: PolicyAuthorityContext.fromJSON(snapshot.authorityContext), status: snapshot.status, versions: snapshot.versions.map((item) => PolicyVersion.fromSnapshot(item)), currentVersionId: PolicyVersionId.from(snapshot.currentVersionId), version: Version.from(snapshot.version) });
  }
  public get tenantId(): TenantId { return this.policyTenantId; } public get metadata(): PolicyMetadata { return this.policyMetadata; } public get authorityContext(): PolicyAuthorityContext { return this.policyAuthorityContext; } public get status(): PolicyStatus { return this.policyStatus; } public get versions(): readonly PolicyVersion[] { return [...this.policyVersions]; } public get currentVersionId(): PolicyVersionId { return this.policyCurrentVersionId; } public get currentPolicyVersion(): PolicyVersion { const version = this.policyVersions.find((item) => item.id.equals(this.currentVersionId)); if (version === undefined) throw new InvariantViolation("Policy current version is missing"); return version; }
  public createVersion(command: CreatePolicyVersionCommand): PolicyVersion { this.requireGovernedAudit(command); if (!command.predecessorVersionId.equals(this.currentVersionId)) throw new InvariantViolation("PolicyVersion predecessor must be current"); if (this.policyVersions.some((item) => item.id.equals(command.versionId))) throw new InvariantViolation("PolicyVersionId already exists"); const version = new PolicyVersion({ id: command.versionId, policyId: this.id, tenantId: this.tenantId, number: this.currentPolicyVersion.number.next(), ruleSet: command.ruleSet, predecessorVersionId: this.currentVersionId, reason: command.reason, authorityDecisionReference: command.decisionReference, evidence: command.evidence, lineage: command.lineage, createdAt: command.occurredAt }); this.policyVersions = [...this.policyVersions, version]; this.policyCurrentVersionId = version.id; this.incrementVersion(); this.emit(PolicyVersionCreated, command, { versionId: version.id.toString(), predecessorVersionId: command.predecessorVersionId.toString(), number: version.number.value }); this.assertState(); return version; }
  public toSnapshot(): PolicySnapshot { return { schemaVersion: 1, policyId: this.id.toString(), tenantId: this.tenantId.toString(), metadata: this.metadata.toJSON(), authorityContext: this.authorityContext.toJSON(), status: this.status, versions: this.versions.map((item) => item.toSnapshot()), currentVersionId: this.currentVersionId.toString(), version: this.version.value }; }
  private assertState(): void { if (this.policyVersions.length === 0) throw new InvariantViolation("Policy requires at least one version"); if (this.policyVersions.filter((item) => item.id.equals(this.currentVersionId)).length !== 1) throw new InvariantViolation("Policy must have exactly one current version"); const versionIds = new Set(this.policyVersions.map((item) => item.id.toString())); if (versionIds.size !== this.policyVersions.length) throw new InvariantViolation("PolicyVersionId must be unique"); if (this.policyVersions.some((item) => !item.policyId.equals(this.id) || !item.tenantId.equals(this.tenantId))) throw new InvariantViolation("PolicyVersion cannot cross Policy or Tenant boundaries"); }
  private requireGovernedAudit(command: GovernedPolicyAuditInput): void { if (command.reason.trim().length === 0 || command.evidence.length === 0 || command.lineage.length === 0) throw new InvariantViolation("Policy mutation requires reason, Evidence and Lineage"); if (!command.authorityReference.tenantId.equals(this.tenantId) || !command.decisionReference.tenantId.equals(this.tenantId)) throw new InvariantViolation("Policy authority context crossed a Tenant boundary"); }
  private emit(eventType: new (props: import("./KnowledgePolicyEvents.js").KnowledgePolicyEventProps) => KnowledgePolicyDomainEvent, command: GovernedPolicyAuditInput & { readonly correlationId: CorrelationId; readonly causationId?: CausationId }, payload: JsonObject = {}): void { this.recordEvent(new eventType({ aggregateId: this.id.toString(), tenantId: this.tenantId, occurredAt: command.occurredAt, version: this.version, correlationId: command.correlationId.toString(), ...(command.causationId ? { causationId: command.causationId.toString() } : {}), evidenceIds: command.evidence.map((item) => item.evidenceId.toString()), lineage: command.lineage.map((item) => item.toJSON()), payload })); }
}
