import { cloneElement, useState, type ReactElement, type ReactNode } from "react";
import { NavLink } from "react-router-dom";
import { translate } from "../../i18n/index.js";
import { useCreateStaticProject } from "../StaticPublisherProvider.js";
import type { Channel, PublisherDraft } from "../models.js";

const initial: PublisherDraft = { title: "", communicationNeed: "", objective: "", expectedOutcome: "", contentLanguage: "en-US", audience: "", centralMessage: "", tone: "Scientific, precise, and accessible", callToAction: "", textualMaterials: "", urls: "", fileName: "", fileType: "application/pdf", fileSize: "", fileDescription: "", requiredFacts: "", requiredTerms: "", prohibitedClaims: "", limitations: "", notes: "", channels: ["BLOG", "LINKEDIN", "INSTAGRAM"], executionMode: "DETERMINISTIC" };
const steps = ["Objective", "Audience and message", "Materials", "Editorial rules", "Channels", "Execution", "Confirmation"] as const;
export type DraftValidationCode = "OBJECTIVE_REQUIRED" | "AUDIENCE_REQUIRED" | "FACT_REQUIRED" | "CHANNEL_REQUIRED";
export function validateDraftStep(step: number, value: PublisherDraft): readonly DraftValidationCode[] { const errors: DraftValidationCode[] = []; if (step === 1 && (!value.title.trim() || !value.communicationNeed.trim() || !value.objective.trim() || !value.expectedOutcome.trim())) errors.push("OBJECTIVE_REQUIRED"); if (step === 2 && (!value.audience.trim() || !value.centralMessage.trim() || !value.tone.trim())) errors.push("AUDIENCE_REQUIRED"); if (step === 4 && !value.requiredFacts.trim()) errors.push("FACT_REQUIRED"); if (step === 5 && value.channels.length === 0) errors.push("CHANNEL_REQUIRED"); return errors; }
const validationMessage = (code: DraftValidationCode) => ({ OBJECTIVE_REQUIRED: translate("validation.objectiveRequired"), AUDIENCE_REQUIRED: translate("validation.audienceRequired"), FACT_REQUIRED: translate("validation.factRequired"), CHANNEL_REQUIRED: translate("validation.channelRequired") })[code];

export function EditorialContextWizard() {
  const create = useCreateStaticProject(); const [step, setStep] = useState(1); const [draft, setDraft] = useState(initial); const [errors, setErrors] = useState<readonly DraftValidationCode[]>([]);
  const set = <K extends keyof PublisherDraft>(key: K, value: PublisherDraft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  function next() { const nextErrors = validateDraftStep(step, draft); setErrors(nextErrors); if (!nextErrors.length) setStep((current) => Math.min(7, current + 1)); }
  function toggle(channel: Channel) { set("channels", draft.channels.includes(channel) ? draft.channels.filter((item) => item !== channel) : [...draft.channels, channel]); }
  return <div className="wizard-page"><header className="wizard-header"><NavLink to="/services/publisher">× Close</NavLink><strong>New Publisher Project</strong><span>Step {step} of 7</span></header><nav className="wizard-steps" aria-label="Editorial Context steps">{steps.map((label, index) => <button className={step === index + 1 ? "active" : step > index + 1 ? "complete" : ""} data-step={index + 1} key={label} onClick={() => index + 1 < step && setStep(index + 1)}><span>0{index + 1}</span>{label}</button>)}</nav><form className="wizard-body" onSubmit={(event) => event.preventDefault()}>
    {step === 1 ? <WizardSection kicker="Objective" title="What does this Project need to achieve?"><Field label="Project title"><input value={draft.title} onChange={(event) => set("title", event.target.value)} /></Field><Field label="What needs to be communicated"><textarea value={draft.communicationNeed} onChange={(event) => set("communicationNeed", event.target.value)} /></Field><Field label="Communication objective"><textarea value={draft.objective} onChange={(event) => set("objective", event.target.value)} /></Field><Field label="Expected outcome"><textarea value={draft.expectedOutcome} onChange={(event) => set("expectedOutcome", event.target.value)} /></Field><Field label="Deliverable language"><input value={draft.contentLanguage} onChange={(event) => set("contentLanguage", event.target.value)} /></Field></WizardSection> : null}
    {step === 2 ? <WizardSection kicker="Audience and message" title="Which message must remain intact?"><Field label="Audience"><textarea value={draft.audience} onChange={(event) => set("audience", event.target.value)} /></Field><Field label="Central message"><textarea value={draft.centralMessage} onChange={(event) => set("centralMessage", event.target.value)} /></Field><Field label="Tone"><input value={draft.tone} onChange={(event) => set("tone", event.target.value)} /></Field><Field label="Optional CTA"><input value={draft.callToAction} onChange={(event) => set("callToAction", event.target.value)} /></Field></WizardSection> : null}
    {step === 3 ? <WizardSection kicker="Materials" title="Give the team the context it needs."><Field label="Text materials"><textarea value={draft.textualMaterials} onChange={(event) => set("textualMaterials", event.target.value)} /></Field><Field label="Reference URLs"><textarea placeholder="One URL per line" value={draft.urls} onChange={(event) => set("urls", event.target.value)} /></Field><div className="wizard-file-grid"><Field label="File name"><input value={draft.fileName} onChange={(event) => set("fileName", event.target.value)} /></Field><Field label="Type"><input value={draft.fileType} onChange={(event) => set("fileType", event.target.value)} /></Field><Field label="Size"><input placeholder="2.4 MB" value={draft.fileSize} onChange={(event) => set("fileSize", event.target.value)} /></Field><Field label="Description"><input value={draft.fileDescription} onChange={(event) => set("fileDescription", event.target.value)} /></Field></div><p className="wizard-note">URLs are not accessed. Only file metadata remains in memory; no file bytes are processed.</p></WizardSection> : null}
    {step === 4 ? <WizardSection kicker="Editorial rules" title="What must the team preserve or avoid?"><Field label="Required facts"><textarea placeholder="One item per line" value={draft.requiredFacts} onChange={(event) => set("requiredFacts", event.target.value)} /></Field><Field label="Required terms"><textarea value={draft.requiredTerms} onChange={(event) => set("requiredTerms", event.target.value)} /></Field><Field label="Prohibited claims"><textarea value={draft.prohibitedClaims} onChange={(event) => set("prohibitedClaims", event.target.value)} /></Field><Field label="Limitations"><textarea value={draft.limitations} onChange={(event) => set("limitations", event.target.value)} /></Field><Field label="Additional notes"><textarea value={draft.notes} onChange={(event) => set("notes", event.target.value)} /></Field></WizardSection> : null}
    {step === 5 ? <WizardSection kicker="Channels" title="Where should the package be adapted?"><div className="channel-choices">{(["BLOG", "LINKEDIN", "INSTAGRAM"] as const).map((channel) => <label key={channel}><input checked={draft.channels.includes(channel)} onChange={() => toggle(channel)} type="checkbox" /><strong>{channel === "BLOG" ? "Blog" : channel === "LINKEDIN" ? "LinkedIn" : "Instagram"}</strong><span>{channel === "INSTAGRAM" ? "Caption and carousel script" : "Adapted text content"}</span></label>)}</div></WizardSection> : null}
    {step === 6 ? <WizardSection kicker="Execution" title="How should the team demonstrate its work?"><div className="execution-choices"><label><input checked={draft.executionMode === "DETERMINISTIC"} name="mode" onChange={() => set("executionMode", "DETERMINISTIC")} type="radio" /><strong>Deterministic demonstration</strong><span>Runs the journey with reproducible fixtures.</span></label><label><input checked={draft.executionMode === "BYOK"} name="mode" onChange={() => set("executionMode", "BYOK")} type="radio" /><strong>Use my AI model</strong><span>Demonstrates configuration only; no real request is made.</span></label></div>{draft.executionMode === "BYOK" ? <p className="wizard-note">Configure the visual state under <NavLink to="/settings/ai">AI Models</NavLink>. No credential is stored.</p> : null}</WizardSection> : null}
    {step === 7 ? <WizardSection kicker="Confirmation" title="You will receive"><div className="confirmation-outcomes">{["Editorial Core for approval", "Editorial strategy", "Blog article", "LinkedIn post", "Instagram caption and carousel", "Consistency report", "Final Editorial Package"].map((label, index) => <article key={label}><span>0{index + 1}</span><strong>{label}</strong></article>)}</div><div className="confirmation-details"><article><span>Expected team</span><p>Context analyst · Editorial strategist · Channel specialist · Consistency reviewer</p></article><article><span>Human control</span><p>Editorial Core approval · Final package approval</p></article><article><span>Consumption</span><p>Estimated consumption: 24 execution units</p></article><article><span>Boundary</span><p>No external publication will be performed.</p></article></div></WizardSection> : null}
    {errors.length ? <div className="wizard-errors" role="alert">{errors.map((error) => <p key={error}>{validationMessage(error)}</p>)}</div> : null}
  </form><footer className="wizard-footer-static"><button disabled={step === 1} onClick={() => { setErrors([]); setStep((current) => current - 1); }}>Back</button><p>Memory-only state; reloading removes created Projects.</p>{step < 7 ? <button className="agency-primary" data-action="continue" onClick={next}>{translate("actions.continue")} →</button> : <button className="agency-primary" data-action="create-project" onClick={() => create(draft)}>{translate("actions.createProject")} →</button>}</footer></div>;
}
function WizardSection({ kicker, title, children }: { readonly kicker: string; readonly title: string; readonly children: ReactNode }) { return <section className="wizard-section"><p className="agency-kicker">{kicker}</p><h1>{title}</h1><div>{children}</div></section>; }
function Field({ label, children }: { readonly label: string; readonly children: ReactElement<{ id?: string }> }) { const id = `wizard-${label.toLowerCase().replace(/[^a-z0-9]+/gu, "-")}`; return <label htmlFor={id}>{label}{cloneElement(children, { id })}</label>; }
