import { NavLink, useSearchParams } from "react-router-dom";
import { useStaticPublisher } from "../StaticPublisherProvider.js";
import { visibleStageLabel } from "../state-machine.js";

export function ProjectListPage() {
  const store = useStaticPublisher(); const [params, setParams] = useSearchParams(); const state = params.get("state");
  if (state === "loading") return <div className="agency-state"><span className="agency-loader" /><h1>Carregando Projetos</h1><button onClick={() => setParams({})}>Mostrar resultado</button></div>;
  if (state === "error") return <div className="agency-state error"><span>!</span><h1>Não foi possível carregar seus Projetos</h1><p>A falha é simulada para validar a recuperação.</p><button onClick={() => setParams({})}>Tentar novamente</button></div>;
  const projects = state === "empty" ? [] : store.projects;
  return <div className="agency-page project-list-page"><header className="agency-page-header"><div><p className="agency-kicker">Seus trabalhos</p><h1>Projetos</h1><p>Contexto, Estratégia, Conteúdos, Revisão e Entrega em um único workspace.</p></div><NavLink className="agency-primary" to="/services/publisher/new">+ Novo Projeto</NavLink></header><div className="state-demo-links"><span>Demonstrar estado:</span><button onClick={() => setParams({ state: "empty" })}>vazio</button><button onClick={() => setParams({ state: "loading" })}>loading</button><button onClick={() => setParams({ state: "error" })}>erro</button></div>{projects.length === 0 ? <div className="agency-state"><h2>Você ainda não possui Projetos.</h2><NavLink className="agency-primary" to="/services/publisher/new">Criar primeiro Projeto</NavLink></div> : <section className="project-cards">{projects.map((project, index) => <NavLink className="project-card" key={project.projectId} to={`/projects/${project.projectId}/context`}><span>0{index + 1}</span><div><small>{project.product.name}</small><h2>{project.title}</h2><p>{visibleStageLabel(project.visibleStage)}</p></div><dl><div><dt>Canais</dt><dd>Blog · LinkedIn · Instagram</dd></div><div><dt>Execução</dt><dd>{project.executionMode === "BYOK" ? "Meu modelo" : "Demonstração"}</dd></div><div><dt>Pendência</dt><dd>{project.pendingHumanAction ?? "Nenhuma"}</dd></div><div><dt>Entrega</dt><dd>{project.status === "READY_FOR_DELIVERY" ? "Pronta" : "Em preparação"}</dd></div></dl><time>{new Date(project.updatedAt).toLocaleDateString("pt-BR")}</time><b>→</b></NavLink>)}</section>}</div>;
}
