import { NavLink, useSearchParams } from "react-router-dom";
import { formatDate, translate } from "../../i18n/index.js";
import { useStaticPublisher } from "../StaticPublisherProvider.js";
import { visibleStageLabel } from "../state-machine.js";
export function ProjectListPage() {
  const store = useStaticPublisher(); const [params, setParams] = useSearchParams(); const state = params.get("state");
  if (state === "loading") return <div className="agency-state"><span className="agency-loader" /><h1>{translate("status.loadingProjects")}</h1><button onClick={() => setParams({})}>Show result</button></div>;
  if (state === "error") return <div className="agency-state error"><span>!</span><h1>We could not load your Projects</h1><p>This simulated failure validates recovery behavior.</p><button data-action="retry" onClick={() => setParams({})}>{translate("actions.retry")}</button></div>;
  const projects = state === "empty" ? [] : store.projects;
  return <div className="agency-page project-list-page"><header className="agency-page-header"><div><p className="agency-kicker">Your work</p><h1>Projects</h1><p>Editorial Context, Strategy, Content, Review, and Delivery in one workspace.</p></div><NavLink className="agency-primary" data-action="create-project" to="/services/publisher/new">+ New Project</NavLink></header><div className="state-demo-links"><span>Demonstrate state:</span><button onClick={() => setParams({ state: "empty" })}>empty</button><button onClick={() => setParams({ state: "loading" })}>loading</button><button onClick={() => setParams({ state: "error" })}>error</button></div>{projects.length === 0 ? <div className="agency-state"><h2>{translate("status.noProjects")}</h2><NavLink className="agency-primary" to="/services/publisher/new">Create your first Project</NavLink></div> : <section className="project-cards">{projects.map((project, index) => <NavLink className="project-card" key={project.projectId} to={`/projects/${project.projectId}/context`}><span>0{index + 1}</span><div><small>{project.product.name}</small><h2>{project.title}</h2><p>{visibleStageLabel(project.visibleStage)}</p></div><dl><div><dt>Channels</dt><dd>Blog · LinkedIn · Instagram</dd></div><div><dt>Execution</dt><dd>{project.executionMode === "BYOK" ? "My model" : "Demonstration"}</dd></div><div><dt>Pending action</dt><dd>{project.pendingHumanAction ?? "None"}</dd></div><div><dt>Delivery</dt><dd>{project.status === "READY_FOR_DELIVERY" ? "Ready" : "In preparation"}</dd></div></dl><time>{formatDate(project.updatedAt)}</time><b>→</b></NavLink>)}</section>}</div>;
}
